### ISSUE TITLE
Does SDK provide automatic fallback to another region?

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [Azure/azure-cosmos-dotnet-v3#1109]
SDK V2 had a property called `PreferredLocations` where I was able to manually specify the fallback regions. SDK v3 has new property called `CosmosClientOption.ApplicationRegion`, which should be set to the closest region where an app is deployed. [According to the documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.applicationregion?view=azure-dotnet), SDK should discover the fallback region and their priority automatically. Is it true?

Our app and it's DB are located in the WUE region. For performance and availability reasons, we have introduced a read region in Central US. Last night we have noticed a very short outage of the CosmosDB in West-Europe region and we have spotted an error which says that there were no attempts to call the fallback region. 
From the exception message:

> [...] The request failed because the client was unable to establish connections to 4 endpoints across 1 regions.

> [...] RequestEndTime: 2019-12-17T02:57:13.8433981Z,  Number of regions attempted:1ResponseTime: 2019-12-17T02:56:46.3849439Z, StoreResult: StorePhysicalAddress

Shouldn't SDK call the Central US region for read?

Full message:

>  Microsoft.Azure.Documents.ServiceUnavailableException: The request failed because the client was unable to establish connections to 4 endpoints across 1 regions. Please check for client resource starvation issues and verify connectivity between client and server.ActivityId: 0cc5acfc-b87c-403d-9f69-719f6059ec95, RequestStartTime: 2019-12-17T02:56:42.5697581Z, RequestEndTime: 2019-12-17T02:57:13.8433981Z,  Number of regions attempted:1ResponseTime: 2019-12-17T02:56:46.3849439Z, StoreResult: StorePhysicalAddress: rntbd://am4prdddc11-docdb-2.documents.azure.com:14308/apps/919f03de-8bbf-4ea1-ad94-ca78b0bb1f81/services/ea9fec95-c353-4dcf-a822-07dee71326e3/partitions/0c87aa95-a650-4fc7-a3da-69231a1bf146/replicas/132101238083627172s/, LSN: -1, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: False, StatusCode: 410, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: True, TransportException: A client transport error occurred: SSL negotiation timed out. (Time: 2019-12-17T02:56:46.3747303Z, activity ID: 303c25a9-3e20-4f50-a2fb-44036caf4098, error code: SslNegotiationTimeout [0x0008], base error: HRESULT 0x80131500, URI: rntbd://am4prdddc11-docdb-2.documents.azure.com:14308/, connection: 10.94.188.245:50604 -> 13.94.201.5:14308, payload sent: False, CPU history: not available, CPU count: 1), ResourceType: Document, OperationType: ReadResponseTime: 2019-12-17T02:56:51.6665165Z, StoreResult: StorePhysicalAddress: rntbd://am4prdddc11-docdb-2.documents.azure.com:14157/apps/919f03de-8bbf-4ea1-ad94-ca78b0bb1f81/services/ea9fec95-c353-4dcf-a822-07dee71326e3/partitions/0c87aa95-a650-4fc7-a3da-69231a1bf146/replicas/132174023102344205p/, LSN: -1, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: False, StatusCode: 410, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: True, TransportException: A client transport error occurred: SSL negotiation timed out. (Time: 2019-12-17T02:56:51.6652065Z, activity ID: 0cc5acfc-b87c-403d-9f69-719f6059ec95, error code: SslNegotiationTimeout [0x0008], base error: HRESULT 0x80131500, URI: rntbd://am4prdddc11-docdb-2.documents.azure.com:14157/, connection: 10.94.188.245:50611 -> 13.94.201.5:14157, payload sent: False, CPU history: not available, CPU count: 1), ResourceType: Document, OperationType: ReadResponseTime: 2019-12-17T02:56:56.9659692Z, StoreResult: StorePhysicalAddress: rntbd://am4prdddc11-docdb-2.documents.azure.com:14314/apps/919f03de-8bbf-4ea1-ad94-ca78b0bb1f81/services/ea9fec95-c353-4dcf-a822-07dee71326e3/partitions/0c87aa95-a650-4fc7-a3da-69231a1bf146/replicas/132126033893966872s/, LSN: -1, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: False, StatusCode: 410, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: True, TransportException: A client transport error occurred: SSL negotiation timed out. (Time: 2019-12-17T02:56:56.9581932Z, activity ID: 0cc5acfc-b87c-403d-9f69-719f6059ec95, error code: SslNegotiationTimeout [0x0008], base error: HRESULT 0x80131500, URI: rntbd://am4prdddc11-docdb-2.documents.azure.com:14314/, connection: 10.94.188.245:50618 -> 13.94.201.5:14314, payload sent: False, CPU history: not available, CPU count: 1), ResourceType: Document, OperationType: ReadResponseTime: 2019-12-17T02:57:04.6410281Z, StoreResult: StorePhysicalAddress: rntbd://am4prdddc11-docdb-2.documents.azure.com:14362/apps/919f03de-8bbf-4ea1-ad94-ca78b0bb1f81/services/ea9fec95-c353-4dcf-a822-07dee71326e3/partitions/0c87aa95-a650-4fc7-a3da-69231a1bf146/replicas/132145379747507783s/, LSN: -1, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: False, StatusCode: 410, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: True, TransportException: A client transport error occurred: SSL negotiation timed out. (Time: 2019-12-17T02:57:04.6397259Z, activity ID: 0cc5acfc-b87c-403d-9f69-719f6059ec95, error code: SslNegotiationTimeout [0x0008], base error: HRESULT 0x80131500, URI: rntbd://am4prdddc11-docdb-2.documents.azure.com:14362/, connection: 10.94.188.245:50625 -> 13.94.201.5:14362, payload sent: False, CPU history: not available, CPU count: 1), ResourceType: Document, OperationType: ReadResponseTime: 2019-12-17T02:57:13.8433981Z, StoreResult: StorePhysicalAddress: rntbd://am4prdddc11-docdb-2.documents.azure.com:14362/apps/919f03de-8bbf-4ea1-ad94-ca78b0bb1f81/services/ea9fec95-c353-4dcf-a822-07dee71326e3/partitions/0c87aa95-a650-4fc7-a3da-69231a1bf146/replicas/132145379747507783s/, LSN: -1, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: False, StatusCode: 410, SubStatusCode: 0, RequestCharge: 0, ItemLSN: -1, SessionToken: , UsingLocalLSN: True, TransportException: A client transport error occurred: Sending the request timed out. (Time: 2019-12-17T02:57:13.8414834Z, activity ID: 0cc5acfc-b87c-403d-9f69-719f6059ec95, error code: SendTimeout [0x000E], base error: HRESULT 0x80131500, URI: rntbd://am4prdddc11-docdb-2.documents.azure.com:14362/, connection: 10.94.188.245:50643 -> 13.94.201.5:14362, payload sent: False, CPU history: not available, CPU count: 1), ResourceType: Document, OperationType: Read, Windows/10.0.14393 cosmos-netstandard-sdk/3.4.2 ---> Microsoft.Azure.Documents.GoneException: The requested resource is no longer available at the server.ActivityId: 0cc5acfc-b87c-403d-9f69-719f6059ec95, Windows/10.0.14393 cosmos-netstandard-sdk/3.4.2   at Microsoft.Azure.Documents.TimeoutHelper.ThrowGoneIfElapsed()   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicasInternalAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicaAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)   at Microsoft.Azure.Documents.ConsistencyReader.ReadSessionAsync(DocumentServiceRequest entity, ReadMode readMode)   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass26_0.<<InvokeAsync>b__0>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)   --- End of inner exception stack trace ---   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy, Func`2 prepareRequestAsyncDelegate)   at Microsoft.Azure.Documents.ServerStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)

**Comment by ealsur** [comment]
SDK will fallback to other regions if a region outage is detected, but this is not the case.

Disecting the stack trace we see that the SDK did retry on 4 different endpoints:

* rntbd://am4prdddc11-docdb-2.documents.azure.com:14308/apps/919f03de-8bbf-4ea1-ad94-ca78b0bb1f81/services/ea9fec95-c353-4dcf-a822-07dee71326e3/partitions/0c87aa95-a650-4fc7-a3da-69231a1bf146/replicas/132101238083627172s
* rntbd://am4prdddc11-docdb-2.documents.azure.com:14157/apps/919f03de-8bbf-4ea1-ad94-ca78b0bb1f81/services/ea9fec95-c353-4dcf-a822-07dee71326e3/partitions/0c87aa95-a650-4fc7-a3da-69231a1bf146/replicas/132174023102344205p/
* rntbd://am4prdddc11-docdb-2.documents.azure.com:14314/apps/919f03de-8bbf-4ea1-ad94-ca78b0bb1f81/services/ea9fec95-c353-4dcf-a822-07dee71326e3/partitions/0c87aa95-a650-4fc7-a3da-69231a1bf146/replicas/132126033893966872s/
* rntbd://am4prdddc11-docdb-2.documents.azure.com:14362/apps/919f03de-8bbf-4ea1-ad94-ca78b0bb1f81/services/ea9fec95-c353-4dcf-a822-07dee71326e3/partitions/0c87aa95-a650-4fc7-a3da-69231a1bf146/replicas/132145379747507783s/

All 4 attempts faced the same client-side issue:

TransportException: A client transport error occurred: SSL negotiation timed out. error code: SslNegotiationTimeout [0x0008], base error: HRESULT 0x80131500

A connection was established from the client's point of view, but the security handshake timed out. Can be caused by:

* Genuinely slow connection establishment and TLS negotiation, e.g. due to network congestion or host overload.
* Half-connected sockets. This can happen with a crashed or hung server process that the kernel didn't clean up yet. The client TCP stack sends SYN, the server TCP stack responds with SYN+ACK (this happens in the kernel and does not involve application code). When the client receives SYN+ACK, the TCP stack sends back ACK to the server, and considers the connection established. However, on the server, nothing retrieves the socket from the accept queue. The client attempts SSL negotiation, which involves application code on both endpoints. The operation times out.
* Half-failed or failed connections. This can happen if the TCP 3-way handshake makes it all the way through, and then the network fails during SSL negotiation. This can happen due to a network device failure, in which case the client failures will be transient, but we've also seen one instance of persistent connection failures where a configuration bug in Azure Networking caused the TCP 3-way handshake to succeed, followed by the connection entering a half-failed state (client->server messages would go across, but server->client messages would not).

I would check metrics on the instance, following https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-dot-net-sdk#request-timeouts, CPU and resource usage on the instance, SNAT port limits too.

Does it repro constantly? Is the code running locally or in the cloud? Does the network have any VPN/proxy?

**Comment by lukasz-pyrzyk** [comment]
Thank you for the great explanation. 

The issue is not reproducing and it has happened only once. CPU/Memory/SNAT port mapping looks ok. However, I did some digging and have occurred an Azure worker upgrade, so our app was moved to a different worker. The exception comes from the connection which was interrupted by the movement.
