### ISSUE TITLE
V3 SDK gives error: CS0012 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

### ISSUE THREAD

**Issue by msomanathan** [Azure/azure-cosmos-dotnet-v3#1147]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I am using SDK V3.5.1. When calling any of the APIs, like, CosmosClient.GetDatabase(id), I get compile error.

**To Reproduce**
This issue happens in a project that is managed by CoreXT. On a brand-new standalone console app, this seems to work without any issues. Below is code snippet:
var client = new CosmosClient(uri, key, new CosmosClientOptions {AllowBulkExecution = true});
Database db = client.GetDatabase("foo");

**Expected behavior**
No compile error.

**Actual behavior**
Compile error on the client.GetDatabase() call is got:
CS0012 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

**Environment summary**
SDK Version: 3.5.1
OS Version (e.g. Windows, Linux, MacOSX): Windows 10

**Additional context**
My .NET framework version is 4.6.2.

**Comment by ealsur** [comment]
Can you share the csproj you are using? Are there any linked projects involved?

**Comment by msomanathan** [comment]
[csproj.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/4048745/csproj.txt)

**Comment by ealsur** [comment]
This is a NET 4.6.2 with an old VS version (12.0), please see: https://github.com/dotnet/standard/issues/542

The workaround seems to be to add `<Reference Include="netstandard" />` to the CSPROJ.

It seems it got fixed in newer versions of VS, reference https://github.com/microsoft/msbuild/pull/2567

**Comment by brcaswell** [comment]
FYI @ealsur that 2017 fix merge and changes are for files that don't even exist in src anymore - since they have been refactored.  (looking at the code, there also may have actually been a bug in that logic when introduced)

Is VS versioning even a consider to this?  I don't see any logic reflected on it here, (and I wouldn't really expect it to be), and this is the logic that would otherwise introduce those references right?

https://github.com/dotnet/sdk/blob/cbe020c4525dd4120de98bda9b90cf06f2477f33/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L80

**Comment by brcaswell** [comment]
I didn't realize this was in an azure repo.. should probably be moved to dotnet\sdk perhaps?
