### ISSUE TITLE
Missing change set (partitions) on change feed processor

### ISSUE THREAD

**Issue by ekjuanrejon** [Azure/azure-cosmos-dotnet-v3#1159]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Change feed, missing partition. Currently using CosmosDb for Event Sourcing. Using the change feed to build projections. However, We seem to be missing events (Partitions) from the change feed

**To Reproduce**
Create loads of documents, and use the changed feed to "replay" from the beginning

**Expected behavior**
Projection is correct built

**Actual behavior**
Missing some change sets from the change feed

**Comment by ealsur** [comment]
Do you have a repro code that we can use to reproduce the issue?

What you are saying is that some changes are missing when you use the Change Feed Processor to read the changes from the beginning?

* Where are you measuring the "misses"? Are you logging all documents at the **beginning of your delegate code**?
* Do you have multiple Change Feed Processor instances with the same `processorName` and `InstanceName`?
* If you capture the state of your Leases Container, all Lease documents should have an Owner, which is the name of the Instance/s that you have running, how is that state?

**Comment by ekjuanrejon** [comment]
Unfortunately our code is private, company code. We can schedule a zoom call sometime next week

**Comment by ealsur** [comment]
Can you troubleshoot the steps at least? The only scenarios where we saw changes being "missed" is basically the ones described in those points, the first 2 being the most common ones.

* If your Processor receives the changes and sends them to another destination and you are measuring "misses" on the destination, that does not mean the Processor is not reporting them to your delegate, the issue could be in the delegate code that is sending those events, so you need to measure/verify on the origin.
* Multiple instances with the same `processorName` and same `InstanceName` act as the same unit, so only one of them will receive changes, not all. See https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor#dynamic-scaling

**Comment by ealsur** [comment]
Please reopen with troubleshooting results. Without any repro code or any information, it's not possible to do any analysis or investigation.

**Comment by luke-asos** [comment]
> * Multiple instances with the same `processorName` and same `InstanceName` act as the same unit, so only one of them will receive changes, not all. See https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor#dynamic-scaling

Can you confirm what you have said is correct? For a single partitioned db I get this behaviour by having different `InstanceName`s; when `ProcessorName` and `InstanceName` are the same then all instances receive the changes.

**Comment by lukermjones** [comment]
> * Multiple instances with the same `processorName` and same `InstanceName` act as the same unit, so only one of them will receive changes, not all. See https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor#dynamic-scaling

Can you confirm what you have said is correct? For a single partitioned db I get this behaviour by having different `InstanceName`s; when `ProcessorName` and `InstanceName` are the same then all instances receive the changes.

**Comment by ealsur** [comment]
That sounds weird.

Here is how internally this works:

1. ProcessorName defines the leases prefix, each different ProcessorName will have it's own independent set of leases. 
1. InstanceName is used as the current processor instance identifier.
1. A lease can be owned by only a single Instance at any given time.

If you have 2 machines, with same ProcessorName AND same InstanceName, they are acting as the same unit, so when selecting which leases to use, both units will try to take the same leases, one of them will win over the other.

There could be the effect of both instances are constantly fighting over the same lease (single partition), so the lease is owned by one instance for some time until the other steals it because it has the same name, it's not a defined behavior.

**Comment by lukermjones** [comment]
In this example, as the lease prefix and instance name are the same, is it not the case that there is no disambiguating information between the instances (i.e., they are effectively the same instance unit) and therefore they both "get" the lease? 

> There could be the effect of both instances are constantly fighting over the same lease (single partition), so the lease is owned by one instance for some time until the other steals it because it has the same name, it's not a defined behavior.

In this case wouldn't the expected behaviour be that one instance picks up one change and then randomly another instance picks up a different change, not both picking up the same change?
Every test I've ran (multiple local instances and instances on separate machines; emulated db and non-emulated) end in the same result: each instance receiving the same message.
