### ISSUE TITLE
Can a race condition exist in stored procedures?

### ISSUE THREAD

**Issue by justinbhopper** [Azure/azure-cosmos-dotnet-v3#1188]
I have a stored procedure that performs a query before inserting a document.  The point of the query is to check for other documents within the same partition according to a unique constraint I am trying to enforce.  The stored procedure only inserts if there are zero results from the query check, otherwise it returns an error indicating the unique constraint would have been violated.

Assuming my account has a Strong default consistency level, is it possible for a race condition to occur if there are two simultaneous executions of this stored procedure?  If so, does this mean that Cosmos only executes one stored procedure at a time per partition while in Strong consistency?

**Comment by j82w** [comment]
Hi @justinbhopper ,

Is there any reason you aren't leveraging [unique keys](https://docs.microsoft.com/en-us/azure/cosmos-db/unique-keys)? 

I suggest reading the Stored Procedure [documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/stored-procedures-triggers-udfs) which explains ACID property guarantees.

**Comment by justinbhopper** [comment]
@j82w The uniqueness check is provided by the caller of our API via a [If-None-Match header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match).  It isn't something we know ahead of time, but we still want to give a guarantee for the caller before their insert is committed.

I have read the ACID documentation, but I don't feel it answers the question.  See here for similar discussions about whether [ACID prevent race conditions](https://stackoverflow.com/questions/6477574/do-database-transactions-prevent-race-conditions).  The article suggests it does not, hence my question to the Azure team.  

SQL Server, for example, uses row-locking to ensure that deadlocks are detected.  My understanding is that only locking can truly protect against a classic race condition like this.  Since Cosmos doesn't have this concept, my guess is a race condition _can_ occur.

**Comment by mkolt** [comment]
@justinbhopper for sprocs consistency on collection or request doesn't matter because sproc always runs on primary replica (essentially means it's strong consistency). But sprocs can run concurrently, there is no restriction to serialize them. Also sproc runs in "snapshot isolation" which means that sproc transaction it takes snapshot at start and all reads from this execution will only see docs in state when snapshot was taken, so if another sproc concurrently updated a doc, read wouldn't see that. This means that you can use such reads for checking your own unique constraints.

But that shouldn't be a problem. If you want, you can make sure that only one instance of sproc is running per (logical) PK value (as sproc execution is per given to request partition key and can only address docs that have same PK value). You can use uniqueness constraints: unique key or simply document id (id + PK pair is always unique), so let's say in the sproc we create a document with id = 'lock'. Once one sproc instance creates it, all other concurrent instances (ran with same PK value) will fail (in fact they fail at the time of create call and not commit time). So, this gives us only one sproc instance at a time. Then you do what you need and in the end remove the 'lock' document.

Would that work for your scenario?

**Comment by justinbhopper** [comment]
@mkolt Thank you for the explanation, and also the additional suggestions.  Indeed, I do use the "document as a lock" technique for a few reasons already, and Cosmos's TTL feature makes this concept very reliable.

Your explanation of snapshot isolation was very helpful.  I had the same theory, so I solved my problem by swapping the sproc's logic.  Instead of check-then-insert, I do an insert-then-check.  If my "uniqueness condition" results in any documents (aside from the one I just inserted), I throw an error and Cosmos will rollback the document that was inserted.  Its still possible for two instances to race one another, but now at least the outcome will be that neither cause an insert, rather than both.

I can imagine conditional unique keys being useful, but in our case it likely won't be.  We're storing our data in a way that puts all search data into a generic form.  This allows us to normalize our searchable data and also makes the search queries easier to generate.  This also means, however, that we're avoiding trying to teach the container about the shape of our data.  See [Microsoft's FHIR Server](https://github.com/microsoft/fhir-server/blob/master/docs/Search.md) for more information on the topic - we took inspiration from their strategy.

Thanks again for the feedback!
