### ISSUE TITLE
ReadItemAsync on non existent record throws CosmosException instead of returning HttpStatusCode.NotFound 

### ISSUE THREAD

**Issue by apulliam** [Azure/azure-cosmos-dotnet-v3#1264]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
The documentation does not indicate that an exception will be thrown when there is an attempt to read a non existent record.  An exception should not be thrown for resource not found when the API provides an option to return HtttpStatusCode.NotFound.  This violates expected behavior, and there is no reliable way to programmatically handle the error, short of parsing the error message.

**To Reproduce**
Call ReadItemAsync for any non existent record.

**Expected behavior**
The call should return with HttpStatusCode.NotFound. It should not throw an exception.

**Actual behavior**
Method throws CosmosException with the message "Response status code does not indicate success: 404 Substatus: 0 Reason: ({
  "Errors": [
    "Resource Not Found"
  ]
})." 

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
Hi @apulliam ,

The CosmosException has a [HttpStatusCode property](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c1c84bf268d3c37a8a32d7ca29e38466bc2ec9ff/Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs#L80) on it. You can see a sample on how to catch specific status [here](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/8b551ce25f5752bcb3c399865fde7f9e1a8f4bdd/Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Program.cs#L264).

```
try
{
       ItemResponse<SalesOrder> response = await container.ReadItemAsync<SalesOrder>(
                partitionKey: new PartitionKey("Account1"),
                id: "SalesOrder1");
}
catch(CosmosException ex) when (ex.StatusCode == HttpStatusCode.NotFound)
{ 
}
```

The [stream APIs](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c1c84bf268d3c37a8a32d7ca29e38466bc2ec9ff/Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs#L222) are a little more complex because of the stream management and serialization. They are more performant by avoiding throwing any service exceptions. They get returned as a [ResponseMessage ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c1c84bf268d3c37a8a32d7ca29e38466bc2ec9ff/Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs#L84)and have a HttpStatusCode on them.

**Comment by apulliam** [comment]
Not a good behavior to throw an exception for an expected result.  At very least, I think the docs need to be updated to add 404 Not found to the expected exception status codes:


StatusCode | Reason for exception
-- | --
429 | TooManyRequests - This means you have exceeded the number of request units per second.

**Comment by j82w** [comment]
@apulliam can you please point to the docs that are missing it?

There has been several [discussions ](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/692#issuecomment-521450353)on throwing 404. The stream APIs will not throw the exception  if you want an exceptionless pipeline.

**Comment by sdg002** [comment]
It took me some effort to reach this page and get to know that the method `ReadItemAsync`  throws an exception when item does not exist. 
I would expect the product team to update the XML docs for this method so that intellisense can give me guidance from within Visual Studio. Do not throw away the good things of .NET Framework/VS.NET

Thank you.
