### ISSUE TITLE
Microsoft.Azure.Cosmos package ref folder lacks XML doc and is incompatible with reflection

### ISSUE THREAD

**Issue by pentp** [Azure/azure-cosmos-dotnet-v3#1281]
**Describe the bug**
1. Microsoft.Azure.Cosmos.Client.xml exists only in the `lib` folder, but not in `ref`. This means there is absolutely no documentation shown inside VS.
2. Microsoft.Azure.Cosmos.Client.dll inside `ref` is not an actual ref assembly (it's just a copy of the same assembly from the lib folder). This means that it contains unresolvable references to other assemblies (e.g., `Microsoft.Azure.Cosmos.Core.dll`) and is unusable by reflecation based tools (e.g., OrleansCodeGenerator).

**Expected behavior**
`ref` folder contains an actual [ref assembly](https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md) (with no code and no invalid references to other assemblies) and also contains `Microsoft.Azure.Cosmos.Client.xml`.

**Environment summary**
SDK Version: 3.6.0

**Comment by pentp** [comment]
#1304 only fixed the first part (missing xml docs), but the assembly in ref folder is still not an actual ref assembly

**Comment by Pilchie** [comment]
If we're not actually producing a ref assembly, we should be able to just eliminate the entire ref folder, and NuGet will add references to the assemblies in the lib folder.

**Comment by rinatmini** [comment]
Yeah, we are currently not producing a ref assembly (reverted in #1922 ). From what I understand, it was due to the [NU5131 NuGet warning](https://github.com/NuGet/docs.microsoft.com-nuget/blob/master/docs/reference/errors-and-warnings/NU5131.md) that was introduced by an upgrade to NuGet.exe, which started enforcing additional NuGet rules.
To enable the production of ref assemblies again, we need to update the NuGet package build process to comply with the new rules (updating the .nuspec file).

**Comment by kirankumarkolli** [comment]
Linked the PR which removed the ref folder. 
+1 to not bring back ref folders.
