### ISSUE TITLE
ReplaceItemAsync no longer throws exception when document does not exist

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-cosmos-dotnet-v3#129]
It looks like when you try to replace a document that does not exist it no longer throws an exception like it did with v2. Is this the desired behavior?

**Comment by j82w** [comment]
Hi @mpaul31 ,

This is by design in v3 SDK. It was decided to not throw on 404 Not Found responses for the following reasons:

- Improved performance. Throwing and catching exceptions consumes a lot of resources.
- Improved user code. Most workflows consider not finding an item part of the normal workflow. This allows users to simply check for null rather than coding a try catch.

**Comment by mpaul31** [comment]
gotcha makes sense however not sure most would expect a call to ReplaceItemAsync to work this was when the intent is the resource is already there. Either way easy work around.

**Comment by j82w** [comment]
This was changed to throw in the GA version.
