### ISSUE TITLE
ReadItemAsync should not throw an exception on 404 NotFound

### ISSUE THREAD

**Issue by MrCochese** [Azure/azure-cosmos-dotnet-v3#1311]
**Is your feature request related to a problem? Please describe.**
ReadItemAsync throws an exception when 404 NotFound status returned. This is frustrating as I can see something inside the SDK has taken upon itself to break control flow, instead of leaving it to the consumer to deal with the response.

**Describe the solution you'd like**
Failed status code in the response object that already exists, with a null Resource. Exceptions are expensive and I do not want my code littered with try-catch sphagetti to deal with records that have not been created yet.

**Describe alternatives you've considered**
An alternative method could be supplied if the current implementation is really popular with people who love try-catch blocks or something. Exceptions in this instance ought to be reserved for transport level failure.

**Comment by j82w** [comment]
The [stream APIs](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/bec4b34277ef33cfcd27c60625a31e9b59a6b05b/Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs#L222) do not throw exceptions. 

There has already been many [issues](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/692) discussing this. The guidance from the central dot net team was to throw it. This also makes upgrades from v2 easier because it matches the same behavior. Why should 404 be different then any other failure status code like a conflict or throttle? This eventually leads to the exceptionless model which is done with the stream APIs.
