### ISSUE TITLE
Add optimization for non-aggregate single partition query.

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#1344]
## Scenario
Need a way to allow users to avoid getting the query plan for non-aggregate single partition key queries. Aggregate queries require the query plan so the SDK can properly aggregate query results.

## Problem
How to expose an option that allows users to skip the getting the query plan for non-aggregate single partition queries

## Current public surface for Query
```c#
container.GetItemQueryStreamIterator(QueryDefinition queryDefinition ,string continuationToken = null, QueryRequestOptions requestOptions = null);
container.GetItemQueryStreamIterator(string queryText ,string continuationToken = null, QueryRequestOptions requestOptions = null);
container.GetItemQueryIterator<T>(string queryText = null,  string continuationToken = null, QueryRequestOptions requestOptions = null);
container.GetItemQueryIterator<T>(QueryDefinition queryDefinition,  string continuationToken = null, QueryRequestOptions requestOptions = null);
container.GetItemQueryIterator<T>(QueryDefinition queryDefinition,  string continuationToken = null, QueryRequestOptions requestOptions = null);
container.GetItemLinqQueryable<T>(bool allowSynchronousQueryExecution = false, string continuationToken = null, QueryRequestOptions requestOptions = null);
```

### 1. Request Option flag:
Pros: Minimal surface area change. Work with all current overloads.
Cons: Very easy for user to incorrectly and will likely result in high CRIs. 
```C#
QueryRequestOption requestOption = new QueryRequestOption()
{
    EnableNonAggregateSinglePartitionOptimization = true;
}
```

### 2.  Explicit query overloads
Pros: More explicit which should result in lower CRIs
Cons: Increases the query surface area and complexity
```C#
container.GetItemQueryStreamIterator(
    QueryDefinition queryDefinition, 
    string continuationToken = null, 
    QueryRequestOptions requestOptions = null,
    EnableNonAggregateSinglePartitionOptimization = false);
```
```C#
container.GetItemQueryIterator<T>(
    QueryDefinition queryDefinition,  
    string continuationToken = null, 
    QueryRequestOptions requestOptions = null,
    EnableNonAggregateSinglePartitionOptimization = false);
```
```C#
container.GetItemLinqQueryable<T>(
    bool allowSynchronousQueryExecution = false, 
    string continuationToken = null, 
    QueryRequestOptions requestOptions = null,
    EnableNonAggregateSinglePartitionOptimization = false);`
```
### 3. Parse/Tokenize query using c# 
Pros: No API surface area changes. It might be possible to write a simple regex to check for all aggregate key words.
Cons: Complex and might introduce additional overhead costs

### 4. Only add support for LINQ
Pros: Linq already has the query parsed and can determine if it meets all the requirements for the optimization
Cons: No support for other APIs. Not sure how complex it will be to implement 

### 5. New API (@bchong95 suggestion)
Pros: Very explicit for users
Cons: Requires 3 new APIs
```C#
container.GetItemPassThroughLinqQueryable<T>(
    bool allowSynchronousQueryExecution = false, 
    string continuationToken = null, 
    QueryRequestOptions requestOptions = null)
```
```C#
container.GetItemPassThroughQueryStreamIterator(
    QueryDefinition queryDefinition, 
    string continuationToken = null, 
    QueryRequestOptions requestOptions = null);
```
```C#
container.GetItemPassThroughQueryIterator<T>(
    QueryDefinition queryDefinition,  
    string continuationToken = null, 
    QueryRequestOptions requestOptions = null);
```

## Open backend questions
1. If a header is set can the backend do the validation to block the request if it is an aggregate query?

**Comment by bchong95** [comment]
1 and 2 are error prone, since a user might opt into the behavior without really knowing what they are doing. For example using a feed option from a different query or just setting the parameter to true, since the name looks good. "Enable...Optimization?" ... "yeah why, not?". It's also not an optimization. It's trading off correctness checking for performance.

I would want this to be a separate method all together, since I don't want it to have anything to do with the ordinary query. So something like

```
container.GetPassthroughItemQueryIterator
```

3. Is not an option, since you can regex check to see if the query is only a single logical partition. ex.

```
SELECT * FROM c WHERE c.pk IN ("asdf")
```

4. I'm fine with this, since I think most people should go through LINQ anyways.

**Comment by bchong95** [comment]
One thing to note. 4 is valid option, but very difficult.

**Comment by kirankumarkolli** [comment]
Can the behavior error out in-case of unsupported scenarios? 
Ideal is to error out. If it can then then misuse at-least will be quickly detected by CX.

With-out it any sugar costing/lipstick is bound to get mis-used and unexpected results also.

**Comment by j82w** [comment]
I updated the suggestions based on @bchong95 comment.

3. Is it possible if it only used the `QueryRequestOption.PartitionKey` value instead of trying to get it from the query text?

4. Is the main reason it is difficult is trying to figure out the partition key restrictions?

**Comment by FabianMeiswinkel** [comment]
IMO 4) isn't an option. The scenarios where it would be most beneficial are often scenarios where customers run very simple queries - often directly in SQL (like getting all/top X documents of a logical partition which we don't support yet via native Api but force them to go through query Api)

If backend can easily identify setting the flag to skip creating queryPlan explicitly on the client is invalid and return a BadRequest I would prefer option 1 + early error detection.

I don't like 2) because ultimately it sounds like we want to have a server-site endpoint (Compute/Gateway) for distributed queries that would mean the new API isn't useful anymore, correct? In that case the clutter it is adding is not worth it.

Regarding Jake's comment - I hope QueryRequestOptions.PartitionKey or PartitionKeyRangeId - otherwise I think that is a reasonable constraint to limit this to scenarios where either the partition key is known - or it is known to be an intentional fan-out query (like in the OLTP spark connector)

**Comment by mbhaskar** [comment]
Option 4) which is a Linq based solution will not work for Java. 
I believe adding a flag would be more helpful.
We give the option of setting nonAggregateOptimization flag to the user. On client side we validate that this could be set only if partitionKey is set and will error out without hitting the backend if its not single partition query. Since user explicitly sets this param, we could throw a 400 back if the BE decides that this cannot be completed in a single continuation?

**Comment by Mortana89** [comment]
Not a fan of option 4 either. We barely use LINQ for our queries, only the very simple ones actually.

I prefer option 3. Prevents users from incorrectly setting the flag, however I understand that this is indeed pretty complex. It would require a pretty complex regex, and wouldn't that nil out the possible performance profit? Are we talking about lower ms or lower RU?

Option 1 would also be feasible albeit with An extra validation to check if partition key is provided perhaps?

**Comment by bchong95** [comment]
Went with option 3 in this PR:

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1609
