### ISSUE TITLE
Why is QueryResponse internal?

### ISSUE THREAD

**Issue by fuocor** [Azure/azure-cosmos-dotnet-v3#1389]
the title pretty much explains it.
The Count parameter is not available and the ```x-ms-item-count``` header seems to be gone

rich

**Comment by j82w** [comment]
QueryResponse is internal because it's just a bunch of internal implementation details. This seems like a bug that the headers is missing this value.

**Comment by ealsur** [comment]
Looks like when the QueryResponse gets created, it builds a set of Headers called `CosmosQueryResponseMessageHeaders` and don't pass the full header response: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/b2d55614cccc4a394ce0964de2bfc4f787d79ff3/Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs#L158

I would think that the reason is, a query response can be coming from multiple server side requests, for example, for aggregation/cross partition queries.

In this case, the `x-ms-item-count` header does not make much sense, because the response does not equal 1:1 with server response.
