### ISSUE TITLE
IClientSideRequestStatistics.IsCpuOverloaded meanning

### ISSUE THREAD

**Issue by arekpalinski** [Azure/azure-cosmos-dotnet-v3#1450]
I wonder about the meaning of an internal property called `IClientSideRequestStatistics.IsCpuOverloaded`. 

I see that its value comes from `Microsoft.Azure.Cosmos.Direct.dll`. I'm interested about conditions when the value is set to `true`. We might be interested in using it for alerting users about high CPU in our [profiling tool](https://hibernatingrhinos.com/products/cosmosdbprof) as this can affect the overall latency of a request.

**Comment by j82w** [comment]
This is used when certain transport exception. If the SDK gets a transport exception and the CPU history is available it throws a specific exception warning users that the timeout was caused by high cpu usage. Currently this value is only populated for .NETFX on windows. There is a change in the next release that should have it working in dot net core and Linux.
