### ISSUE TITLE
Unable to change from autoscale to manual throughput with the SDK

### ISSUE THREAD

**Issue by jberthiaume** [Azure/azure-cosmos-dotnet-v3#1554]
**Describe the bug**
Unable to change from autoscale throughput to manual throughput with the SDK. 

**To Reproduce**
1) Create a container with autoscale throughput set to 4000 RU/s. 
2) Use the SDK to change the container's throughput to manual 400 RU/s. `Container.ReplaceThroughputAsync(ThroughputProperties.CreateManualThroughput(400))`

**Actual behavior**
Receive a "Bad Request" response with the following error: 
> x-ms-cosmos-migrate-offer-to-manual-throughput must be supplied and offercontent must contain autopilotSettings for migration of autoscale collection to manual throughput.

**Environment summary**
SDK Version: 3.9.1

**Additional details**
This operation works in when performed directly in the Azure portal, which means that it's not a limitation of Cosmos itself.

**Comment by j82w** [comment]
This is actually by design. There shouldn't be a scenario where users are constantly converting between the two. Having developer put something in the application to do a single conversion doesn't make since. If it does the check every time the application start it consumes RUs and unnecessary overhead. Most users should be able to do the conversion easily through the portal. There will be powershell and CLI support for users that need to convert a large number of resources. Is there any reason you are trying to do the conversion the SDK?

**Comment by j82w** [comment]
@jberthiaume if there a scenario where this is needed please respond back with it, and the issue can be reopened.

**Comment by jberthiaume** [comment]
The reason I need to change scale with the SDK is that my company cannot grant the required Azure Portal rights for production-level databases due to policies around data security and separation of duties. We've evaluated all of the built-in Azure roles and unless something has changed recently, there is no role which gives access to container-level scaling without also giving some sort of Read access to data or to secret keys.

**Comment by j82w** [comment]
You can create a custom Azure role that only has read access to Database, Container, and Offer APIs. Only have update permission on Offers. It would be far more restricted than using a master key in the SDK, and there would be no way to access secret keys.
