### ISSUE TITLE
CosmosClient: UpsertItemAsync/UpsertStreamAsync/ReplaceItemAsync/ReplaceStreamAsync methods are not updating properties intermittently

### ISSUE THREAD

**Issue by pavitrag123** [Azure/azure-cosmos-dotnet-v3#1596]
To update properties for bulk items, while using CosmosClientSDK with AllowBulkExecutor Option enabled, we observed properties are not getting updated for few items. Issue is reproducible only for bulk item updates(500 items) but not while doing for 10-50 items

We tried with UpsertStreamAsync/UpsertItemAsync/ReplaceItemAsync/ReplaceStreamAsync methods
Below is code snippet where object properties are updated and converted to MemoryStream 
![image](https://user-images.githubusercontent.com/19691194/83777613-407e7500-a6a7-11ea-9e3e-9f1bf34f6ef4.png)

Above memory stream is pushed to clientSDK Upsertstream similar to https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/BulkSupport/Program.cs file

![image](https://user-images.githubusercontent.com/19691194/83777719-5f7d0700-a6a7-11ea-97cb-c50edda3b9fc.png)

Can someone please help us on where it is going wrong? The missing updated items varies for each run and In very few times, issue doesn't even occur

**Comment by j82w** [comment]
@pavitrag123 are you awaiting the task? Does it eventually get updated?

@ealsur any suggestion?

**Comment by pavitrag123** [comment]
yes all the tasks are awaited after loop like below

![image](https://user-images.githubusercontent.com/19691194/83830968-0a231300-a704-11ea-8e5a-ccf237dd3245.png)

**Comment by ealsur** [comment]
Are you getting a failure on the `else` clause? Could you be getting throttled?

**Comment by pavitrag123** [comment]
No, there were no errors logged through else clause and also no throttling 429 errors logged. 

If there are 500 tasks running async, total completed tasks are always 500 and also verified respective task's IsCompleted/IsCompletedSuccessfully/IsCanceled/IsFaulted properties, IsCompleted/IsCompletedSuccessfully status is true for all of them and IsCanceled/IsFaulted  is  false


FYI, Microsoft.Azure.Cosmos.Client version is 3.9.1.0

**Comment by pavitrag123** [comment]
Hi @ealsur , 

I've uploaded sample github solution https://github.com/pavitrag123/CosmosBulkUpdateWithSDK. 

Above solution has an API to insert 1000 items to database with 2 different status values with 500 items each. 
Another API to update those 500 items to another status value

Issue is reproducible for hosted functionappp api calls but not for localhost. Function app is under B1 service plan

During initial update run, status not updated for 100 items and after another run, 18 items were not updated

Could you please check the code and let me know where it went wrong

Thanks in advance

**Comment by ealsur** [comment]
@pavitrag123 What do you mean by it doesn't repro on localhost? If it's the same code, connecting to the same Cosmos DB account, it should repro regardless, unless the Functions runtime is having some issue?

Couple of more questions for the code:

* Why using a ConcurrentBag<Task> instead of a List<Task>?
* Is the dataToImport unique (has no repetitions on Id and PK)
* You are mixing Deletes and Creates, is this taking into account if an item receives a Create and then a Delete on the same bulk operation?
* Does this repro on Direct Mode (the default)?
* Are you by any chance calling these API endpoints concurrently? For example, could the Delete one be called while the Insert or Update are running?

**Comment by pavitrag123** [comment]
@ealsur , yeah updates worked as expected when I ran the solution locally 3-4times pointing same cosmos db account in azure, but  functionapp didn't work. I haven't found any relevant logs for this in app insights logs/failures, 

- We faced "Destination Array not long enough" issue while using List to process huge data. So changed it to ConcurrentBag 
- Yes data imported is unique, Id is always unique though partitionKey is repeated
- Same method is used to perform upserts/deletes in bulk. But each bulkImport object will have only one type of operation either import or delete
- Yes issue is repro with Direct Mode also
-  No, APIs are not called concurrently
- Yes, used real cosmos DB account and default consistency is set to SESSION

**Comment by pavitrag123** [comment]
@ealsur, providing MaxRetryAttemptsOnRateLimitedRequests value like below seems to have fixed the issue. 
![image](https://user-images.githubusercontent.com/19691194/83999517-87f35280-a980-11ea-867f-6fa8ed1fe1a9.png)

We will be monitoring it for now and provide some constant value for it.
Regarding 429 errors, sorry I was checking at app insights but not at database level.  They are getting logged at database level though functionapp shows success code. Also noticed localhost is producing very less 429 errors compared to functionapp which might be reason for successful execution during localhost

**Comment by ealsur** [comment]
Thanks for the confirmation, yes, 429s would mean those operations were retried by the SDK (it does so 9 times by default) and then failed. Increasing the Max Attempts works and explains why this doesn't happen with 10 items but it does with 500.

The reason localhost does not have an issue is probably because you are adding Network delay to the requests, so they end up being sent more slowly than when the code is running co-located in the same Azure datacenter. That extra air time reduces the 429s since the rate of requests is less.

**Comment by ealsur** [comment]
Closing as the source of the issue has been found (throttles). Please reopen in case something else is found.

**Comment by sachin-agarwal-by** [comment]
@ealsur  do we have any api where we can use the bulk update because replaceItemStreamAsync it will work for one object ..
@pavitrag123

**Comment by ealsur** [comment]
@sachin-agarwal-by Please open a new issue describing the problem you are encountering
