### ISSUE TITLE
Efficient way to look up an item by Id?

### ISSUE THREAD

**Issue by a-vishar** [Azure/azure-cosmos-dotnet-v3#1605]
**Is your feature request related to a problem? Please describe.**
I'd like to look up an item as efficiently as possible when only the Id of the item is available.

I had assumed that the `ReadItemAsync` method would support this, but it appears to require a `PartitionKey`.  To be clear, a key is defined in the collection, I just don't know it at certain times.

**Describe the solution you'd like**
An efficient way of querying a document by Id when the `PartitiondKey` is unknown

**Describe alternatives you've considered**
The best idea I have:

```
var feedIterator = _container.GetItemQueryIterator<TDataType>($"SELECT TOP 1 * FROM c WHERE c.id = '{documentId}'");
if (feedIterator.HasMoreResults)
{
	var document = await feedIterator.ReadNextAsync();
	return document.FirstOrDefault();
}
```

**Additional context**
I just feel as though there must be a better way!

**Comment by j82w** [comment]
Please take a look at the [Partition documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview). Items in Cosmos DB are identified by the Id and Partition Key value. The partition key is what determines what machine it is stored in and the id is used to identify the item in that partition. There is no efficient way to find an item without the partition key, because you have to go every [physical partition](https://docs.microsoft.com/en-us/azure/cosmos-db/partition-data) and do a query to check if it is there. This will get worse as the container is scaled up as there will be more physical partitions that have to be checked. If you have a large container or planning it scaling up I would recommend changing the partition key to something the application is always aware of.

**Comment by ealsur** [comment]
As @j82w said and linked, the identity of the document is defined by the `id` and partition key value. 
If your container has the `id` as the Partition Key Definition, then just the `id` would work, but without that value, a point read is not possible.

Which is your Partition Key Definition?

**Comment by ealsur** [comment]
Closing. Service requests require both `id` and Partition Key for point reads. If the container has `/id` as the Partition Key definition then the same value can be used on both parameters, otherwise, the value of the Partition Key property needs to be used as second parameter in order to do a point read.

**Comment by a-vishar** [comment]
With the example you gave (using `while` instead of `if`).  If there can be empty pages, wouldn't I need to return something like this: `results.FirstOrDefault(m => m != null)` ?

Alternatively, my expectation is that `feedIterator.ReadNextAsync` would return a null item, therefore I would use:

```
while (feedIterator.HasMoreResults)
{
    var document = await feedIterator.ReadNextAsync();
    if (document != null)
    {
        return document;
    } 
}
```

Apologies for the confusion here, I'd just like to make sure I'm handling things correctly.

**Comment by ealsur** [comment]
Empty pages does not mean they have a list with null values. Empty pages means it's a FeedResponse where the list of items returned is empty. So no, you don't have to compare with null and `document` won't be null (`document` is of type `FeedResponse`).

**Comment by a-vishar** [comment]
Is there a reason to add to the collection multiple times in the way you did or would this achieve the same result?

```
public async Task<TDataType> GetById(Guid documentId)
{
	var feedIterator = _container.GetItemQueryIterator<TDataType>($"SELECT TOP 1 * FROM c WHERE c.id = '{documentId}'");

	while (feedIterator.HasMoreResults)
	{
		var iterator = await feedIterator.ReadNextAsync();
		var document = iterator.FirstOrDefault();

		if (document != null)
		{
			return document;
		}
	}

	return default;
}
```

Perhaps I misunderstood the intent behind your implementation, but it seems as though it could try to add an empty collection to the list multiple times, and could continue looping after it has found one result (more empty pages)?

**Comment by ealsur** [comment]
Your code is not draining the query and dealing with empty pages.

```
public async Task<TDataType> GetById(Guid documentId)
{
	var feedIterator = _container.GetItemQueryIterator<TDataType>($"SELECT TOP 1 * FROM c WHERE c.id = '{documentId}'");
        List<TDataType> results = new List<TDataType>();
	while (feedIterator.HasMoreResults)
	{
		var iterator = await feedIterator.ReadNextAsync();
                results.AddRange(iterator);
	}

	return results.FirstOrDefault();
}
```
