### ISSUE TITLE
Need to do custom Order By

### ISSUE THREAD

**Issue by ajitsinghit2** [Azure/azure-cosmos-dotnet-v3#1608]
I have a field "Severity" in my container which can have 4 possible values i.e. "Critical", "Alarm", "Warning" and "Information". I want to sort them in same order as defined here. I cant use simple order by as it will do the alphabetic sort.
To achieve I created a "severityIndex" property. I am not populating it but in my query, based on Severity, I am assigning corresponding index to this property. But when I do order by against "SeverityIndex", it doesn't sort against it.

I tried to do with subquery like 
select * from (select Severity, Severity="Critical" ? 4 : Severity="Alarm" ? 3 : Severity="Warning" ? 2 : 1 AS SeverityIndex  from c) data order by data.SeverityIndex
but it didn't work.

Is there any way I can achieve it?

**Comment by bchong95** [comment]
We currently do not support ordering by a non indexed field and since you are generating one on the runtime it is not being indexed. Your best bet is to add the numeric sort into every document or split the query up into 4 queries:

```
SELECT * FROM c WHERE c.Severity = "Information"
SELECT * FROM c WHERE c.Severity = "Warning"
SELECT * FROM c WHERE c.Severity = "Alarm"
SELECT * FROM c WHERE c.Severity = "Critical"
```

And stitch the results together client side.

Please reopen the incident if you have further questions.

**Comment by ajitsinghit2** [comment]
Thanks Brandon. For now, we have added another numeric field sort against that.
