### ISSUE TITLE
Guidance around AllowBulkExecution

### ISSUE THREAD

**Issue by Camios** [Azure/azure-cosmos-dotnet-v3#1611]
At what point does it make sense to enable AllowBulkExecution?
Does it have any impact on reads?

At the moment we're uploading just over 100 records to one container (indexed is about 1600RUs) and another 100 key-value records to another container (non-indexed is about 1300RUs, for comparison indexed is about 6500RUs). 
The containers are written in two different threads. The items are created using [this](https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/) approach.
```
Container container = cosmosClient.GetContainer("myDb", "myCollection");

// Assuming your have your data available to be inserted or read
List<Task> concurrentTasks = new List<Task>();
foreach(Item itemToInsert in ReadYourData())
{
    concurrentTasks.Add(container.CreateItemAsync(itemToInsert, new PartitionKey(itemToInsert.MyPk)));
}

await Task.WhenAll(concurrentTasks);
```

When locally developing against the Cosmos Emulator it executes about 4-5times slower if I set AllowBulkExecution to true.
When running in debug mode I'm seeing "DocDBTrace Information: 0 : Batch is full - Max operation count 100 reached. "

When writing to real Cosmos in Azure, the difference isn't as pronounced (could be network latency due to running function locally), but AllowBulkExecution=true is still slower.

Am I correct that for this dataset, it appears it makes sense to leave AllowBulkExecution as default (false)?
In the future we will need to handle different datasets and much larger / more numerous data.  When will it make sense to enable AllowBulkExecution?

**Comment by j82w** [comment]
This [bulk article](https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/) does a good job of explaining when you should use bulk. There is also the option to use [batch](https://devblogs.microsoft.com/cosmosdb/introducing-transactionalbatch-in-the-net-sdk/).

**Comment by j82w** [comment]
> Are you doing a nightly dump of 2 million records into your Cosmos DB container? That is bulk.
> 
> Are you processing a stream of data that comes in batches of 100 thousand items you need to update? That is bulk too.

The article calls out 100 thousand items or millions of records. You are only working with 100. What is your reasoning to try using bulk for so few of items? You could also look into [transactional batch](https://devblogs.microsoft.com/cosmosdb/introducing-transactionalbatch-in-the-net-sdk/) support.

**Comment by ealsur** [comment]
There is nothing magical about Bulk. The volume of data you are sending is under your control.

Cosmos DB has a predictive RU cost, meaning that a write operation with a document of a given size will always consume that amount of RU, so if one operation costs X, and you are sending 10K operations, that will consume 10K x X if executed in the same second.

What Bulk does is, on scenarios where the provisioned RU is more or less aligned with the data you want to process, it optimizes network, and optimizes the throughput utilization to push that data faster. It will be faster than doing those operations individually. It basically let's you squeeze more your provisioned throughput on scenarios where you want to consume it all and push data as fast as possible.

But if you are underprovisioned, there is no magic around it, you just cannot provision a 400 RU/s container and expect to send 10K operations and have them complete without throttling. Operations will get throttled.

The SDK automatically retries on throttles 9 times by default, and you can customize this through the `CosmosClientOptions.MaxRetryAttemptsOnRateLimitedRequests`, you can set it to a very high number and the SDK will keep retrying, so it will take longer, but eventually succeed.

**Comment by Camios** [comment]
@ealsur missed my points.
Regarding the “volume is under my control” and if “sending <quantity> operations”: I was trying to make the point that I don’t believe we control ‘quantity’ sent per second. Not with the async/WhenAll bulk examples provided - it would just line up as many requests as possible depending on the host platform and we don’t control the host platform. Not without writing a back-off throttling client wrapper. 
So my next related point is you effectively have to set throughput of cosmos based on max operations per second of the client host platform(s) and that would likely be very overprovisione d (if active clients is variable) or you could atttempt to average it out but that would require heuristics or you have to rely on cross-host back-off throttling. 
If you want to do bulk then there is an implicit assumption: you have more data than you can fit in the provisioned throughput/s. This bulk implementation solves in a narrow case where required send-throughput is capped and known. 
I suggest it is brittle if ‘quantity/s’ is variable 
and the only throttling is reactive to server side responses (rate limit)

I was trying to suggest there are alternative ‘bulk’ scenarios (eg variable, uncontrolled or unknown quantity/s) and they might benefit from the SDK providing a client side throttling which could be configured manually (in the case of multiple clients) or automatically capped based on the container’s configured throughput (for single client work loads) by default.

**Comment by ealsur** [comment]
Even if you take Bulk out of the picture, always the compute will play a part in how much data you can push through.

Let's step back a bit and see the base scenario.

We have a benchmark tool that helps you understand how many operations per second you can do with a certain provisioned throughput: https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Tools/Benchmark

Cosmos DB, once you consume more than what you have provisioned, it will throttle your requests. This means that they either fail, or if you have something that retries (like the SDK) they can eventually succeed but will take longer.

If you had X amount of documents / operations that you wanted to get through utilizing as much of the available throughput as possible, with the SDK, you could technically issue all the operations concurrently, create a List of Tasks, where each Task will do an operation and the rate at which they get executed will depend on your compute + network + available throughput (this is all without Bulk into the picture). This will issue independent network requests, one per operation, and all these requests in parallel will drain the available throughput. Obviously if you send more operations than what can be processed by your available throughput, operations will get throttled.

What Bulk does is optimize this scenario, not any other. How does it optimize it? By reducing the network utilization, and reducing the payloads that are sent, and encoding the contents. This effectively increases the throughput your compute can dish out. That is all Bulk does.

Currently the Bulk implementation does have a [Congestion control](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1074) that reduces the rate when encounters 429s or increases the rate if the current rate is not showing signs of throttling.

Does this mean that the volume of data that you want to push in needs to be higher than the provisioned throughput? No. But the flow is optimized for a large number of operations, because the overhead of packing the operations gets offset as the volume of operations increase. If you are doing a single write, and you send it through Bulk, the packing overhead cannot be faster than simply doing that single write.

We are working on [improving](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1612) the scenarios where the volume of operations is low, but the main scenario for Bulk has always been optimizing throughput.
