### ISSUE TITLE
Question: Why does SDK hit Cosmos DB every five minutes?

### ISSUE THREAD

**Issue by krispenner** [Azure/azure-cosmos-dotnet-v3#1623]
**Question**
I see an HTTP GET request to my Cosmos DB account every five minutes exactly to the second. It originates from my Azure Web App which uses the Cosmos SDK. I can't find any documentation on any heartbeats in the SDK or what would be continually hitting the DB. I create a singleton Cosmos client for my Web App. The Web App is a custom Linux container. Connection mode is the default of Direct which I believe uses TCP so I wouldn't expect any HTTP requests to begin with.

**SDK Version**
`<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.9.1" />`

The Cosmos Monitor documentation [here](https://docs.microsoft.com/en-us/azure/cosmos-db/use-metrics) states:

> Metrics are collected every five minutes and are kept for seven days.

However, I don't think this is related, because:

A) I wouldn't expect to see these metric requests in Application Insights itself, and more importantly
B) I wouldn't expect to see these metric requests originating from my Web App as a dependency request 

**Screenshot from Application Insights**
![image](https://user-images.githubusercontent.com/8837910/84705319-0f583d00-af10-11ea-8097-86e3409f47a4.png)

So my question is: Can anyone explain or confirm what this request might be related to? It is not my code. Is there some configuration/option for the client SDK this related to. I just want to understand what these requests are about.

**Comment by ealsur** [comment]
The SDK every 5 minutes checks the Account endpoint. It is a call to the `/` of the endpoint.

Source: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L274

The goal is to detect any account changes, for example, new regions added, consistency changing, etc.

**Comment by krispenner** [comment]
Thank you for your explanation. Sounds reasonable :) I'll go ahead and close this. Might be worth documenting this so others don't also get confused, unless it is already and I just can't find it.

**Comment by fhtino** [comment]
@ealsur  is there a way to get rid of these Application Insights entries? or a way to "disconnect"/divert them from the flow of data related to application insight operationid?  
When I look into Application Insights, some runs are filled by those continuous checks. 
As far as I understand, these 5-minutes checks are assigned by ApplicationInsights to the first run (i.e. operationid) of the function because the first run of my function creates the static instance of CosmosClient. So this first-run will continue indefinitely to collect calls until the fucntions underlying instance is alive.

**Comment by ealsur** [comment]
@fhtino That seems like a bug on App Insights. One thing you could do is (it really depends on your code), do the initialization in your Startup using maybe, using the new APIs (https://devblogs.microsoft.com/cosmosdb/improve-net-sdk-initialization/) to avoid that being always tagged to the first request. 
It's weird that they are assigning that same operation because this happens in the background, but I don't know their correlation logic. You can always engage with a support ticket with them.

**Comment by fhtino** [comment]
@ealsur I followed/adapted you suggestion. In Function Startup I create the static CosmosClient and execute a call for a document. The following real functions executions are no more polluted by GET every 5 minutes. Problem solved.
Interestingly, the cosmosdb call(s) executed in function startup is not traced by Application Insights. Bug? I looked for any signs of them, using kusto query in application insights logs without success.

**Comment by ealsur** [comment]
Glad you got it working. Sadly I cannot answer anything regarding App Insights, the SDK does not have any specific integration with it. Apparently App Insights injects itself on the HTTP pipeline and logs any HTTP call from within the application. Maybe they inject themselves when you register it? If in your Startup you have the registration/initialization of the Cosmos DB SDK before App Insights registration, try inverting the order.
