### ISSUE TITLE
Error "The read session is not available for the input session token"

### ISSUE THREAD

**Issue by dpgregory** [Azure/azure-cosmos-dotnet-v3#1708]
**Describe the bug**
I have been using this SDK fine for at least the last 6 months, up until today when I created a new Database (basically to rename the one I had), but now I am getting the error "The read session is not available for the input session token". 
From my investigations, what seems to be happening is when I use the session token returned from an update on one container (call it ConainterA), on another container (ContainerB) is fails with the above message. When doing an update on ContainerB it returns a lower session token. So for example I update an item in ContainerA and it returns session "0:-1#30", and then try to use that on ContainerB it fails with the above error. If I then do and update on an item in ContainerB it returns the session as "0:-1#12". As far as I am aware the session token isn't per container? The strange thing is, when I point my code at the "old" server this all works fine and the response from ContainerA can be used against ContainerB. Both are in UK South. So not sure if this is an issue with the SDK or Cosmos itself?

**To Reproduce**
Create a new Database in UK south with 2 containers. Insert something into containerA and try to use the returned session token to query from containerB

**Expected behavior**
The session token from one container can be used on another container without causing error.

**Actual behavior**
Error is returned when using a session token from one container on another container

**Environment summary**
SDK Version: 3.11.0
OS Version: Windows

**Comment by ealsur** [comment]
Couple of questions:

* Are you using the same client?
* Which consistency is set on the account?

**Comment by dpgregory** [comment]
It's exactly the same code, just config change, so yes same client.

Sorry yes should have said it's the default session consistency on both databases.

**Comment by ealsur** [comment]
If it's the same client, you don't need to pass the SessionToken around. The SessionToken is for when you have multiple clients and you want to pass around the session scope outside.

SessionToken is scoped to a container/collection, the SDK's SessionContainer maintains the state per container https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/SessionContainer.cs#L41

**Comment by dpgregory** [comment]
Sorry, I misread what you meant by client. It's an ASP.NET Core application, and this is 2 different end points, so needs to be passed between them. 

So I need to keep track of each SessionToken per container between each request?

I have been doing a bit more investigating and setting up a brand new Cosmos DB account, and initially it behaved as I expected, the SessionToken works across all containers. I realised the one thing that was different to this new ComosDB account over the old one, was I had used [CosmicClone](https://github.com/microsoft/CosmicClone) to copy the data across from old to new. Once I used that to copy some data from old repo into the test one, that's when things started to not work any more and couldn't use the same SessionToken across all the containers. So it might be something to do with the bulk import in that. If you can just answer my question above, I will then close this issue. Thanks.

**Comment by j82w** [comment]
I think there is a misunderstanding of how and what a session token is. The session token is like SQL Server Log Sequence Number (LSN). It's essentially is just a int that increments when ever something is written to the container.  The purpose of it is if you have your application scaled out across multiple machine, and you need to be sure that two instances are reading the same information then you can share the session token. 

Example with both apps using the SDK in session token mode:
// Failure scenario
App 1: Creates item A
App 2: Reads item A, but gets a not found because it read from a replica that was behind
// Session token used to fix the above issue
App 1: Creates item A, then shares the session token with App 2
App 2: Reads item A with the session token returned from App 1 create operation. The read is now guaranteed to be successful and will not use a replica that is behind.

For your scenario where the data has been cloned the SessionTokens will not work as different operations are done on the separate containers causing the SessionToken to increment differently. As an example the original container might have had 10 separate create items, and the clone will only have 1 because of the bulk operation.

@kirankumarkolli or @ealsur do you have any suggestions on how to do this? The only thing I can think of is to simply do a read or query item on the cloned container to verify the information is there.

**Comment by dpgregory** [comment]
That is how I am using the SessionToken with multiple app servers. Front end stores SessionToken and sends it back, in case it hits a different app server. Not got replicas yet as still in dev, but in production will have multiple so needs to cover that scenario as well.

The cloned data does not have the same LSN as the original. For the same document, in the old account, it has 81834 and in the new it is 36, so don't think the cloning copies the LSN across, so had assumed it would work. Not got to the bottom of exactly what is causing the issue, but sounds you are suggesting it is the bulk copy that is causing it?

If I treat the LSN as per container, then it should work, but not sure if that is how it's meant to work, or if the LSN is meant to be across the whole Database and all the containers within it.

**Comment by j82w** [comment]
SessionToken is per a container, and represents a point in the logs. The cloned container is a completely different container, and will have completely different logs and there for completely different SessionToken values. 

Simplified Example:
Container A: Create item a: session token 1
Container A: Create item b: session token 2
Container A: Create item c: session token 3
//Clone Container A to Container B
Container B: Bulk read items from container A then bulk insert item a, b, and c: session token 1

**Comment by dpgregory** [comment]
OK, thanks for the clarification that session token is supposed to be per container. Must have just been luck that it works on my old account then! I'll have to send all the container session tokens back and forth to the front end now then.
