### ISSUE TITLE
LINQ queries with DateTime values are broken

### ISSUE THREAD

**Issue by mywyb2** [Azure/azure-cosmos-dotnet-v3#1732]
LINQ queries with DateTime values containing trailing zeros (which is usually the case when the DateTime comes e.g. from a UI DateTime picker) generally do not work, neither in Microsoft.Azure.Cosmos nor in Microsoft.Azure.DocumentDB.Core. See https://stackoverflow.com/questions/63112044/bug-in-datetime-handling-of-cosmos-db-documentclient for details.

**Comment by timsander1** [comment]
Hi @mywyb2 , this will be addressed in a service update later this year. Tentative timeline is late October

**Comment by planty** [comment]
Hi, is there any update on when this will be fixed?

**Comment by srchilu** [comment]
Our team is also blocked on this issue. Can you share by when this will be fixed?

**Comment by timsander1** [comment]
Apologies, I hadn't clicked through the Stackoverflow link and misunderstood the original issue. There's an improvement we are making for relaxing input for DateTime system functions handling trailing 0's which turns out to be unrelated to the question.

I'll investigate this and update in a couple of days with a timeline.

**Comment by timsander1** [comment]
Since Cosmos DB does not have a DateTime type (DateTimes are represented as strings), LINQ queries currently do not handle trailing zeros correctly. This is because LINQ has a DateTime type but Cosmos DB does not.

Our recommendation is to compare DateTimes as strings using CompareTo

For example:
var queryable = orderedQueryable.Where(x => 
                ((string)x["datetime"]).CompareTo(datetime.ToString("yyyy-MM-ddTHH:mm:ss.fffffffZ")) <= 0
                );

Would get translated to the following SQL query:
{{"query":"SELECT VALUE root FROM root WHERE (root[\"datetime\"] <= \"2000-01-01T00:00:00.1234560Z\")"}}

I'll update the LINQ docs to mention this.

**Comment by timsander1** [comment]
Also wanted to check, are you using V2 or V3 of the .NET SDK?

**Comment by mywyb2** [comment]
As described in the SO post, the error occurs in all versions of the SDK. (But the workarounds are different depending on v2 or v3.)

 �

**Comment by timsander1** [comment]
Yes, like the post mentions, you'll see the same behavior in both V2 and V3 SDK. The reason I asked which version you were using is because of the recommended solution in the Stackoverflow post (specify the JsonSerializerSettings as part of a CustomerSerializer). This is another possible solution but will only work for the V3 SDK.

**Comment by aaron-0** [comment]
FYI we tried fixing this with CustomerSerializer but then ran into a whole bunch of issues around linq working with camel casing.
The current model of CosmosJsonDotNetSerializer being internally sealed makes it quite hard to change the json.net settings. 
Recommend exposing things in a way that JsonSerializerSettings can be specified, that way DateTimes can be formatted retaining trailing 0's and other customizations are easy to make.

**Comment by srchilu** [comment]
@timsander1  we have one more layer on top of iqueryable which is to build **Expression<Func<T, bool>> expression** which is converted to iqueryable. 
One issue with this approach is we have to update all our models from datetime to string and deal with strings in our code.

expression.And(obj => obj.CreatedDateTime <= query.MaxCreatedDateTime);
to 
expression.And(obj => ((string)obj.CreatedDateTime).CompareTo(query.MaxCreatedDateTime) <= 0);

We cannot typecast obj.CreatedDateTime to string.

**Comment by srchilu** [comment]
@aaron-0 are you able to use custom serializer and query correctly. 
We are able to use custom serializer to format while writing but issue remains same while querying. Trailing zeroes are removed.
Can you confirm?

**Comment by mywyb2** [comment]
@srchilu I'm the author of both the question and the workaround on StackOverflow and can confirm that the custom serializer works for LINQ queries in SDK v3, i.e., LINQ queries are correctly translated into SQL with trailing zeroes. For SDK v2 you have to configure the global JSON serializer settings.

**Comment by srchilu** [comment]
Thank you @mywyb2 for your reply. We are using v3 SDK.

I copied CosmosJsonDotnetSerializer from cosmosdb repo and initialized cosmosclient with below code snippet:

                cosmosClientOptions = new CosmosClientOptions()
                {
                    ConnectionMode = ConnectionMode.Gateway,
                    Serializer = new CosmosJsonDotNetSerializer(
                        new JsonSerializerSettings
                        {
                            DateFormatHandling = DateFormatHandling.IsoDateFormat,
                            DateTimeZoneHandling = DateTimeZoneHandling.Utc,
                            DateFormatString = "yyyy-MM-ddTHH:mm:ss.fffffffZ",
                        }),
                };

As mentioned in previous post, we are building linq expression and then using where to get iqueryable like below
Expression<Func<T, bool>> expression (passed as param);
var queryablenew = queryable.Where(expression);

When I check in queryable1, trailing zeroes are being removed.

Can you point out if I missed any other setting?

**Comment by mywyb2** [comment]
@srchilu I think it's not sufficient to set the standard `JsonSerializerSettings` as you did above. You need to create a custom JsonConverter as described in my SO answer.

**Comment by aaron-0** [comment]
@srchilu I have not had a chance to be able to get back to this, however, I spoke to the developer in my team who did the work.
We were not able to Customer Serializer as when you set Serializer you can no longer set SerializerOptions. We use SerializerOptions to set CosmosPropertyNamingPolicy.CamelCase. So if we put in a customer serializer all our linq queries break due to camel case instead of pascal case. In another project we had no choice but to set a Custom serializer, we ended up having to put JsonProperty on every property of every model so the linq parser picks up camel case. This has been a fair bug factory for us.

@timsander1 given that cosmos db does all DateTime comparisons based on a string, wouldn't the simplest solution to this problem be to change the string formatting from that ends in FFFFFFFK (dropping 0's) to either 'o' or a format using 'f' so 0's are always kept.

It would also be great if you made it easier to pass in JsonSerializerSettings to the CosmosJsonDotNetSerializer class in your library. I understand from the comments you have hidden this class so you can move to System.Text.Json at some point, but the situation is causing issues as I have detailed above.

**Comment by davidobrien1985** [comment]
@timsander1 any update on this one? You mentioned that this would be addressed in an update, potentially October, but we're still seeing this issue. Thanks.

**Comment by aaron-0** [comment]
@timsander1 any updates

**Comment by DyByronWu** [comment]
any updates? still have this problem in v3

**Comment by Yleisnero** [comment]
I have a similar problem. When comparing two DateTimeOffset objects in a LINQ query as a part of a a cosmos queryable the DateTimeOffset objects are compared without using the time zones. Which means that Cosmos does not note the offset.
```
using var billQueryFeedIterator = _container.GetItemLinqQueryable<T>()
                .Where(x => x.LatestChangeUtc >= changesSince)
                .ToFeedIterator();
```
When using the upper code and changesSince is not a UTC time the query is wrong.

Workaround:
```
using var billQueryFeedIterator = _container.GetItemLinqQueryable<T>()
                .Where(x => x.LatestChangeUtc >= changesSince.ToUniversalTime())
                .ToFeedIterator();
```

Seems like there are still problems in Microsoft.Azure.Cosmos v3.29.0.

**Comment by Ronnehag** [comment]
> I have a similar problem. When comparing two DateTimeOffset objects in a LINQ query as a part of a a cosmos queryable the DateTimeOffset objects are compared without using the time zones. Which means that Cosmos does not note the offset.
> 
> ```
> using var billQueryFeedIterator = _container.GetItemLinqQueryable<T>()
>                 .Where(x => x.LatestChangeUtc >= changesSince)
>                 .ToFeedIterator();
> ```
> 
> When using the upper code and changesSince is not a UTC time the query is wrong.
> 
> Workaround:
> 
> ```
> using var billQueryFeedIterator = _container.GetItemLinqQueryable<T>()
>                 .Where(x => x.LatestChangeUtc >= changesSince.ToUniversalTime())
>                 .ToFeedIterator();
> ```
> 
> Seems like there are still problems in Microsoft.Azure.Cosmos v3.29.0.

Tried this and I still can't get it to work. We are using a nullable DateTime since this field is only set after changing a document after initial creation. It's working if I'm executing it as raw SQL.

I worked from the example provided by [MS Docs](https://learn.microsoft.com/sv-se/azure/cosmos-db/nosql/query/working-with-dates#querying-datetimes-in-linq).

`var sevenDaysAgo = DateTime.UtcNow.AddDays(-7)`;

This results in 0:
```
var data = await Query()
.Where(x => x.Changed <= sevenDaysAgo)
.ExecuteAsync();
```

This results in 1766 hits:
```
var data = await QueryRawAsync($"SELECT * FROM c WHERE c.Changed <= '{sevenDaysAgo}'");
```

Behind the scenes it's using the `GetItemQueryIterator` and `GetItemLinqQueryable` together with the FeedIterator.

**Comment by mywyb2** [comment]
Please reopen as the bug still exists as of January 2025.
