### ISSUE TITLE
Provide ability to Scale Out CosmosDB CFP Lease Container

### ISSUE THREAD

**Issue by johngallardo** [Azure/azure-cosmos-dotnet-v3#1822]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
We are leveraging CosmosDB CFP to manage CFP instances over a high volume of containers (~1K). We are finding that the pressure put on the CFP Lease Container is quite high. This is further exacerbated by the fact that it seems the CFP doesn't take advantage of partitioning (/id is used as the partition key) and there are frequent cross-partition queries coming from the CFP to gather all of the leases for a given container.

These cross-partition queries make it challenging to scale the CFP lease container.

**To Reproduce**
Create CFP over several hundred containers.

**Expected behavior**
CFP to make more efficient usage of allocated CosmosDB RUs (e.g., use the container ID as the partition key, so query for all leases for that container are constrained to a single partition).

**Actual behavior**
Excessive RU consumption due to cross-partition queries.

**Environment summary**
SDK Version: 3.9.0
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by j82w** [comment]
How large is your CFP lease container?

**Comment by ealsur** [comment]
Are you customizing the intervals? Using `WithLeaseConfiguration`?

The only query that happens on the lease container is a cross-partition query when the CFP checks if new leases are available to be taken, this needs to be a cross partition query, because we need to scan all leases in the store (for the same processorName) to know if any new lease is ready to be taken. But this happens by default, every 13 seconds, so the RU impact in the lease store shouldn't be high, unless you are reducing this time? How many instances do you have running?

**Comment by johngallardo** [comment]
We have configured AcquireInterval -> 7 seconds, and RenewInterval -> 5 seconds, ExpirationInterval -> 10 seconds. Our goal is to try to process changes within five seconds of them hitting the monitored container. 

At peak, we have 1K containers that would be monitored. We actually partition these across a set of hosts, so that not every host monitors each container. We target 3 hosts per container. 

Recently, in one of our scale test environments we scaled the CFP container to 100K RUs (Autoscale), which resulted in creating ~ 10 partitions. Originally, we had this @ 10K max RUs, but were encountering throttling. 

I believe another contributing factor is that we create 1 CFP Estimator per processor, so we actually have 3 estimators running as well, with those configured to run every 5 seconds. I believe CFP Estimator also does a poll of all of the leases similar to when the processor checks for available leases. We are looking to reduce this estimator interval which should also help with this.

**Comment by ealsur** [comment]
> Our goal is to try to process changes within five seconds of them hitting the monitored container.

Those settings are mainly affecting scenarios where your instances might change (dynamically adding/removing instances, instances crashing), they don't directly affect the metric you are explaining. You are just adding more pressure on the lease store.

The time it takes for you to pickup new changes is directly affected by the time you take to process current changes (within the same lease scope), so your focus should be to have the fastest delegate possible.

The other important factor is the WithPollInterval. As explained in https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-processor#processing-life-cycle, if the partition for a lease has no changes, the CFP sleeps for that interval, if any new changes land during that sleep, they will be delayed. If your changes are sporadic, you might want to reduce this (default is 5 seconds) so something like 3? This does not add RU consumption on the lease store. 

On the Estimator, yes, you only need one. For monitoring purposes it's best that it's an independent instance, unrelated to the Processors (to decouple the processor lifetime with the estimator lifetime).

**Comment by johngallardo** [comment]
WRT instances changing -- instances changing is somewhat frequent in our system, and we do this to actually try to shuffle hosts across containers, otherwise what we observe is that the first host to boot (e.g. after a deployment of a new version) immediately grabs the lease on all of the containers, so part of our host distribution logic takes this into consideration. The change to move to 7 seconds was because we observed that when a host gracefully released the partition, it would take a while for another host to acquire the lease on that partition, leading to cases where we would lose our SLA during these shuffling periods.

**Comment by ealsur** [comment]
That makes sense, though the Acquire Interval is kind of the max, because the task is already running in other processors, so when a host goes down and releases the leases, that running task might just take 1 second up to the Acquire Interval (in the scenario where the Task just slept when the lease was released).

In any case, we cannot remove the queries, because that's the discovery method.

It is common for the first instance to boot up and take all leases and the others to start the distribution mechanism, so it just takes some time for the load balancing to complete, but in all this time, the leases are being processed, not left idle. The only scenario where the lease might become idle for some time (until some instance starts the lease Acquire) is if a host crashes, which would leave the lease taken by a not running host and any other host needs to wait until the Timeout. 
In that case, the delay is between LeaseTimeout and LeaseTimeout + AcquireInterval in the worst case. But if your hosts are not crashing (they shut down gracefully) then the only delay is a maximum AcquireInterval (but could be less).

I would start with removing the extra estimators and leaving one.

**Comment by ealsur** [comment]
Closing. Please share if removing the extra estimators solved the issue.
