### ISSUE TITLE
Container.GetChangeFeedProcessorBuilder().WithStartTime() not working anymore with 3.15

### ISSUE THREAD

**Issue by RomanKreisel** [Azure/azure-cosmos-dotnet-v3#2031]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).
The Problem only occurrs with the latest version

**Describe the bug**
The changefeed processor always starts at the beginning, even when given a specific time

**To Reproduce**
* Use Library in Version 3.15.0
example code:
```
            var changeFeedProcessor = sourceContainer
                .GetChangeFeedProcessorBuilder(processorName, this.changesHandler)
                .WithStartTime(this.startTime)
```

**Expected behavior**
The first dataset shouldn't be months before the given "startTime"

**Actual behavior**
The first dataset IS months before the given "startTime".

BUT: Downgrading the library (without changing any single line of code) solves the problem.

Of course, after every attempt, you have to delete your lease-collection, to ensure the startTime is considered at all!

**Environment summary**
SDK Version: 3.15.0
OS Version: Win 10

**Comment by j82w** [comment]
@bchong95 can you please take a look?

**Comment by ealsur** [comment]
The bug is that `ChangeFeedStartFromRequestOptionPopulator` is now using a different format for the date.

On 3.13.0 it was using `PopulateStartFromRequestOptionVisitor` that was using:

```
this.requestMessage.Headers.Add(
    HttpConstants.HttpHeaders.IfModifiedSince,
    startFromTime.StartTime.ToString("r", CultureInfo.InvariantCulture));
```

Which yields, for example `Wed, 02 Dec 2020 21:27:36 GMT`

On 3.15.0 it is using

```
this.requestMessage.Headers.Add(
    HttpConstants.HttpHeaders.IfModifiedSince,
    startFromTime.StartTime.ToString("o", CultureInfo.InvariantCulture));
```

Which yields, for example `2020-12-02T21:29:29.6812357Z`

The backend seems to be discarding the header due to the bad format. seems like this was introduced on https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1725, since the refactoring deleted the old file and replaced it with a new file, catching the change during review was a bit harder, I honestly didn't see it when reviewing it.

Sadly we did not have any emulator tests to catch the regression on the CFP. 

The reason `ChangeFeedIteratorCoreTests.ChangeFeedIteratorCore_StartTime` does not face this problem is because it is using an iterator it is no longer using the Visitor, but `NetworkAttachedDocumentContainer.ChangeFeedStateRequestMessagePopulator`

**Comment by j82w** [comment]
@RomanKreisel please try the [3.15.1](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/changelog.md#-3151---2020-12-16) which contains the fix.

**Comment by RomanKreisel** [comment]
@j82w :Thank you for the update! I added a story to our product backlog, but it'll take at least another 2-4 weeks until it's processed. 
Since you were able to reproduce the issue, I'm pretty sure it'll work for us, if it works for you now :)

**Comment by RomanKreisel** [comment]
ok, finally the promised update:
Had the chance to update the library in our product and tested the replay from a specific date - works fine now! :)

Thanks for fixing this so quickly!
