### ISSUE TITLE
Codeless Application Insights is broken after adding Microsoft.Azure.Cosmos Nuget package to my solution

### ISSUE THREAD

**Issue by lwlwalker** [Azure/azure-cosmos-dotnet-v3#2118]
**Describe the bug**
We have a WebAPI in our team deployed in Azure Web App. We had Application Insights configured (using Azure UI, so no code) and working fine.

As an improvement to the API we moved our data from SQL Server to CosmosDB. So we need to add this package to our solution: Microsoft.Azure.Cosmos

This package adds Azure.Core.1.8.0 package too, that depends on System.Diagnostics.DiagnosticSource package.

The problem is that this package is incompatible with AppInsights Codeless integration. So we don't get any data in AppInsights now.

So, my question is: Is this dependency needed? Is there any plan to fix this? (if not, please, think about adding this in the priority list, as this is affecting all of us in Azure 8-D)

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos 3.15.1 (last one by now)
OS Version: Azure Web App

**Comment by lwlwalker** [comment]
This issue is documented here by MS: https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps?tabs=net#troubleshooting
From the page: "Confirm that there are no entries for AppAlreadyInstrumented, AppContainsDiagnosticSourceAssembly, and AppContainsAspNetTelemetryCorrelationAssembly."

In this case AppContainsDiagnosticSourceAssembly is happening.

**Comment by j82w** [comment]
@lwlwalker can you open an issue against the [Azure .NET SDK team](https://github.com/Azure/azure-sdk-for-net) who owns this dependency? 

This dependency is needed because we are working on adding Azure Active directory support this package provides the necessary interfaces. This dependency will also be required for future SDK version to follow the [Azure .NET SDK teams guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html).

**Comment by lwlwalker** [comment]
@j82w
Done! https://github.com/Azure/azure-sdk-for-net/issues/17936 
Thank you very much for the suggestion!

Luis
