### ISSUE TITLE
Migrate continuation token from CosmosDBTrigger format

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-cosmos-dotnet-v3#2155]
**Is your feature request related to a problem? Please describe.**

Difficult to migrate applications that used `CosmosDBTrigger` to Cosmos DB v3 SDK's Change Feed pull model due to the different format of the continuation token.

**Describe the solution you'd like**

Feature: automatically migrate legacy-style continuation token.

**Comment by ealsur** [comment]
That is not possible, these are 2 separate libraries with 2 separate models.

CosmosDBTrigger is an extension of Azure Functions that uses the Change Feed Processor library (not SDK) which stores state through a dedicated lease collection and lease documents. That cannot be mapped to the V2 SDK Change Feed pull model.

You can migrate to the Change Feed Processor in the V3 SDK by pointing it to the same lease collection the CosmosDBTrigger was using though and it will be able to interpret the data, because they are 2 versions of the Change Feed Processor.

**Comment by shibayan** [comment]
Thanks for the reply.

After examining the values in the Lease container, the stored LSNs themselves seemed to be compatible, so I thought it would be possible to convert them to the format (JSON) required by the Pull Model.

I would like to write a conversion code to solve this problem.

**Comment by ealsur** [comment]
While LSNs might be there, these are opaque continuation, not any sort of strict contract, and it can change at any point, making any conversion code you might generate fallible if any of the continuation formats change (leases in Trigger or the Change Feed pull model).

**Comment by shibayan** [comment]
Thanks for the detailed information. I hadn't completely thought about the relationship with physical partitions.

I don't think it is possible to migrate with physical partitions in mind, as you say, so I would like to change the migration procedure. (Specifically, stop writing to Cosmos, and switch to the pull model after the Change Feed is empty.

Thank you again.
