### ISSUE TITLE
system.text.json + azure functios + cosmos db

### ISSUE THREAD

**Issue by drma-dev** [Azure/azure-cosmos-dotnet-v3#2169]
I'm not sure if it's really an issue or normal behavior. But I have the following situations:

```
public DateTimeOffset Date1 { get; set; } = DateTimeOffset.Now;
public DateTimeOffset Date2 { get; set; } = DateTimeOffset.UtcNow;
public DateTime Date3 { get; set; } = DateTime.Now;
public DateTime Date4 { get; set; } = DateTime.UtcNow;
```
And it is saving as follows in the cosmos:
```
"date1": "2021-02-01T12:28:55.845-03:00",
"date2": "2021-02-01T15:28:55.962+00:00",
"date3": "2021-02-01T12:28:55.963-03:00",
"date4": "2021-02-01T15:28:55.963Z",
```
I'm trying to use the date functions of the cosmos (DateTimeDiff), but it only accepts the last format.

Shouldn't the cosmos save exclusively in the last format, which is what it accepts?

**Comment by drma-dev** [comment]
I'm using the following settings

```
<PropertyGroup>
  <TargetFramework>netcoreapp3.1</TargetFramework>
  <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  <EnableNETAnalyzers>true</EnableNETAnalyzers>
</PropertyGroup>
```
```
<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.16.0" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
```

**Comment by j82w** [comment]
This should be a Cosmos DB service feature request. The SDK is just serializing the string. The query function should understand the different formats.

@timsander1 is there a reason query only supports the last format?

**Comment by ealsur** [comment]
> Shouldn't the cosmos save exclusively in the last format, which is what it accepts?

What do you mean by accept? Are you getting errors with the other formats?

This is part of Newtonsoft.Json serialization of datetimes: https://www.newtonsoft.com/json/help/html/DatesInJSON.htm

You could configure the default settings to use a particular format, decorate the class to use a custom converter. From the SDK perspective, this is a string field and it is sent on the wire to the backend. There is no validation that should happen on the SDK. If the backend can store the data, then it's valid.

Is the problem that you are afterwards executing queries? If so, there is a doc talking about it: https://docs.microsoft.com/en-us/azure/cosmos-db/working-with-dates#storing-datetimes

But this is not a requirement, you could be storing dates in any format because they might be later on consumed by a reader that does not execute queries or something like that.

**Comment by drma-dev** [comment]
I chose not to do any customization and make it as simple as possible.
```
public class newclass
{
    public DateTimeOffset Date1 { get; set; } = DateTimeOffset.Now;
    public DateTimeOffset Date2 { get; set; } = DateTimeOffset.UtcNow;
    public DateTime Date3 { get; set; } = DateTime.Now;
    public DateTime Date4 { get; set; } = DateTime.UtcNow;
}
```
```
public CosmosRepository(IConfiguration config)
{
    var connString = config.GetValue<string>("RepositoryOptions:CosmosConnectionString");
    var databaseId = config.GetValue<string>("RepositoryOptions:DatabaseId");
    var containerId = config.GetValue<string>("RepositoryOptions:ContainerId");

    var _client = new CosmosClient(connString, new CosmosClientOptions()
    {
        SerializerOptions = new CosmosSerializationOptions()
        {
            PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
        }
    });

    Container = _client.GetContainer(databaseId, containerId);
}
```
```
public async Task<T> Add<T>(T item, CancellationToken cancellationToken) where T : CosmosBase
{
    var response = await Container.CreateItemAsync(item, new PartitionKey(item.Key), null, cancellationToken);

    return response.Resource;
}
```

**Comment by timsander1** [comment]
To use DateTimeDiff (or any of the other date and time system functions), the date must be in a certain format. For DateTimeDiff, we specify it as: UTC date and time ISO 8601 string value in the format YYYY-MM-DDThh:mm:ss.fffffffZ. 

Dates and times can also be represented in [ticks or a timestamp value](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-date-time-functions#functions-to-obtain-the-date-and-time)

Since JSON has no date data type, Cosmos DB uses string values to represent dates. As long as it's a valid string, Cosmos DB will store it. The individual system functions have checks to make sure the date and time format is valid.

**Comment by drma-dev** [comment]
@ealsur 
Cosmos doesn't even perform the function if it's not in the correct format
![image](https://user-images.githubusercontent.com/12803050/106512584-90207500-64b0-11eb-93a5-2d21b43977f5.png)

**Comment by drma-dev** [comment]
```
builder.Services.AddMvcCore (). AddJsonOptions (options =>
 {
     options.SerializerSettings.DateFormatHandling = Newtonsoft.Json.DateFormatHandling.IsoDateFormat;
     options.SerializerSettings.DateParseHandling = Newtonsoft.Json.DateParseHandling.DateTimeOffset;
     options.SerializerSettings.DateTimeZoneHandling = Newtonsoft.Json.DateTimeZoneHandling.RoundtripKind;
 });
```

Is there any way to resolve this similar to the above code? (this specific code does not work on core 3)

**Comment by ealsur** [comment]
@drma-dev I understand that DateTimeDiff might not work, and that is because it has certain requirements like Tim mentioned. For DateTimeDiff to work, the date should be in that particular format.

But that is in the case where you are using DateTimeDiff. It wouldn't make sense for the Cosmos DB service to reject other formats, after all, it's just a string and it cannot know how you will consume it later. If, say, I store the date in a custom format because I then read the JSON from another system and apply a custom conversion, why should the service reject it?
In any case, rejecting the payload or not is not part of the SDK scope, and should be a service request.

To your question about the settings. The Cosmos DB SDK uses Newtonsoft.Json as default serialization engine. You can use System.Text.Json in your application, for other things, but the fact that you are configuring System.Text.Json in the web app doesn't mean the Cosmos DB SDK will use it, it just means that, in your case, you might end up using it for client serialization from your web client to the Mvc Actions and back. Cosmos DB SDK uses Newtonsoft.Json by default. You can either customize Newtonsoft.Json to apply a particular date parsing OR you could replace Newtonsoft.Json completely with System.Text.Json by implementing your own custom [CosmosClientOptions.Serializer](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.serializer?view=azure-dotnet) that uses System.Text.Json instead, with whatever configuration you want.  One example of a System.Text.Json implementation can be found here: https://github.com/ealsur/ondotnet-cosmosdb/tree/master/src/episode1/customserializer

**Comment by drma-dev** [comment]
Thank you. Anyway, I'm using the example that works:
`public DateTime Date4 {get; set; } = DateTime.UtcNow`
