### ISSUE TITLE
Request is blocked. Please check your authorization token and Cosmos DB account firewall settings

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-cosmos-dotnet-v3#2298]
**Describe the bug**
I have a Cosmos DB account with configured IP firewall.
I added my current IP to the allowed list. 
Got error "Request is blocked." on adding data to a container.

**To Reproduce**
 - Configure IP firewall
 - Add current IP
 - Use Cosmos SDK to `CreateItem`

**Expected behavior**
The response should be successful.

**Actual behavior**
This code can create a database, can create a new container but cannot add items to the container due to 403
![image](https://user-images.githubusercontent.com/9221694/110684836-4aa94300-81e6-11eb-8979-ce4f72d38526.png)
> Provide a description of the actual behavior observed. 
> System.Exception: 'Response status code does not indicate success: Forbidden (403); Substatus: 0; ActivityId: 5f7338ca-ed44-45c9-8e34-5871a3546ace; Reason: (Message: {"Errors":["Request is blocked. Please check your authorization token and Cosmos DB account firewall settings."]}
> ActivityId: 5f7338ca-ed44-45c9-8e34-5871a3546ace, Request URI: /apps/0156f92e-e3ce-40cc-b1ee-be8393bd1b32/services/29e75939-155e-4b51-ba5c-e2efa9dd8d7d/partitions/e9bdb85e-d6a5-44fc-8626-e505b9255756/replicas/132598680007213774p/, RequestStats: Please see CosmosDiagnostics, SDK: Windows/10.0.19042 cosmos-netstandard-sdk/3.15.2);'
> 

**Environment summary**
SDK Version: 3.15.2
OS Version: Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment]
This is not related to the SDK, the SDK is simply surfacing the failure happening on the service.

Please see https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-forbidden#solution

**Comment by Marusyk** [comment]
@ealsur but it works well using the Portal. 403 only from SDK

**Comment by Marusyk** [comment]
@ealsur any comments? I follow all steps from the docs, added my IP. it works well using the Portal. 403 only from SDK

**Comment by bartelink** [comment]
@Marusyk ealsur is a very helpful engineer based in Seattle who has a day job. He works on the .NET SDK team and as such is well placed to explain and fix _SDK issues_. The SDK produces HTTP requests etc, as do all the other SDKs. He has no control over the permissioning issues.

Are you sure the client ip you're running from when you run the code "from SDK" is correct and/or whitelisted?

This really is extremely unlikely to be an SDK issue and running these sorts of questions through this repo is really counterproductive compared to using a site like stackoverflow which is more tuned for quick permanent answers re troubleshooting etc. You'll want to include the full response message. By all means come back and paste a link here - helpful people will traverse it and answer if they have time, but this issue is best closed as there is no reason to believe there is an issue with the actual SDK at this point.

**Comment by Marusyk** [comment]
@bartelink
I don't know who is ealsur, but he closed my issue and I need some explaining

> Are you sure the client ip you're running from when you run the code "from SDK" is correct and/or whitelisted?

of course, as you can see below, it works from Azure Portal and it created a new container and event a new database. 
The problem only with adding data into the container.

**Comment by bartelink** [comment]
This project is open source. It's a SDK. I watch the repo.

While I "just want to share my thoughts", my point was and is:
a) the SDK is just code
b) the issue was closed as the code in the SDK can't influence the service denying the request - it's just the messenger
c) you're going to resolve the answer quicker by approaching this as a general troubleshooting problem with the service, rather than roundtripping to Seattle to the messenger who is stating this basic fact.

The permissioning for DML (creating docs) vs DDL (making containers etc) operations can very easily be different depending on your security configuration.

**Comment by j82w** [comment]
If you are still having issues please [contact support](https://aka.ms/azure-support). 

One common issue that I'm aware of is if you double click the key in the portal it doesn't select the entire key and usually causes a few missing characters at the end of the key. Which then results in auth failures.

**Comment by ealsur** [comment]
@Marusyk As explained, this is not an SDK issue. One potential aspect based on experience, is that the IP you believe the request is originating from (and thus you used to add to your firewall configuration) might not be the actual IP (in cases where you use proxies for example). The Azure Portal has independent configurations to allow requests to go through:

![image](https://user-images.githubusercontent.com/1633401/110822323-cd151f80-8245-11eb-84cb-a8d17d3ab827.png)

But there is nothing that can be changed from the SDK to fix this situation, that is the reason the issue is closed, it just does not apply to the SDK.

You can, as Jake mentioned, contact support, they might check the account telemetry and potentially see which is the IP the requests are actually departing from. If you are running the code in Azure, there is the configuration to: `Accept connections from within public Azure datacenters`

**Comment by Marusyk** [comment]
My Cosmos Configuration is:
![image](https://user-images.githubusercontent.com/9221694/110824909-2740cf80-829c-11eb-8bad-0e7cbafd230b.png)
![image](https://user-images.githubusercontent.com/9221694/110824925-2b6ced00-829c-11eb-9761-d58a3fbc2676.png)

**Comment by ealsur** [comment]
The blocking of the request is not generated by the SDK, the SDK is just materializing the service response, it's the service the one blocking the request, so we cannot know the reason from the SDK perspective.

There could be a service side that is only affecting point operations (CreateItem call) and not metadata operations (CreateDatabase), but we cannot answer that here, this is not a Cosmos DB general support forum, we can only act on SDK bugs or issues.

Technically speaking, the CreateDatabase call is an HTTP call that goes to the Gateway, while the CreateItem is a TCP call that goes to the backend replica address (V3 SDK has Direct mode as default). If the Gateway calls are working and the TCP calls are failing, it could indicate an issue on the service and a support ticket is the best way. 

If you disable Firewall and everything works, and you enable Firewall and it fails, then logically, the issue is with Firewall.

In your screenshot, I see you also have VPN enabled, another potential aspect could be the VPN, but again, not an SDK issue.

**Comment by Marusyk** [comment]
Thank you very much for this great explanation. It was exactly what I need. Thanks again.

**Comment by corbin-insinuation** [comment]
@bartelink +1
