### ISSUE TITLE
Spatial.Converters throws null reference exception when data serialized with System.Text.Json.JsonSerializer class

### ISSUE THREAD

**Issue by PunzunLtd** [Azure/azure-cosmos-dotnet-v3#2304]
**Description**
When attempting to load data with spatial data from CosmosDB, the `Microsoft.Azure.Cosmos.Spatial.Converters.GeometryJsonConverter` throws a `NullReferenceException` in `ReadJson` when the spatial data was stored using `System.Text.Json.JsonSerializer.SerializeAsync(Stream, object)`. This is because the Microsoft serializer writes spatial data in a different format than the Newtonsoft deserializer used in the `GeometryJsonConverter` class.

This problem arose when attempting to follow the official sample code for bulk inserts provided at https://github.com/Azure-Samples/cosmos-dotnet-bulk-import-throughput-optimizer/blob/main/src/Program.cs

**To Reproduce**
1. Start with the official sample code for bulk CosmosDB inserts linked above
2. In your sample, add a field of type `Microsoft.Azure.Cosmos.Spatial.Point` called `location`
3. Run your sample; your CosmosDB collection should have an object with a `location` value
4. Attempt to read your data back using code similar to this:

```
var queryable = Container
	.GetItemLinqQueryable<MyType>(true)
	.Where(p => p.id = "my id");

var iterator = queryable.ToFeedIterator();

var models = new List<MyType>();
while (iterator.HasMoreResults)
{
	var response = iterator.ReadNextAsync()?.Result;
	if (response is null) break;

	models.AddRange(response);
}
```

**Expected behavior**
The query should execute and return your data

**Actual behavior**
The method `iterator.ReadNextAsync()` throws an `AggregateException` containing a `NullReferenceException` terminating `   at Microsoft.Azure.Cosmos.Spatial.Converters.GeometryJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)`

**Environment summary**
SDK Version: .NET 5.0.3, Microsoft.Azure.Cosmos package 3.16.0
OS Version: Windows 10

**Additional context**
The cause appears to be a mismatch between the way Newtonsoft and Microsoft serialize `Point` data. The example code for bulk-inserts linked above uses `System.Text.Json.JsonSerializer` to serialize the data for insertion into CosmosDB. But the `Microsoft.Azure.Cosmos.FeedIteratorCore<T>` class uses Newtonsoft tools to deserialize.

Newtonsoft's serialization looks like this:
```
    "location": {
        "type": "Point",
        "coordinates": [
            -90.740237,
            39.950254
        ]
    },
```
while Microsoft's looks like this:
```
"location": {
            "Position": {
                "Coordinates": [
                    -87.9066,
                    41.9795
                ],
                "Longitude": -87.9066,
                "Latitude": 41.9795,
                "Altitude": null
            },
            "Crs": {
                "Type": 0
            },
            "Type": 0,
            "BoundingBox": null,
            "AdditionalProperties": {}
        }
```
Examining the source code at https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Spatial/Converters/GeometryJsonConverter.cs has this at line s 63-66:
```
JToken typeToken = token["type"];
if (typeToken.Type != JTokenType.String)
{
    throw new JsonSerializationException(RMResources.SpatialInvalidGeometryType);
}
```
My guess is that line 64 throws the `NullReferenceException` because `token["type"]` will be null in the Microsoft-serialized example.

I tried to fix this by replacing `await System.Text.Json.JsonSerializer.SerializeAsync(stream, model)` in the sample code with this bulkier Newtonsoft code:
```
var itemsToInsert = new Dictionary<string, Stream>(models.Count);
var jsonSerializer = new JsonSerializer() { NullValueHandling = NullValueHandling.Ignore };
foreach (var model in models)
{
	var stream = new MemoryStream();
	var streamWriter = new StreamWriter(stream);
	var jsonWriter = new JsonTextWriter(streamWriter);
	jsonSerializer.Serialize(jsonWriter, model);
	await streamWriter.FlushAsync();

	itemsToInsert.Add(model.id, stream);
}
```
This worked, but I am seriously worried about all the open streams after it finishes. It looks like a potential memory leak to me.

(Note also that the sample uses the model's `PartitionKey` as the key in the `itemsToInsert` dictionary, which means the sample breaks when you attempt to add two items that are in the same partition. My fix to that problem was to use the ID as the dictionary key and get the item's partition key

**Comment by ealsur** [comment]
Is your Model using any of the Spatial types?

**Comment by PunzunLtd** [comment]
1. Yes, the model has a Point member.
2. Yes, _that is the problem_. The sample code for bulk inserts uses `System.Text.Json` but the SDK still uses `Newtonsoft.Json`. You're right that one workaround would be to create a custom serializer or deserializer. Other options might be (in no particular order): refactoring the SDK to use `System.Text.Json` or fixing the line of code I identified in the SDK that references an array element by case-sensitive string literal. I chose the easiest fix, which is to use Newtonsoft for the bulk insert side since I can't really avoid using it on the read side.

It's possible this is less a bug in the SDK and more a bug in the official sample code, but that's above my pay grade.

**Comment by ealsur** [comment]
@PunzunLtd Changing the SDK to use `System.Text.Json` is something that is slated for the next SDK version as it would be considered a breaking change (the V4 preview uses it).

The V3 SDK has no compatibility with `System.Text.Json` and none is planned. It offers a serialization model where you can customize the serializer if you want to replace it entirely.

Spatial types, provided by the SDK, are Newtonsoft.Json compatible, but really this is all Json. If your Bulk process is using Newtonsoft.Json, it is just writing Json. If your read/query process wants to use System.Text.Json, you can do so, you just need to provide your own System.Text.Json types for Spatial representations that deserialize the Json in a way that is compabitle with System.Text.Json instead.

**Comment by PunzunLtd** [comment]
The change will be important, because any spatial data serialized with one will break when deserialized with the other, it looks like. I hope that's on the roadmap.

Again, this isn't _my_ code using `System.Text.Json` to serialize; it's the _official sample code_ for this SDK at https://github.com/Azure-Samples/cosmos-dotnet-bulk-import-throughput-optimizer/blob/main/src/Program.cs. See line 67, specifically.

**Comment by ealsur** [comment]
I understand, but that is just an example that shows one scenario, you are not forced to follow it. The idea is to guide in a generic scenario to help understanding the concepts, in this case, that Bulk mode leverages concurrent tasks.
Just like the example contains a way to setup the Indexing Policy, but might not be applicable to all cases, or you are not using the same `Item` type but rather a Model of your own. The example is showing how you could achieve the best possible outcome performance-wise by potentially relying on System.Text.Json for faster serialization, but it's not required.

For example:

```
foreach (Item item in Program.GetItemsToInsert())
                {
                    MemoryStream stream = new MemoryStream();
                    await JsonSerializer.SerializeAsync(stream, item);
                    itemsToInsert.Add(new PartitionKey(item.pk), stream);
                }
```

That is showing how you could leverage System.Text.Json, or if your data already comes in Stream format (which would be even better), but you could simply do:

```
List<Task> tasks = new List<Task>(ItemsToInsert);
foreach (Item item in Program.GetItemsToInsert())
{
	tasks.Add(container.CreateItemAsync(item, new PartitionKey(item.pk))
		.ContinueWith(itemResponse =>
		{
			if (!itemResponse.IsCompletedSuccessfully)
			{
				AggregateException innerExceptions = itemResponse.Exception.Flatten();
				if (innerExceptions.InnerExceptions.FirstOrDefault(innerEx => innerEx is CosmosException) is CosmosException cosmosException)
				{
					Console.WriteLine($"Received {cosmosException.StatusCode} ({cosmosException.ErrorMessage}).");
				}
			}
		}));
}

// Wait until all are done
await Task.WhenAll(tasks);
```

If those examples are confusing, I'll work with the authors to improve them.

**Comment by ealsur** [comment]
If you do not use System.Text.Json to save your documents and instead use the default Newtonsoft.Json as the above snippet shows, that would solve the problem, correct?

**Comment by PunzunLtd** [comment]
OK. I appreciate what you're saying. But there's still a bug here, even if it's only a usability bug. Specifically, your statement "Spatial types, provided by the SDK, are Newtonsoft.Json compatible" is generally true but does not remain true when you use `System.Text.Json.JsonSerializer.SerializeAsync(Stream, object)` to serialize a `Point` object.

I filed this report because tracking down what was actually happening took a couple of hours. I think it would have been easier to track down if, instead of throwing a `NullReferenceException` the SDK threw a `SerializationException` instead. And I filed it here because the SDK, not the sample code or the JSON libraries, threw the exception that took me a couple of hours of digging through the SDK source code to figure out. I believe I identified exactly why the SDK throws an NRE, and I believe that this is an inappropriate outcome in the general scenario I've described (serializing a `Point` with `System.Text.Json` and deserializing it with whatever the SDK is using.

Another possibility is for the team responsible for `System.Text.Json` to make their serialization of `Point` compatible with naïve serializations such as Newtonsoft's. That would ensure that when the Azure SDK eventually switches to `System.Text.Json`, the switch doesn't break what could be millions of CosmosDB documents that serialized geospatial data using Newtonsoft's serializer.

Finally, if you provide feedback to the team responsible for the sample code I followed, please also mention that populating the dictionary `itemsToInsert` using the partition key as the dictionary key will failif a logical partition contains more than one document.

**Comment by ealsur** [comment]
I will follow up on the documentation with your feedback for sure.

Potentially, the `NullReferenceException` is because `Point` is being used to deserialize Json that was not generated with Newtonsoft.Json. It does make sense for the error to be more descriptive though, do you have the stack trace of the exception so we can see which line it might be? I do see several checks on the GeometryJsonConverter that throw `JsonSerializationException` (like https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Spatial/Converters/GeometryJsonConverter.cs#L64) but there might be other flow missing.

I don't believe the team behind System.Text.Json would be interested in supporting `Point`, this is a type provided by the SDK (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Spatial/Point.cs) and it has Newtonsoft.Json annotations. So when you use it with System.Text.Json it won't pickup or understand those annotations, generating a raw json that, if later deserialized with Newtonsoft.Json using also `Point`, wouldn't match. These Spatial types are helpers (they are just following the https://tools.ietf.org/html/rfc7946 standard using Newtonsoft.Json, but the same standard could be followed by a custom serializer with a custom type, for example, this was an experiment trying to get those types to support System.Text.Json https://github.com/Azure/azure-cosmos-dotnet-v3/commit/d706a6d4421e6e4ecbb112732f8f24363d9640e1), and not the only way to use GeoJson.

**Comment by PunzunLtd** [comment]
@ealsur , I believe the `GeometryJsonConverter` throws the NRE at line 64:
```
63 JToken typeToken = token["type"];
64 if (typeToken.Type != JTokenType.String)
65 {
66    throw new JsonSerializationException(RMResources.SpatialInvalidGeometryType);
67 }
```
...because I believe `token["type"]` returns null in that case.

I'm still concerned that the mismatch between Newtonsoft and Microsoft on the `Point` class means existing data may cause the SDK to fail in future releases.

**Comment by ealsur** [comment]
Thanks for the pointer, will try to repro.

I understand the concern, but in my humble opinion, the issue is arising due to a mix of types that are not meant to work together. `Point` is only meant to be used with the default SDK serialization (Newtonsoft). It is correct that it is possible for a user to use it with their own custom serialization and see unexpected results, in that case, it would be ideal to have this better documented on the Geometry classes themselves in order to avoid incorrect expectations.

**Comment by PunzunLtd** [comment]
So, what class should I use instead of `Microsoft.Azure.Cosmos.Spatial.Point`?

**Comment by ealsur** [comment]
The SDK does not have any alternatives for System.Text.Json serialization of GeoJSON data because that is not the serialization engine used by default.

You can either:

1. Use `Point` but use Newtonsoft.Json (default serialization). In your write flow code, you can use `CreateItemAsync` directly instead of serializing to Stream with System.Text.Json. That would also let your read/query flow work. This is potentially the best alternative.
2. If you do want to use System.Text.Json in your write flow, you'll need to either code or find a GeoJSON Point implementation for System.Text.Json. There are some hints of it on the linked commit I shared before. I am not aware of GeoJSON Point provided by the System.Text.Json team, but maybe there is.

**Comment by PunzunLtd** [comment]
OK, I'll try the CreateItemAsync flow, but I'm still very worried what happens when the SDK switches to `System.Text.Json` and all those point locations break. It seems like the prevention would be to create a point model class with just latitude, longitude, and elevation, and bypass the geometry classes entirely. As long as CosmosDB sees a field called "location" it seems to accept a lot of different document types as geospatial data.

**Comment by ealsur** [comment]
If you are using V3 SDK, the SDK won't ever switch to `System.Text.Json`. In the code you pointed at, it is the user code decision to utilize `System.Text.Json` to create Streams, that is outside of the SDK scope. If your user code makes the decision of using System.Text.Json to serialize data and pass it as Streams to the SDK, it is your user code responsibility to handle also the deserialization. The Stream APIs in the SDK are agnostic to the serialization mechanics you used to generate those Streams, they are just taking a Stream of bytes that represent raw Json, how you generated it, the SDK cannot know.

For the V4 SDK, we are planning to switch to `System.Text.Json` to align with all the other Azure SDKs, and in that case, there would be Spatial classes (like `Point`) versions that work with `System.Text.Json`. Since this would still following the GeoJSON standard, then serializing with V4 SDK and deserializing with V3 SDK would work, because underlying, it's just raw Json that follows the same standard.
