### ISSUE TITLE
Read only connection string

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-cosmos-dotnet-v3#2315]
Do read only connection strings provide a performance boost, or do they simply manage access?

For example, if I have a Cosmos account setup in multiple read and write locations (e.g. North and South Central US) would a client created with a read-only connection string perform faster because it would access the read-only replicas?

Or put another way, is there a benefit to creating two CosmosClients, one read-only, and another read-write, and then picking one based on the intended operation, i.e. use the read-only connection for queries, and the read-write for inserts / updates.

**Comment by ealsur** [comment]
Not that I'm aware, there is no performance benefit of using read-only keys, it is only to manage access.

**Comment by j82w** [comment]
Having multiple client instances on the same machine can lead to performance issues since the client instances do not share connections. That's why it's recommended to use a [singleton](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips-dotnet-sdk-v3-sql#sdk-usage). I'm also not aware of any performance benefit from using read-only keys.

**Comment by ealsur** [comment]
Closing as question has been answered.
