### ISSUE TITLE
Guidance on additional retry policies

### ISSUE THREAD

**Issue by stpetzinger** [Azure/azure-cosmos-dotnet-v3#2351]
We are currently wrapping the Azure Cosmos SDK with our own SDK that adds an additional layer of resiliency over top of the Azure Cosmos retry policies. We are looking into revising the logic on how exceptions from the Azure Cosmos SDK should be retried. I've read in [Exceptions.md](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Exceptions.md) that "Cosmos DB SDK on any IO failure will attempt to retry the failed operation if retry in the SDK is feasible", and that this includes read and query IO failures, but not non-idempotent write failures like create, upsert, etc.  I've also read at [Retry guidance for Azure services](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#cosmos-db) that "Exceptions that the [CosmosClient] raises are either beyond the retry policy or are not transient errors."  This could read that we should not automatically be retrying any CosmosExceptions, since any IO errors would have been retried the optimal number of times or duration, any remaining errors are not transient or not idempotent.  What is your guidance on implementing an automated retry policy on top of Microsoft's already existing policies?  Note that this question only refers to an automated retry policy on top of the Azure Cosmos policies and not any error handling that would be done at the application level.

**Comment by ealsur** [comment]
Hi @stpetzinger 

I am not sure who is the author of the "Retry guidance for Azure services", so I cannot comment on the wording there (which potentially can be improved), but on the SDK docs (https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-dot-net-sdk?tabs=diagnostics-v3#common-error-status-codes-) we document the different possible response codes.

Normally the SDK, if you use the `<T>` typed APIs, in the case of a non-success, you get a `CosmosException` that has a StatusCode that could map to the documented ones.

SDK has internal retries on known scenarios and the exception surfacing can mean that the number of retries were not enough. For example, 429s are retried as the documentation say, for a limited number of times, after that, the exception would get thrown. It does not mean further retries cannot be done, it simply says that the SDK retried the configured amount of time and even after that, your collection is being throttled. If you expect extended throttling, you could retry on top of the SDK or configure the SDK to retry more times on 429s, and/or understand if you need to scale the collection.

Other cases in the link I shared can also be retried, for example, Timeouts or 503s. Timeouts can happen due to transient network conditions (https://docs.microsoft.com/en-us/azure/cosmos-db/troubleshoot-dot-net-sdk-request-timeout#troubleshooting-steps), and the SDK will attempt to retry for Read operations (Writes are not idempotent). The SDK retries because it attempts to recover from a potential transient issue (it cannot know if its permanent or not), and if the number of retries are exceeded, it will throw the error out. The error itself contains information that can be used to understand the nature. You can certainly add a retry on Timeouts or 503s for Read operations (for Write operations, a retry could also lead to a 409 because the Timeout could be on the receiving), because sometimes connectivity issues can extend beyond what we retry on the SDK for some reason, the time we retry for is not a silver bullet, it is a best effort.

You can use any retry mechanism on top of the SDK, like using Polly on:

* 408s - Timeouts - retried internally as a best effort on Reads
* 429s - Retried based on configuration
* 449s - Retried internally also as a best effort.
* 503s - Related to connectivity issues - retried internally as best effort

**Comment by stpetzinger** [comment]
Thank you @ealsur.  That makes sense.  A couple questions, though.

1. Shouldn't we honor the user cancelling the operation by not retrying TaskCanceledExceptions?
2. You mention it is safe to retry 503's for Read operations.  Is there a property of the request or other way that we can tell that it is a Read operation?
3. We were considering retrying 500 errors.  What is your stance on that?
4. This is a slightly different topic but falls into same bucket (retry policy on top of the Azure Cosmos SDK) so I will ask it here. We are using request handlers in our SDK code and noticed that because all the responses in the Request Handler pipeline are of type ResponseMessage, we cannot use Polly to retry exceptions as we did in our previous versions because they are not thrown until the response is possibly deserialized by the client code.  Even if we were to return EnsureSuccessStatusCode() on the response which would trigger any exception, this would not account for scenarios in which the client called a streaming operation and did not intend for for any exceptions to be thrown.  What is your recommendation for retrying in the case where we don't know whether the client has submitted a Streaming request or a Typed request?

Thanks,
Steve

**Comment by ealsur** [comment]
1. Correct, but that might be a business application level decision. That might not be a recommendation that applies to all cases, just like retrying on 429 might not also be something everyone might want to do. Worth evaluating in each case.
2. The operation you are executing is either a Write (Create, Replace, Upsert) or a Read (Read, Query), so you already know the intent based on the type of operations you are executing.
3. I have mixed feelings on 500s. Maybe retrying once might be good in some scenarios, it could help if the 500 is temporary, but since there is no failproof way to really know that, it's hard to say "Yes, the retry will solve it", because a 500 does not communicate the nature of the failure in any way. If you want to retry, a single retry would be the best effort.
4. The question is, does it really matter if the user is using a Stream API or a Typed API from the failure point of view? The only difference is when the result materializes as you mentioned. If you are going the Handler route, and there is a 500 (following the previous example), the ResponseMessage will have StatusCode 500 regardless of the user calling it through Stream or Typed. And I believe with Polly you can certainly use the StatusCodes without requiring exceptions to be there, right?

**Comment by stpetzinger** [comment]
Thank you.

1. Since like you said it could be an application level decision I think we would let that fall on the application consuming our SDK.
2. I was just seeing if there was a built-in property of the RequestMessage or any way to get it.  If not then we would just manually set it.
3. Those are good points.  Thanks.
4. Initially we were not going to retry Streaming operations because we are in most respects a pass-through to the Azure Cosmos SDK in which exceptions from Streaming operations are just wrapped in a ResponseMessage instead of thrown.  In other words, for our SDK, if the response doesn't throw an exception, don't retry it because it is part of the design.  But this presented a problem because in the Request Handlers, exceptions aren't thrown for Typed operations either until they are deserialized by the client.  As a result, retries were occurring neither in streaming nor typed operations.   

You're correct that we can use the StatusCodes in Polly without requiring the exceptions to be there, so that would be one solution to that issue.  But we still would have a problem if we only wanted to retry Typed operations, because there is no way to natively know whether the operation was Typed or Streaming in the execution pipeline without adding custom metadata.  

That being said, your question, "does it really matter if the user is using a Stream API or a Typed API from the failure point of view?" may have some merit. The original intent of having users of the Streaming API handle all their own exceptions might be a moot point.  Retrying of requests might be a separate concern from which API they decide to use.

Lastly, as an alternative to changing our Polly retry code to look at ResponseMessage.StatusCode, is it reasonable to wrap operations with EnsureSuccessStatusCode() which as your know would return the successful response or throw an exception to be retried by our current policy?

**Comment by ealsur** [comment]
> Lastly, as an alternative to changing our Polly retry code to look at ResponseMessage.StatusCode, is it reasonable to wrap operations with EnsureSuccessStatusCode() which as your know would return the successful response or throw an exception to be retried by our current policy?

This could cause Stream operations to throw exceptions, which is unexpected. If the caller of your SDK uses the Stream APIs, they do not expect exceptions, if your handler calls EnsureSuccessStatusCode, it will throw. Again I think if your concern is a custom retry policy, it is independent of Stream or Type APIs, and the Handler pipeline is made so you can put your logic regardless of Stream or Typed API.

If your intent is to only add a custom retry logic for Typed API calls (which would leave Stream APIs uncovered and it sounds weird IMO, because how does the caller know that one API has your custom retry and the other doesn't?), you can instead of going through the pipeline approach, just wrap the Typed API call with Polly and that's it.

**Comment by stpetzinger** [comment]
> This could cause Stream operations to throw exceptions, which is unexpected. If the caller of your SDK uses the Stream APIs, they do not expect exceptions, if your handler calls EnsureSuccessStatusCode, it will throw. 

Yes. I forgot that some exceptions that wouldn't be retried and thus sent to the caller. Thanks.

> Again I think if your concern is a custom retry policy, it is independent of Stream or Type APIs, and the Handler pipeline is made so you can put your logic regardless of Stream or Typed API.

I am coming to this conclusion as well.  The challenge I initially faced was that our current policy code only handles exceptions and is shared with other SDK's, and that didn't work with the new Request Handler model and Streaming.  It does seem now that the best way is to create a new policy implementation that uses status codes instead of exceptions, and retry both Stream and Typed APIs for consistency.

**Comment by ealsur** [comment]
Closing as conclusion was reached in terms of the approach and questions answered.
