### ISSUE TITLE
Don't use exceptions for flow control

### ISSUE THREAD

**Issue by AndriySvyryd** [Azure/azure-cosmos-dotnet-v3#24]
On every cross partition query this exception is thrown and caught. This makes debugging much slower and probably degrades production performance.

>Microsoft.Azure.Cosmos.Internal.DocumentClientException
  HResult=0x80131500
  Message=The provided cross partition query can not be directly served by the gateway. This is a first chance (internal) exception that all newer clients will know how to handle gracefully. This exception is traced, but unless you see it bubble up as an exception (which only happens on older SDK clients), then you can safely ignore this message.
ActivityId: 17f2c157-c4c0-4ca1-9da2-8b3e42af20c5, Microsoft.Azure.Documents.Common/2.1.0.0
  Source=Microsoft.Azure.Cosmos.Client
  StackTrace:
   at Microsoft.Azure.Cosmos.ClientExtensions.<ParseResponseAsync>d__1.MoveNext()

**Comment by j82w** [comment]
Hi Andriy,

This exception will not occur if you follow the [performance tips](https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips) and use Direct Mode TCP on x64 platform. We haven't prioritized improving the implementation since our recommended connection mode prevents it, and there are other customer requests that have will provide a better impact.

If you get a chance please try out the new v3 SDK and provide any feedback or request you have. In the v3 SDK it now defaults to Direct Mode TCP to reduce the friction when on boarding. 

In the future please post issues around v2 SDK  to the[ v2 github repo](https://github.com/Azure/azure-cosmos-dotnet-v2/issues) 

Thanks,
Jake

**Comment by AndriySvyryd** [comment]
I didn't specify it, but I am using Microsoft.Azure.Cosmos 3.0.0.1-preview

**Comment by AndriySvyryd** [comment]
@j82w Can you reopen this?
I still get this when using the direct connection mode:
```C#
var client = new CosmosClient(
                new CosmosConfiguration(_endPoint, _authKey)
                {
                    ConnectionMode = ConnectionMode.Direct
                }));
```

**Comment by j82w** [comment]
Hi @AndriySvyryd ,

Sorry for the confusion. I thought the fix was in the initial release, but it has not been worked yet. I re-opened the issue until the fix is checked in.

**Comment by bchong95** [comment]
@AndriySvyryd The exception is thrown from the gateway as a first chance exception. If you switch to Direct + TCP and have access to ServiceInterop.dll you should avoid that code path immediately. In the future we are reworking the contract so that an exception is never thrown.

**Comment by j82w** [comment]
Fixed in: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/141
