### ISSUE TITLE
container.GetChangeFeedProcessorBuilder.WithStartTime not working in Version 3.20.0

### ISSUE THREAD

**Issue by wzzdzr** [Azure/azure-cosmos-dotnet-v3#2588]
**Describe the bug**
container.GetChangeFeedProcessorBuilder.WithStartTime not working in Version 3.20.0

**To Reproduce**
> ChangeFeedProcessor changeFeedProcessor = cosmosClient.GetContainer(databaseName, sourceContainerName)
                   .GetChangeFeedProcessorBuilder<ToDoItem>(processorName: "changeFeedSample", HandleChangesAsync)
                    .WithInstanceName("consoleHost")
                    .WithLeaseContainer(leaseContainer)
                    .WithStartTime(DateTime.UtcNow) // I have also tried DateTime.Now and other specific DateTime
                    .Build();

**Expected behavior**
CFP only receives changes from now on

**Actual behavior**
CFP receives changes which happened yesterday

**Environment summary**
SDK Version: 3.20.0
OS Version: Windows

**Comment by wzzdzr** [comment]
I notice "These customization options only work to setup the starting point in time of the change feed processor. Once the leases container is initialized for the first time, changing them has no effect." in document.
It seems that there is no way to set specific start time after the lease container was initialized.

**Comment by ealsur** [comment]
That is by design. Once the leases have been created they already contain the state and the continuations for the moment the host was started. As documents are processed, the continuations are updated, and the goal is, in the case the host crashes, it can pickup where it left off (latest saved continuation).
If you stop the processor and add the `WithStartTime` it makes no difference as the state has already been initialized.
If you want to reprocess the Change Feed for a specific point in time you need to stop the processor, and delete the lease container and recreate it or simply remove the lease documents.

**Comment by bartelink** [comment]
>simply remove the lease documents.

There's a [related feature request](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/510) for a programmatic way to achieve that.

**Comment by wzzdzr** [comment]
@ealsur Thanks for your reply.
