### ISSUE TITLE
Update documentation/comment for PageSizeHint

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-cosmos-dotnet-v3#2644]
The current definition of pageSizeHint is: The maximum number of items to be returned in the enumeration operation.(https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.changefeedrequestoptions.pagesizehint?view=azure-dotnet)

But sometimes customer will get more than the maxItems when multiple items are included in bulk/batch operation. Please update the documentation to also include it.

**Comment by ealsur** [comment]
This is expected behavior on Change Feed. Change Feed cannot break the transactional scope, if you create 10 item in a Sproc execution or using Transactional Batch, they all have the same LSN, if you read the Change Feed with a max items header of 5, the backend will always return 10, because it cannot break the transaction boundary.

Just needs a doc update.
