### ISSUE TITLE
Microsoft.Azure.Documents.Document replacement

### ISSUE THREAD

**Issue by CharlesToniolo** [Azure/azure-cosmos-dotnet-v3#2653]
Hi!

I have an Azure Function that receives inputs from the change feed and uses the Microsoft.Azure.Documents.Document class from the Microsoft.Azure.DocumentDB.Core package as the input type.
I'm basically replicating the data from one container to another.

```csharp
[FunctionName("ChangeFeedFunction")]
public async Task Run([CosmosDBTrigger(
    databaseName: "",
    collectionName: "",
    StartFromBeginning = true,
    ConnectionStringSetting = "",
    LeaseCollectionName = "")]IReadOnlyList<Document> inputs)
{
    if (inputs != null && inputs.Count > 0)
    {
        var taskList = new List<Task>(inputs.Count);

        foreach (var input in inputs)
        {
            taskList.Add(Container.UpsertItemAsync(input));
        }

        await Task.WhenAll(taskList);
    }
} 
```

I want to migrate this code to the new version of the Azure Functions with .NET 5. 
I would like to still receive "anything" and replicate that to the other container. 
How can I do that without using the Microsoft.Azure.Documents.Document class?

**Comment by ealsur** [comment]
This is the incorrect repository for this issue, you are asking about the CosmosDBTrigger, which is an Azure Functions extension (https://github.com/Azure/azure-webjobs-sdk-extensions/). In the future please use the Functions repository.

Migrating to Functions on .NET 5 is unrelated to any of the SDK packages, because that is the runtime. You should be able to run this same code on NET Core 3 or NET 5, there are no required changes.

The other question about not using the Document class, that is not currently possible because the CosmosDBTrigger uses the V2 SDK. When the CosmosDBTrigger packages gets upgraded to the V3 SDK (which is a work already in progress) then you will be able to stop using the Microsoft.Azure.Documents.Document class and use your own Model/T to receive the list of events (or JsonObject if you want something generic).
