### ISSUE TITLE
[vNext] nullable reference type support

### ISSUE THREAD

**Issue by Romfos** [Azure/azure-cosmos-dotnet-v3#2694]
Please, start using multitargeting (.NET Standart 2.0 + .NET 6) for V4 sdk and enable nullable refernce types by default :)
plus would be nice to remove some refrences for nuet pakcages that .net 6 have out of the box

**Comment by Romfos** [comment]
cc @kirankumarkolli

**Comment by j82w** [comment]
@Romfos the v4 SDK is controlled by the [Azure Core SDK team](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core) guidelines. Please open an issue against that repo to add support. The guidelines would need to be updated for all the SDKs. I'm closing the issue since Cosmos DB SDK has to follow that guideline and it is unlikely it would be allowed to diverge.
