### ISSUE TITLE
Set DateParseHandling mode to None in JSON.NET serializer.

### ISSUE THREAD

**Issue by krispenner** [Azure/azure-cosmos-dotnet-v3#2702]
Please consider adding the following line to the instantiation of the `JsonSerializerSettings` used by the Cosmos client and referenced below.

```cs
DateParseHandling = DateParseHandling.None,
```

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/abeb0e10a93677172612d461d505565cc3329e9e/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs#L48

My dates in Cosmos are stored in the format `2021-09-03T16:52:00+00:00` and without any intervention from me, are being deserialized and re-serialized as `2021-09-03` due to JSON.NET performing some internal date detection and modifications.

This JSON.NET "design decision" is discussed at length [here](https://github.com/JamesNK/Newtonsoft.Json/issues/862).

`System.Text.Json` does not do this sort of unsolicited data changes, so if the plan is to move to it then fixing this now will help prepare for the move later.

**Comment by j82w** [comment]
This would be a breaking change because any application that upgraded to a new version of the SDK would be dependent on the old behavior. Breaking changes can only be done with major SDK versions. You can apply this using a [custom serializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/abeb0e10a93677172612d461d505565cc3329e9e/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L445).  Here is an example of one: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs
