### ISSUE TITLE
Azure Cosmos Db In-built Triggers

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-cosmos-dotnet-v3#2718]
I would like to know if there was a way to create an in-built trigger for a particular Cosmos Db Database/Container. Any article or documentation would help a lot. Also wanted to know if we can create the trigger using .NET SDK. I am familiar with Azure Function Cosmos Trigger but I don't know if and how using Azure Function, we can create an in-built trigger hosted alongside the Cosmos Db database/container. Attached is the screenshot of our Cosmos Db database where we can see options for Triggers, Functions, Stored Procedures.

![image](https://user-images.githubusercontent.com/65625217/132723330-12491bb5-b39d-4a19-bebc-796b5c43d3ee.png)

**Comment by j82w** [comment]
The triggers operations are here and it has some sample code: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e3c08acff8830b918b516d9aae71637be352397f/Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs#L528

What is the use case for using a Cosmos DB Trigger?

**Comment by ssghoda** [comment]
We have created an Azure Search Index based on this Cosmos collection but we are not able to work with Soft Delete so we were thinking of using a Cosmos trigger so that when a Cosmos document is updated, we will query Azure Search Index for the incoming document and do some processing.

**Comment by j82w** [comment]
That won't be possible with Cosmos DB triggers. The Cosmos DB triggers are meant to modify the document. https://docs.microsoft.com/en-us/azure/cosmos-db/sql/how-to-write-stored-procedures-triggers-udfs?tabs=javascript#triggers

What I would suggest is looking into change feed. You could create Azure Function or some App that gets a list of documents that have been updated. You can then do what ever processing is necessary.
https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed

**Comment by ssghoda** [comment]
We came across Azure Function only but then we thought if it was possible to do the same thing in post-trigger in-built with database/container itself, we wouldn't need to host the Azure Function separately. 

While writing a post-trigger, we would get some metadata of the incoming document, make a REST API call to Azure Search Index, get back results and clean it up as per the change in the Cosmos document. Theoretically, it sounded good but didn't know if we could do that. :)

**Comment by ealsur** [comment]
There is a mix-up because naming is not easy.

The "Cosmos DB Trigger for Azure Functions" is one thing, and it is called Trigger because in Azure Functions, you have Bindings or you have Triggers. The Triggers react on events. If you want to hook Azure Search Index using this, you can start with: https://medium.com/microsoftazure/azure-cosmos-db-functions-cookbook-search-indexing-7059b7faa73f

The "Cosmos DB Pre/Post Triggers" are similar to SQL Server Triggers, in the sense that are logical executions that happen before or after a particular operation executes. The difference though is that in Cosmos DB you need to specify which Pre/Post Trigger you want to include on the operation execution itself (like the CreateItemAsync call) and these Triggers are Javascript based, and you cannot do anything else besides working with the document information (you cannot connect to Azure Search for example).
