### ISSUE TITLE
Expose 449(RetryWith) configuration

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#2771]
# Issue
The current SDK automatically retries on 449(RetryWith) exceptions. The 449 usually represents a concurrent write conflict. If the user is getting 449s they should look at their application design to avoid these write conflicts. The current problem is with the SDK automatically retrying on these exceptions the user might not know if they are hitting these exceptions. If they are hitting the exception they have no way to control the retry policy which can increase the latency of the requests. 

# Two different options to expose control to the 449 retry policy

## 1.  Disable RetryWith policy
The RetryWith exception usually points to a conflict with Writes on trying to update the same item concurrently. The application should be changed to avoid these exceptions. Having a simple off switch gives the users the ability to easily monitor if a request hit a RetryWith exception.

```c#
public class CosmosClientOptions
{
...
     public bool? DisableRetryAttemptsOnRetryWithRequests { get; set; }
....
}
```

## 2.  Configure retry count
There is currently 3 internal properties already for controlling the RetryWith logic. These fields could be made public. This would allow user to control the retry policy.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/919bb3b4e7012b22850446890f2d95ea594866ab/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L589

```c#
public class CosmosClientOptions
{
...
        public int? InitialRetryForRetryWithMilliseconds { get; set; }
        public int? MaximumRetryForRetryWithMilliseconds { get; set; }
        public int? RandomSaltForRetryWithMilliseconds { get; set; }
....
}
```

// This is an example of the 429(Throttle) options being exposed.
```c#
public class CosmosClientOptions
{
...
     public int? MaxRetryAttemptsOnRateLimitedRequests { get; set; }
     public TimeSpan? MaxRetryWaitTimeOnRateLimitedRequests { get; set; }
....
}
```

### Recommendation is option 1
Option 1 to allow users to disable the retry attempts on the RetryWith exceptions. This gives the users the ability to add there own custom retry logic on top of the SDK which they can customize and monitor. 

Please respond with any comments, questions, and/or concerns.

**Comment by ealsur** [comment]
The question I would ask myself as a user if I see these settings is: Why am I getting 449s? Is it ok? Should I change my usage pattern to reduce/remove them? Do they happen only based on my usage (like 429s) so I'm completely responsible about them or can they happen due to some service/backend condition unrelated to my usage?

Anytime a configuration is available, a user would ask in which scenarios and why should they touch it. Do I need to worry about it?

I still think 449s are a bit obscure in terms of what they truly mean, we don't have any service docs (except one that says they are retriable) that fully explain why could I get it?

Starting with the user scenario and explaining why would a user want to tinker/disable it, then it might help understand which API design is better. Should it be simple or complex? If complex, what is the explanation we can give so a user knows which values to use without shooting themselves in the foot? If we cannot explain that, then it means it's overly complex.

**Comment by j82w** [comment]
I updated the description with more information about what the issue and explaining why user needs to control it.

**Comment by j82w** [comment]
After discussion the 449 is just a signal saying the SDK should retry. There is no clear action that customer can do besides retrying. The SDK has already made improvements to the retry policy to make it more aggressive on retries.
