### ISSUE TITLE
IndexMetrics on QueryResponse

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-cosmos-dotnet-v3#2855]
Currently IndexMetrics is on QueryResponse<T> but not QueryResponse,

see: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Query/v3Query/QueryResponse.cs

It would be great to have the new IndexMetrics feature on the QueryResponse object; is there a technical limitation why this cant be done? Currently I am using The 'Stream' response so I can handle deserialization without Newtonsoft Json, so QueryResponse<T> is not being used.

**Comment by ealsur** [comment]
@leminh98 Could you help answering the customer question? Which is the solution for someone that consumes the Stream (ResponseMessage) API?

**Comment by ealsur** [comment]
@onionhammer Since getting the IndexMetrics is not something you'd leave enabled on production, isn't it possible to just use the normal `FeedIterator<T>` and analyze the metrics that way?

**Comment by onionhammer** [comment]
@ealsur sure I could theoretically. Is there a technical reason why the index stat is on the generic `QueryResponse<T>` but not the `QueryResponse` class?

**Comment by ealsur** [comment]
Not that I can think of, will let the author @leminh98 comment on that, I was just trying to think of an alternative that could unblock you.
If I understand correctly, the idea is that Index Metrics is something you use sporadically, not on a real case where you want to consume the results in production, so you should be able to leverage the normal `<T>` API without even consuming the actual results.

**Comment by j82w** [comment]
@onionhammer why are you referencing QueryResponse? I'm curious because the public contract is the ResponseMessage.

While it's not ideal you should be able to do something like this as a workaround:
var base64String = responseMessage.Header["x-ms-cosmos-index-utilization"];
string indexString = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(base64String));

**Comment by j82w** [comment]
@timsander1 any suggestions?

**Comment by onionhammer** [comment]
@ealsur it's something I would like to be able to debug/troubleshoot without rearranging my code every time I need to do that, if that makes sense.

**Comment by ealsur** [comment]
Makes total sense and I don't see any technical blockers if the information is available in `FeedResponse<T>`. Maybe at least some guidance on how to read the header would be good.

**Comment by leminh98** [comment]
As @ealsure mentioned, the idea for the IndexMetrics was to be a one-off debugging feature so I only put it in the non-stream API so that I can parse and display the header in a readable/pretty-text format to users. I will look into adding this to the Stream API. For now, if you want to be unblocked, the above workaround works
