### ISSUE TITLE
Don't use object for partition key

### ISSUE THREAD

**Issue by ausfeldt** [Azure/azure-cosmos-dotnet-v3#287]
**Is your feature request related to a problem? Please describe.**

object as partition key is ambiguous as only a small set of types is accepted. Also unboxing/boxing object is not performant. 

**Describe the solution you'd like**

Use PartitionKey with constructor overloads or factory methods for each supported type

**Describe alternatives you've considered**

If we don't want make changes to PartitionKey, and not rock the boat, create and adapter to PartitionKey called PartitionKeySettings and use that

**Comment by j82w** [comment]
I agree with having a specific type instead of object. This will also make it easier for users to find on google and stackoverflow if they have issues. 

We should also be able to get additional performance improvement by handling CosmosElement/ byte array to avoid converting the PK from the stream to c# object.

**Comment by SiddheshV** [comment]
There was a specific reason for introducing PartitionKey as Object.  Please sync with @visridha

**Comment by kirankumarkolli** [comment]
Mian goal of Object is to avoid boiler plate new ParittionKey(value) application code.

**Comment by j82w** [comment]
I think the boiler plate is a necessary evil. It makes it clear to user what types are supported, and it allows us to make it easier to discover new supported types.
