### ISSUE TITLE
Question: Is a session token per document, partition key, logical partition, physical partition, region?

### ISSUE THREAD

**Issue by krispenner** [Azure/azure-cosmos-dotnet-v3#2876]
Based on the structure of the session token, I'm assuming it relates to the logical or physical partition but I'd like confirmation of what it relates to.

Let's say I have a partition key per "user" with multiple documents created under the user's partition key.
After I create document 2 under user A's partition key, can I then use the session token returned from the create operation to read document 1 from user A's partition key guaranteeing that document 1 will be the latest version since the creation of their document 2?

Or is the session token per document like an ETag, in which case it's really not much different than the ETag in many ways. I assume and hope it is not per document, but I can't find any topics explicitly stating to what data range we can share a session token across.

For instance, neither of the documentation quoted below seems to really, or clearly, explain what I'm asking about:

> One of the consistency levels in Azure Cosmos DB is Session consistency. This is the default level applied to Cosmos accounts by default. When working with Session consistency, the client will use a session token internally with each read/query request to ensure that the set consistency level is maintained.
>
> To manage session tokens manually, get the session token from the response and set them per request. If you don't need to manage session tokens manually, you don't need to use these samples. The SDK keeps track of session tokens automatically. If you don't set the session token manually, by default, the SDK uses the most recent session token.

- https://docs.microsoft.com/en-us/azure/cosmos-db/sql/how-to-manage-consistency?tabs=portal%2Cdotnetv3%2Capi-async#utilize-session-tokens

> In session consistency, within a single client session reads are guaranteed to honor the consistent-prefix, monotonic reads, monotonic writes, read-your-writes, and write-follows-reads guarantees. This assumes a single "writer" session or sharing the session token for multiple writers.
>
> Session consistency is the most widely used consistency level for both single region as well as globally distributed applications. It provides write latencies, availability, and read throughput comparable to that of eventual consistency but also provides the consistency guarantees that suit the needs of applications written to operate in the context of a user. The following graphic illustrates the session consistency with musical notes. The "West US 2 writer" and the "West US 2 reader" are using the same session (Session A) so they both read the same data at the same time. Whereas the "Australia East" region is using "Session B" so, it receives data later but in the same order as the writes.

- https://docs.microsoft.com/en-us/azure/cosmos-db/consistency-levels#session-consistency

Thank you.

**Comment by ealsur** [comment]
The session token contains the transactional identifier up until which the current client has written on that particular container, but only includes the container partitions state that the current container interacted (did writes on) with, not all. The intent is that whatever the current client has written up to, another client can read and see.

> After I create document 2 under user A's partition key, can I then use the session token returned from the create operation to read document 1 from user A's partition key guaranteeing that document 1 will be the latest version since the creation of their document 2?

If document 1 was created by the same client instance, in an operation that was not concurrent to the creation of document 2 (finalized and was completed before), then yes, it should work, because the creation of document 2 would have a higher transactional number than document 1, but if you send document 1 and 2 concurrently and only capture the SessionToken from 2, it might or might not include 1, depending on the order the requests were processed.

The SessionToken is not per document, but rather, it identifies a point in the transaction history of the container, that the current client has written up to.

Others might pitch it for more details.

**Comment by krispenner** [comment]
@ealsur, thank you very much for your insights here. It sounds like I should be OK.

To better clarify my example, document 1 was created prior to document 2 not at the same time.

> The SessionToken is not per document, but rather, it identifies a point in the transaction history of the container, ...

If the SessionToken is defined at the container level, then it applies to all four physical partitions of the container?

So when specifying a SessionToken, I'm guaranteed to receive the latest data up to when the SessionToken was returned for reading of any document in any partition key on any physical partition of the container?

However, you then go on to include:
>... that the current client has written up to.

I'm confused by this, can we remove that part of your description and it sill means the same thing?
I need to share the session token across requests, I pass it back in a header to our API consumer and they return it to in future requests. So we create a new Comsos SDK client in subsequent requests, it's not the same client. Can you clarify what you mean by "client" and how that is affected in the above?

**Comment by ealsur** [comment]
> To better clarify my example, document 1 was created prior to document 2 not at the same time.

Then the Token from document 2 should also cover the existence of 1. But again, it is not guaranteed by the token itself, just by the way your application works. "Read my writes" is mainly to track and be able to read this last write that I just did, that write could be a single write, or for example, a TransactionalBatch operation that includes 100 documents as a single transaction. In a scenario where you have concurrent writes, each write might return a different token, some of them higher in transactional identifier than the other, depending on when the concurrent operation completed.

>If the SessionToken is defined at the container level, then it applies to all four physical partitions of the container?

> So when specifying a SessionToken, I'm guaranteed to receive the latest data of any document with any partition key on any physical partition of the target container (up to when the SessionToken was originally returned)?

The key is "that the client interacted with". The client tracks and returns Tokens from partitions it wrote to, if it never wrote to a partition, then it will never return a token that includes that partition's state, because the intent of the Session Token is "Read my Writes", then if I (client) never did a write to it, there are no writes to read. And you are not guaranteed to get the "latest", you are guaranteed to get up to the transactional identifier represented by the Session Token, what was included in the partition, which includes the write that generated that token

>I'm confused by this, can we remove that part of your description and it sill means the same thing?
I need to share the session token across requests, I pass it back in a header to our API consumer and they return it in subsequent requests. So we create a new Comsos SDK client in subsequent requests, it's not the same client. Can you clarify what you mean by "client" and how that is affected in the above?

"that the current client has written up to" means what I explained previously. One client performs write operations and the Session Token is the result of a write operation to a partition. If Client 1 does a write on instant A, gets a Session Token, then 10 hours pass without Client 1 doing anything, while Client 2 is performing writes all along, Client 2 will have a Session Token that would include the writes Client 2 did, which have a higher transactional identifier than whatever Client 1 has, but whatever Client 1 has is enough to read whatever Client 1 wrote.

I'm not sure why you need to create new SDK clients on subsequent requests, but I would refrain to do so and try to follow the Singleton pattern, unless you are using Resource Tokens for authentication based on the current Web user? In any case, the flow would be:

1. User calls Web API to write
2. Your Web API writes and returns the SessionToken to the caller in a header
3. User then wants to read the data he just wrote, calls the Web API and passes the Token it has
4. Your Web API receives the call, calls the client and passes the Session Token on the ItemRequestOptions and should be able to find that write operation.

**Comment by krispenner** [comment]
> The client tracks and returns Tokens from partitions it wrote to

I thought the Cosmos service returns the SessionToken, but your explanation is making me question if maybe the client is generating the SessionTokens somehow internally themselves. Can you please confirm if the Cosmos DB service or Cosmos SDK client generates the SessionToken?

> I'm not sure why you need to create new SDK clients on subsequent requests, but I would refrain to do so and try to follow the Singleton pattern

We do follow the Singleton pattern, but we scale out our API hosts and we don't use any session affinity cookies for routing back to the same host. So a new (different) SDK client will be used in the other API host's process.

**Comment by ealsur** [comment]
> I thought the Cosmos service returns the SessionToken, but your explanation is making me question if maybe the client is generating the SessionTokens somehow internally themselves. Can you please confirm if the Cosmos DB service or Cosmos SDK client generates the SessionToken?

They are returned by the service but the client keeps them stored in a cache besides returned them to the user. The reason is, the Session Consistency documentation you linked states that Session Consistency is maintained when using the same client OR passing the session token. The "Session" is the scope of operations that a client instance is doing, when you use the same client, you don't need to pass the Session Token in and out, because the client takes care to enforce the consistency by "remembering" the tokens it already received if you are not passing a Token on the read.

> Sorry, I should have been more specific with our implementation. We do follow the Singleton pattern, but we scale out our API hosts and we don't use any session affinity cookies for routing back to the same host. So a new (different) SDK client will be used in the other API host's process for subsequent requests.

Passing the Session Token from the Write operation when performing the Read, in any other client that it landed on, should make sure the document is readable.

**Comment by krispenner** [comment]
Thank you for the confirmation and clarification - that all makes sense. So for our purposes, we can use that last session token received from any client that wrote any document within the user's partition key for reading any other document within the user's partition key on another client and be sure to get the latest since the session token was generated.

1. Client 1 writes document A within partition key P, receives session token Ax
2. Client 2 writes document A within partition key P, receives session token Ay
3. Client 3 writes document B within partition key P, receives session token Bx
4. Client 4 reads document A within partition key P, with session token Bx (guaranteed to read Client 2's writes)

I think it would be great if a dedicated section was created for documenting what you have explained regarding session tokens.
- they don't relate to a single document
- they relate to all partitions last written too by the client who did the writing
- reading any document from any of the partitions in the session token will read the latest since the session token
- maybe include a simple example like mine above

Because I can't find any documentation that detailed this and what you have explained here is super helpful and I think many would find it useful in planning their session based approach. I think a lot of people may assume a session token related to the document written and can only be used for reading that document so this will have a big impact on their understanding and maybe prevent them from choosing bounded staleness when it isn't needed.

Thank you very much @ealsur for all your time and help.
