### ISSUE TITLE
Linq expression on Nullable<T>.HasValue does not work when using camelCase serialization

### ISSUE THREAD

**Issue by ssa3512** [Azure/azure-cosmos-dotnet-v3#2916]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Due to the logic in ExpressionToSQL, when `camelCase` serialization is enabled, `Nullable<T>.HasValue` does not translate to IS_DEFINED, and instead translates to ["hasValue"] in query text.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/df040f31ad69da38eafab3076025e4cad92e129d/Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs#L737-L756

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.
```cs
void Main()
{
    var client = new CosmosClient("connectionString", new CosmosClientOptions()
    {
    	SerializerOptions = new CosmosSerializationOptions()
    	{
            PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
    	}
    });
    var container = client.GetContainer("x", "y");
    var query = container.GetItemLinqQueryable<C>()
    	.Where(x => !x.NullableValue.HasValue || x.NullableValue == null);
    Console.WriteLine(query.ToQueryDefinition());	
}

public class C
{
    public DateTime? NullableValue { get; set; }
}
```
**Expected behavior**
Query is `SELECT VALUE root FROM root WHERE ((NOT IS_DEFINED(root["NullableValue"])) OR (root["NullableValue"] = null))`

**Actual behavior**
Query is `SELECT VALUE root FROM root WHERE ((NOT root["nullableValue"]["hasValue"]) OR (root["nullableValue"] = null))`

**Environment summary**
SDK Version: 3.23
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Additional context**
N/A

**Comment by jackbond** [comment]
I haven't run it in the Debugger, but if member name is getting set to "value" or "hasValue" then obviously the checks on lines 746 and 752 will fail. That's an easy fix. However the real issue is, assuming the code was fixed, WHY is HasValue being converted to IS_DEFINED, as they are two entirely different concepts. HasValue is a c# null check, while IS_DEFINED checks to see if a property is present with the JSON text.

If the Cosmos team wishes to conveniently handle HasValue, it should be converted into a null check. Consider the following query,

.Where(x => x.NullableValue.HasValue)

A C# programmer is going to expect documents where NullableValue is not equal to null, but will get back documents containing the following JSON:

nullableValue: null

The documents returned by this query will literally have NullableValue.HasValue equal to false, which is the exact opposite of plain language intent of the query.

I looked at the history a bit, and it looks like HasValue has been converted to IS_DEFINED for a while, but for my money, this should absolutely be considered a bug, and should be fixed and listed as a breaking change in the 4.0 release.

**Comment by ssa3512** [comment]
@jackbond there has been some discussion about this behavior over at https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2248 but for now this is the behavior of the SDK, and since the `IsDefined` LINQ extension is not unit testable this is the only mechanism to use LINQ/`IQueryable` to check for an undefined value and be able to have test coverage. That being said, it seems to make sense to fix the issue with the existing behavior independently from any proposals of behavior changes.

**Comment by jackbond** [comment]
Setting aside the absolutely insane current implementation, I'm curious, what isn't testable about IsDefined?

**Comment by ssa3512** [comment]
> what isn't testable about IsDefined?
The implementation is `throw new NotImplementedException()` so while it works if you use it with the SDK IQueryable provider, it will throw in unit tests. Since it's an extension method there is no way to mock it.
