### ISSUE TITLE
Create/query document Dependecy calls Canceled on Linux

### ISSUE THREAD

**Issue by WouterSlob** [Azure/azure-cosmos-dotnet-v3#3032]
**Create/query document Dependecy calls Canceled on Linux**
We are comparing App Services running on Windows and Linux. Our test contains a heavy CosmosDB query load which we send to the separate environments with their own CosmosDB instance. We use the Direct Connection Mode.

On Windows there are no dependency failures. On Linux there are quite a lot failures for outgoing command **Create/query document** to the **/colls/MyCollection/docs** endpoint.

Typically most calls are canceled after 500ms, but some are canceled after 2 seconds.

When we increase the load the number of canceled call also increases.

There seems to be no impact on query output / performance. The system works.

In the [documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips-dotnet-sdk-v3-sql?tabs=trace-net-core#hosting-recommendations) it is stated that Linux uses the gateway to get the optimized query.
We do see two different dependency calls on the Linux environment, which are not logged in the Windows environment:
- Create/query document
- Query documents

**Questions**
- What kind of calls are the **Create/query document**? What are they used for?
- Are there any limits on Gateway level for these query calls? Is there a rate limit?

**Comment by j82w** [comment]
1. Is your application in the same region as the Cosmos DB account?
2. Are you specifying the partition key in the request options? 
3. Are these single partitions queries?
4. Do they have aggregates like 'order by', 'group by', etc?
5. Make sure to follow all the recommendations: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips-dotnet-sdk-v3-sql?tabs=trace-net-core 

The performance document linked above explains why Windows x64 is recommended for query workloads. There is a 'ServiceInterop.dll' which allows the SDK to generate the query plan locally. On Linux the SDK may have to go to the gateway to get the query plan depending on the query. If the query has the partition key specified in the request options and it does not have aggregates, then the SDK can handle it locally. Otherwise, it has to go to the gateway to get the query plan.

If the application is doing cross partition queries I would recommend investigating if a different partition key could be used to limit it to a single partition key. Cross partition queries will always be slower, more expensive, and do not scale as good as single partition queries.

**Comment by WouterSlob** [comment]
1. Is your application in the same region as the Cosmos DB account? **Yes**
2. Are you specifying the partition key in the request options? **Yes**
3. Are these single partitions queries? **Yes**
4. Do they have aggregates like 'order by', 'group by', etc? **No. But we do use ST_DISTANCE and ARRAY_CONTAINS for filtering.**

5. Make sure to follow all the recommendations: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips-dotnet-sdk-v3-sql?tabs=trace-net-core
6. Please provide the diagnostics of the slow request: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-dot-net-sdk-slow-request?tabs=cpu-new#capture-diagnostics

**Performance is not a problem. It works ok on Windows and the performance on Linux is comparable.**

We just would like to understand why we are getting this dependency canceled failures on Linux and we would like to know if there are any limits on the gateway that might give problems in the future when the load increases.

**Comment by ealsur** [comment]
Wouldn't this question then be more in the App Insights repo? They would know exactly what is considered "Canceled" on their UI.

**Comment by j82w** [comment]
The SDK has the following retry logic: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1954. It should not be taking .5 seconds for the gateway to respond with the query plan. This points to a possible issue. Can you provide the diagnostics of one of the queries?

@timsander1 can you answer the question regarding the limits of gateway?

**Comment by j82w** [comment]
If you are seeing failures on write operations? If so, can you provide the exception for the writes?

**Comment by WouterSlob** [comment]
It seems to happen only on reads.

I've tried to gather the diagnostic from this canceled request:
![trace](https://user-images.githubusercontent.com/4522980/154271205-954395ed-a193-4608-b53d-cdf99b7f716f.png)

Diagnostics:
[trace.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/8080103/trace.txt)

Unfortunately AppInsights did not store the complete trace. Is the first part workable?

**Comment by j82w** [comment]
Do you have any more info on what the first Create/query document call is? Based on the diagnostics provided it was able to create the query plan locally, so it did not have to go to gateway to get it. The first network called shows a success.  All the caches seem to be warmed up. It's possible the full diagnostics might have more info. 

Is AppInsights automatically collecting this info in direct mode?

**Comment by ealsur** [comment]
What does "Canceled" mean in App Insights? The answer to that question would then shed more light on exactly why it appears there.

**Comment by cedrox** [comment]
Hello
We are currently using the package version v3.21 and are facing the same issue. The call we make is:
ReadItemAsync<T>(id, new PartitionKey(partitionKey));
The following call has no issue.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/10764310/156161466-3ff1408b-d70f-4d9f-b4e9-dd1d7a222f58.png)

Is it possible for you to coordinate troubleshooting with app insight team ?

Thanks

**Comment by onionhammer** [comment]
This happens quite frequently on my system running on Linux as well.

Is microsoft going to address this windows/linux inconsistency at some point or are we all just satisfied with the "Run on windows x64 for best performance" advice?

**Comment by pbiasotti** [comment]
We are seeing kind of the same behavior with an Azure function hosted in windows. The function and the Comos DB instance are in the same region and we are using the NuGet Microsoft.Azure.Cosmos 3.27.1.

The parent call looks like finishing correctly returning the status code 200 but seems there is an internal call being cancelled which is generating noise in our monitoring.

By looking at the code looks like it's executing the query `SELECT TOP 1 * FROM Collection` using `Container.GetItemQueryIterator<T>(QueryDefinition)` to check if the collection is empty. Is there something we can do to avoid this error (which is not consistently happening)?

_App insights logs_
![image](https://user-images.githubusercontent.com/19777960/183645030-9ee73cde-527e-4969-bca7-f82638857eb8.png)

![image](https://user-images.githubusercontent.com/19777960/183645492-b1842299-53f0-4f26-9edd-4a04d8c333ff.png)

![image](https://user-images.githubusercontent.com/19777960/183645895-35fffb4f-885d-4aed-a6a6-1dcd043e944f.png)

**Comment by ealsur** [comment]
@onionhammer Thanks for the comment. Like I explained, the "Canceled" is something Application Insights is interpreting in their own way.

The SDK is issuing an HTTP call, the call is taking more than 500ms (this is the problem), the SDK is being proactive, cancelling that request and retrying. If the request would not be 500ms, it would not cancel and retry. The whole reason for the cancelling is the latency on the request. The latency of the request is a product of the application environment + network + Cosmos DB Gateway. Gateway latency could be seen on the Azure Monitor metrics on the account (I am not sure about this but it might be there) but otherwise can be verified through a Support request (Gateway could have a latency spike but should not impact P99 of your application). If Gateway is not the source of the 500ms latency, then it's on the network or the application environment.

Some scenarios where the network is involved is networking issues (packet retransmits in the middle), network bottleneck on the network interface or hardware failures. Some scenarios for application environment issues are running the application in a different Azure region (hence you will always have high latency due to cross-region geographical distance), blocking async operations and not allowing threads to resume, using proxies with misconfigurations.

The HTTP call to obtain the Query Plan cannot be avoided for cross-partition queries, that is by design on the service itself.

Query operations do not have any latency SLAs. If you do believe there is an SLA breach, please feel free to contact support.

**Comment by onionhammer** [comment]
@ealsur It sounds like you're trying to convince us that constant random blocking HTTP 500ms timeouts driven by the Cosmos SDK running in a single azure datacenter alongside Cosmos is either 

A) Our fault or 
B) Not an issue at all

Is this right?

**Comment by ealsur** [comment]
@onionhammer I am not trying to convince you of anything, I am explaining how the SDK behaves.

The SDK is not the cause of the HTTP call on your environment to be taking 500ms, these are not "driven by the Cosmos SDK". This is an HTTP request done through the HttpClient, that is all the SDK is doing.

I agree the 500ms latency should be investigated, as I explained, the source of such latency is not the SDK.

**Comment by onionhammer** [comment]
@ealsur The SDK creates the request that blocks any awaiting code and is ultimately cancelled, that is what I mean by "driven by the SDK".

**Comment by ealsur** [comment]
Yes, the SDK creates the HTTP request, I explained the reason, it is needed to obtain the Query Plan (the query cannot be executed without it).

When the request completes and the Query Plan is obtained, the Cross-partition Query can be executed.

This is by design.

If the HTTP request to obtain the Query Plan takes 10ms, 5ms, 500ms or 20 seconds, that is outside of the SDK scope. The problem here is the request is taking longer than 500ms (Application Insights is measuring the raw HTTP request latency, so this time is not SDK code introducing latency through code execution). This is the root of the issue, the request latency.

**Comment by ealsur** [comment]
If you believe that the design that requires the Query Plan to be obtained is at fault, that goes beyond the SDK and into the Query engine of the service. We can share that feedback with the service team for certain.

**Comment by onionhammer** [comment]
@ealsur this behavior does not happen on Windows, correct? So this is a limitation of the .NET SDK on Linux?

**Comment by ealsur** [comment]
The requirement for the Query Plan is always there (Windows or Linux), so obtaining the Query Plan is always a requirement for Cross-partition queries. If the Query is not cross-partition, then it is not needed.

For the .NET SDK (only .NET), the Query service team provides a native DLL that works on Windows/x64 (not x86) that allows for the Query Plan to be generated locally (https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips-query-sdk?tabs=v3&pivots=programming-language-csharp#use-local-query-plan-generation), so on this conditions, the HTTP request can be avoided and the native DLL invoked. For Linux, or Windows that do not meet the criteria, the .NET SDK behaves like the Java/Python/NodeJS SDK and sends the HTTP request to obtain the query plan.

If the request is for a native DLL that works on Linux (you requested it on https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2768) that is something the Query service team should evaluate. 

If this native DLL did not exist, then the .NET SDK would simply behave like the Java/Python/NodeJS SDKs and always do the network request regardless of platform. Sure, this sounds like playing favorite with Windows+.NET and I also agree that this DLL should made available for other platforms or removed, but the current state is that it is only being produced for Windows.

Going to the root cause of this Issue (What does the Canceled mean?), 500ms for an HTTP request on the same Azure region is not something normal, even on Linux, there shouldn't be this network latency impact for this request. What is the cause of the latency? I provided already potential causes, but from the SDK perspective, I cannot tell you exactly which of them, nor there is anything on the SDK code we can change to lower that latency.

If we removed the retry after 500ms, then your query would either throw a timeout exception (the HTTP request eventually failed with a timeout) or succeeded with a latency way higher than 500ms (because we didn't stop and retry, the original request took whatever time it was going to take, maybe in the seconds range). So the retry after 500ms is helpful.

**Comment by onionhammer** [comment]
So to recap, you're saying that while there is a limitation of the SDK on linux (#2768), you're saying this could also happen on Windows (perhaps less frequently?)

If the issue is on the Cosmos service-side, you're saying there's nothing you can or should do because that's not your purview as someone who works solely on the SDK? There are no channels you could use to communicate this issue to the backend team, so customers are left to just open up a service ticket?

**Comment by dnolan** [comment]
@onionhammer I need to check tomorrow (11pm here), but I'm following this thread as we have been getting this Cancelled issue in AppInsights, and we're running in Windows, so I think the Linux comments further above are perhaps a red herring.

**Comment by ealsur** [comment]
Yes, if you run on Windows/x86 you would also see the HTTP call for Query Plan. Both the application needs to be compiled as x64 and the environment should be set as x64 (for example, App Service has such a configuration).

What I'm saying is that the 500ms+ latency is not on the SDK scope. I cannot say it is on the Cosmos DB service. I can only say it is not in the SDK (not time spent on computational execution on the SDK), it could be time spent on the network (a problem on the network interfaces in your Compute / App Service), it could be a network interface overloaded (max number of connections or concurrent requests), or it could be latency on the Cosmos DB Gateway service.

I cannot help from this repo to troubleshoot where the latency is coming from, I can help in this repo if the Issue is a bug or a problem on the SDK code, which in this case it isn't.

In those cases where P99 latency is affected, this needs to be investigated by Azure Support, they can take a look at your Compute, and also have access to the Gateway service to investigate the latency and follow up with the Gateway service team if needed, or with the App Service team if that is your Compute, or with Azure Networking if the problem is related to network interfaces.

**Comment by amolkhairnar21** [comment]
Create/query document call RequestCanceled error we are getting for out Bot
![image](https://user-images.githubusercontent.com/1864293/235611388-508259b8-aa2c-4177-9b0d-f51e3bcfbd7f.png)
Please check provide some help Thanks!!!

**Comment by ealsur** [comment]
Closing this issue as it is becoming a dumping ground.

@amolkhairnar21 please read the comments on this thread to understand more what does the Canceled mean in your AppInsighta metrics, particularly https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3032#issuecomment-1227434296

**Comment by CallumRBreen** [comment]
@onionhammer Did you manage to resolve this issue? Currently, on Microsoft.Azure.Cosmos 3.3.36 using Direct Connection mode and still getting these dependency failures

**Comment by onionhammer** [comment]
@CallumRBreen I havent seen this in a while, I have 1 app still running 3.31.1 and am not seeing it in the logs anymore.
