### ISSUE TITLE
Group By queries return results in a different order than the online query editor

### ISSUE THREAD

**Issue by admo-1** [Azure/azure-cosmos-dotnet-v3#3166]
I do not understand why that is. When the same query that uses `GROUP BY` is executed against the same collection, `GetItemQueryIterator` returns the results in the opposite order than the online query editor.
Is there a logical reason that explains this behaviour?

**Comment by j82w** [comment]
@timsander1 can you please take a look?

**Comment by timsander1** [comment]
Hi @admo-1, could you share an example? Some of GROUP BY logic is in the SDK so my suspicion is that there's slight different logic in the .NET SDK and JavaScript SDK (which the Data Explorer uses) that impacts the ordering of results. Assuming they include all the query results, these are both correct results since there isn't a defined ordering of GROUP BY query. That being said, I agree that it would helpful if all SDK versions returned GROUP BY query results in the same order, so we add a work item to fix this.

**Comment by admo-1** [comment]
Hello, sorry I have been off for some time.
Please find attached to this comment the Json file to upload in your container, and the query/code I use that produces this bug. 
I also added the result I get when I run the same query on the online query editor.
I put them in a zip since JSON and CS files are not supported.
[json+code.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/8689179/json%2Bcode.zip)
Thank you very much, take care.

**Comment by neildsh** [comment]
Hello @admo-1, my apologies for the late response here. GROUP BY does not guarantee any ordering on the results. Hence, I am closing this issue.

We are looking into supporting ORDER BY in the presence of GROUP BY to allow ordering group by results. This will be mentioned in the release notes once it is implemented.
