### ISSUE TITLE
Clearer documentation of CosmosClient Dispose API contract

### ISSUE THREAD

**Issue by oiqwrwer1** [Azure/azure-cosmos-dotnet-v3#3201]
This issue is to request that the conditions under which one should call CosmosClient.cs > Dispose() be documented in the API comments.
Context is that I am instantiating a new CosmosClient per rotated CosmosDB key/token but am not sure if it's fine to rely on GC to clean up the old CosmosClients or I need to call Dispose() explicitly.

I am not using the Singleton pattern which lets .NET handle CosmosClient.cs > Dispose() natively because from the documentation, it appears I need 1 CosmosClient per key/token.

**Comment by oiqwrwer1** [comment]
Relatedly, I'm confused about why the[ performance best practices doc](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips-dotnet-sdk-v3-sql?tabs=trace-net-core) recommends using CosmoClient as a singleton b/c CosmosDB key/token rotation seems like a security best practice and that necessitates a CosmosClient per key/token.

**Comment by ealsur** [comment]
As a general guidance, any class implementing IDisposable needs to be disposed when no longer user, if your application, for whatever reason, no longer needs the CosmosClient instance, then you can dispose it.

Why you would no longer need the CosmosClient? That's up to your business logic.

Ideally yes, you would have a Singleton instance for the lifetime of the application, if you use MSI authentication, there are no keys, so there is no rotation scenario. If you do use keys and you need to rotate, then sure, you can dispose the current client (because you no longer need it, following IDisposable usage) and create a new one in its place. It's still 1 active client, not 2.
