### ISSUE TITLE
Remove plural types and [] acessor

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#333]
- [x] Flatten plural types (CosmosDatabases & CosmosContaiers).
- [x] Remove statefull dictionary for databases and containers
- [x] [] indexer replaced by GetDatabase and GetContainer
- [x] Shortcut in client with GetContainer(dbName, containerName)
- [ ] Conflicts to GetConflicts() method

**Comment by kirankumarkolli** [comment]
CosmosClient is non-abstract & CosmosDatabases is abstract. 
CosmosClient needs to remain implementation to avoid Factory. 
CosmosDatabase[Core] implementation type would be used.

**Comment by j82w** [comment]
To add more context on this change we have gotten user feedback that the indexers have the following issues.
1. Hard to discover, and cause a big learning curve that requires looking at documentation
2. Goes against .NET standards since it is creating an object as part of the indexer operation. Most developers assume it is only a lookup.

Based on the above reasoning the SDK will be making the following changes.
1. Convert the indexer to Get methods (GetDatabase, GetContainer).
2. With the conversion to use Get methods plurals cause it to be to verbose
`this.client.Databases.GetDatabase("DbId").Containers.GetContainer("containerId");`
To fix this issue CosmosDatabases and CosmosContainers will be removed and merged with the parent resource.
`this.client.GetDatabase("DbId").GetContainer("containerId");`
Additional shortcut will be added to get the container reference
`this.client.GetContainer("DbId", "containerId");`

**Comment by kirankumarkolli** [comment]
Also [] are not intellisense friendly
