### ISSUE TITLE
Memory Leak in Comsos .net client

### ISSUE THREAD

**Issue by LastTribunal** [Azure/azure-cosmos-dotnet-v3#3356]
What a POS this .net cosmos client is (new and old).. The only way to run this this thing is as a singleton. Constant Instantiation will guarantee memory leak disasters in Prod, as I learned the hard way.
GC will not lean up, it will linger in Gen2 heap forever, till it blows up your server.

MS needs to either un'f the client and make it garbage collectable, or put a disclaimer about its use and potential destruction of your prod.
MS should compensate me and my org for suffering...

PS: the storage .net client doesn't suffer from the same sickness

![image](https://user-images.githubusercontent.com/4235993/180316665-443fd857-38d1-4a91-80ef-cec64bf605e6.png)

**Comment by ealsur** [comment]
Hi, thanks for your feedback. Could you please describe what is the intent of this Issue? 

Once a client is Disposed, the objects related to it are Disposed. If you are not Disposing the client instances and instead de-referencing them, that's a different case. The CosmosClient implements `IDisposable`, any class that implements `IDisposable` should be disposed once not used anymore.

Is your statement that after calling Dispose, there are objects that remain referenced or pinned for that client instance? Could you share evidence of this statement?

> Constant Instantiation will guarantee memory leak disasters in Prod, as I learned the hard way.

Our documentation across talks about why the CosmosClient should be a singleton (https://docs.microsoft.com/azure/cosmos-db/sql/performance-tips-dotnet-sdk-v3-sql, https://docs.microsoft.com/azure/cosmos-db/sql/best-practice-dotnet) and the technical documentation explains how connectivity works and how connections are reused (https://docs.microsoft.com/azure/cosmos-db/sql/sql-sdk-connection-modes#direct-mode, https://docs.microsoft.com/azure/cosmos-db/sql/conceptual-resilient-sdk-applications#client-instances-and-connections).

It is expected that if you are constantly creating new clients, memory will keep increasing and connections will keep increasing, TCP protocol keeps connections open (by default) permanently (https://docs.microsoft.com/azure/cosmos-db/sql/sql-sdk-connection-modes#volume-of-connections), which is different from the Storage client because they are different protocols (HTTP vs TCP). 

I'm sorry that the existing documentation is not clear enough, we'll try to be better. Could you please point us to which documentation you might have used so we can make sure it contains the correct guidance or if you used any sample application so we can make sure it contains proper usage examples?

**Comment by LastTribunal** [comment]
@ealsur looks like  somehow I wasnt disposing it correctly, even though I was using the `using()` statement.  Running with dispose() in a test console app, I could not replicate..
So I take back all the harsh words and stand corrected.

**Comment by bartelink** [comment]
Well I hope the lesson learned is (beyond the fact that SELECT is normally not broken and that this repo would fill with issues and dups of issues pretty quick if there was such a leak), is that you're best of practicing your nice voice in GitHub issues. If there is a particular documentation area you found insufficient that led you into this state, calling out a particular section and/or suggesting a rewording and/or addition of a line that might have saved you from going down the frustrating path you did would help future people in similar situations.

**Comment by ealsur** [comment]
@LastTribunal Thanks for closing the loop, glad you found the culprit!

As @bartelink points out, if you did follow some documentation or sample that put you in that situation, please let us know so we can fix it and avoid this problem for future users, your feedback is highly appreciated.
