### ISSUE TITLE
Why only retry for 503 ServiceUnavailable when there are multiple regions?

### ISSUE THREAD

**Issue by rmt2021** [Azure/azure-cosmos-dotnet-v3#3378]
I notice that Cosmos DB will only retry for error 503 (ServiceUnavailable) when there are multiple regions:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/b713ce4cb3e482175a8a6a9b8fc7051d9c7b5e91/Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs#L373-L378
 
Shouldn't it also retry when there is single region since the service may be back?  

**Describe the solution you'd like**
Also retry on the same region when 503 happens (at least for the read operation). 
For the second retry, we can mark the endpoint as unavailable.

**Additional context**
I notice that other Azure services would retry blindly on some transient error codes like 408, 429, 500, 503 etc.

**Comment by ealsur** [comment]
The SDK already retries on the region multiple times before generating the 503. Think of it like an onion. The ClientRetryPolicy is at the outer part.

References: 

* https://docs.microsoft.com/en-us/azure/cosmos-db/sql/conceptual-resilient-sdk-applications#timeouts-and-connectivity-related-failures-http-408503
* https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-sdk-availability#transient-connectivity-issues-on-tcp-protocol

Connectivity errors are retried on the transport layers, and if those errors keep happening through the retries, then the 503 bubbles up (or if this is a non-retriable scenario like Write Timeouts as explained in the article). Because we already exhausted all local retries, then the ClientRetryPolicy evaluates if cross-region retries can be done, and that can only happen if the account has multiple regions.

**Comment by rmt2021** [comment]
Thanks for your reply @ealsur !

So where can I find the transport layer retry implementation? 
I tried to find some clues in the repo, but didn't make it.

Could you please share some more details about the transport retry mechanism?

**Comment by rmt2021** [comment]
Hi @ealsur, is the code below related to the transport layer retry?

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/b713ce4cb3e482175a8a6a9b8fc7051d9c7b5e91/Microsoft.Azure.Cosmos/src/WebExceptionRetryPolicy.cs#L38-L43

However, I cannot find the `WebExceptionUtility.IsWebExceptionRetriable` in this repo or in another open-source .NET project, but I can find a Java implementation online:

https://jar-download.com/artifacts/com.microsoft.azure/azure-cosmos/3.2.0/source-code/com/azure/data/cosmos/internal/directconnectivity/WebExceptionUtility.java

**Comment by ealsur** [comment]
The code for the .NET TCP stack is not in this repo, it comes from `Microsoft.Azure.Cosmos.Direct` nuget dependency.

For Java, it would be:

* https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/ReplicatedResourceClient.java#L163-L170
* https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/TimeoutHelper.java
* https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/BackoffRetryUtility.java

**Comment by ealsur** [comment]
It retries TCP connectivity problems for read requests up to 30 seconds before bubbling the 503. For write requests there are no retries because write timeouts are not idempotent.

**Comment by rmt2021** [comment]
I see. I will take a deeper look at these.
Thanks a lot!!

**Comment by rmt2021** [comment]
Hi @ealsur, thanks again for offering these links. May I ask other questions related to the error code?

You mentioned that:
> The SDK already retries on the region multiple times before generating the 503. Think of it like an onion. The ClientRetryPolicy is at the outer part.

So I am wondering where the status code 503 is generated. Is it generated on the client side (e.g., in the SDK code)?
Or on the server-side? 
I think normally the status code 503 (service unavailable) should be returned from the server, right? Like the when the server is busy, it will return the client a 503.

But according to the link here: https://docs.microsoft.com/en-us/azure/cosmos-db/sql/troubleshoot-service-unavailable#client-side-transient-connectivity-issues
it seems that the "503" described there is still another type of timeout, and will throw a "TransportException" error.

Then what is the difference between 408 Timeout, 503 Service Unavailable, and 410 Gone?

**Comment by ealsur** [comment]
From your perspective, you only see 503 and 408, and should follow https://docs.microsoft.com/en-us/azure/cosmos-db/sql/conceptual-resilient-sdk-applications#timeouts-and-connectivity-related-failures-http-408503

Your application will never receive an exception with 410s in the newer (like this one) SDKs.

503s can be client-side generated (SDK on Direct mode facing connectivity errors due to backend endpoints unavailability) or can be server side (SDK on Gateway mode). In any case, from your perspective, it's the same. It means the local retries are not working for this operation. If the volume of 503s is high and it's affecting P99, then see https://docs.microsoft.com/en-us/azure/cosmos-db/sql/conceptual-resilient-sdk-applications#when-to-contact-customer-support

The mention to `TransportException` is a relic from older .NET SDKs. It means what I described earlier, there were connectivity errors locally (TransportException) and eventually it generated a 503.

**Comment by rmt2021** [comment]
BIG THANKS for your clarification!! @ealsur 

Then another question is: will there be a retry request for 503 in SDK if I use the **Gateway** mode? I didn't notice the built-in SDK retry implementation for the Gateway mode in the SDK.

When using Gateway mode, I tried to use a HTTP proxy (like Fiddler) to block the request for a while (e.g., 5 mins) or modify the response status code to 503 and then deliver to the client, but I cannot trigger/observe a retry request sent from the SDK.

Is it because the SDK will not retry when using Gateway mode, or is it because the retry happens in the transport layer so I cannot observe it in the HTTP proxy?

Thanks again!!! @ealsur

**Comment by ealsur** [comment]
As I mentioned, 503s can be client side generated (Direct mode TCP connectivity issues) or coming from the server side (SDK on Gateway mode).

The SDK retries transient connectivity issues that (first case) which would, if not resolved, generate the 503.

A 503 coming from Gateway is not a transient connectivity issue, it is a clear response from the service. In that case, the SDK would apply the 503 retry policy (attempt cross-region retry).

Transient HTTP connectivity issues surface as HTTP timeouts, and are also retried: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs assuming your proxy is making the .NET HttpClient generate timeout exceptions (reference https://github.com/Azure/azure-cosmos-dotnet-v3/blob/cda62eb42a563f7fea4eb0406fdc48bf7818a8ef/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L274).

**Comment by rmt2021** [comment]
This definitely solves my confusion! Thanks a lot! @ealsur
