### ISSUE TITLE
The Connection Mode is not work as the Code's setting.

### ISSUE THREAD

**Issue by qinqingxu** [Azure/azure-cosmos-dotnet-v3#3387]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I set the CosmosDB client to use the "Direct" mode.
But when I try to print the diagnostic log, I found it is still using the Gateway mode.

**To Reproduce**
Here is my code:
![image](https://user-images.githubusercontent.com/93512957/184916249-9be78c54-c3f4-4f02-bd49-95f64c3773dd.png)
And you can find the Diagnostic log show like:
![image](https://user-images.githubusercontent.com/93512957/184916712-ea06d751-f23b-411b-80d6-ffbf6425c416.png)

**Expected behavior**
The client shall use the "Direct" mode.

**Actual behavior**
The client is using the "Gateway" mode.

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos  3.29.0
OS Version (e.g. Windows, Linux, MacOSX):  Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment]
@imanvt could you take a look? This sounds related to https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3231

**Comment by imanvt** [comment]
Hi @qinqingxu, 

Setting the connection mode in the CosmosClientOptions to Direct mode will use Direct mode when possible. However, even when Direct mode is set, some operations will be performed using Gateway mode. I was only able to reproduce this behavior when performing an operation that requires HTTP calls, which are done in Gateway mode, rather than TCP (direct mode). I believe that the operation you are performing - "Typed FeedIterator ReadNextAsync" requires HTTP calls via Gateway mode. We can verify that this is true by seeing the HTTP 200 status shown in the GatewayCalls section of the diagnostics. 

Please see the relevant documentation: 
https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-sdk-connection-modes#routing
https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.cosmosdb.connectionmode?view=azure-java-legacy

**Comment by qinqingxu** [comment]
@imanvt So this is expected result, right?

**Comment by qinqingxu** [comment]
@imanvt Many thanks for your reply. Looking forward to your good news.  :)
