### ISSUE TITLE
Meta-data write operation routing to hub region

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#3408]
Meta data is about account/db/collection, its a system data NOT JSON documents that CX create. 
Currently meta data is served by Routing-Gateway.

Meta data has reads and writes. Writes will always be served from the hub/primary region. 
SDK supports automatic fail-over of region when it perceives region un-availability. In such scenarios the writes should be routed to the hub/primary region.

References: GlobalEndpointManager, ApplicationRegion, ApplicationPrefferedRegion are good starting exploring points.

**Comment by NaluTripician** [comment]
Attached are the http logs from the tests I ran regarding this issue: 

First I created a new database in the eastus region. Then I initiated a manual failover to centralus and while that was happening I started to create another database using the same client. As failover was still happening, the database was created in eastus. Finally using the same client I again created a new database which was written in centralus. 
[fiddler logs.zip](https://github.com/Azure/azure-cosmos-dotnet-v3/files/9560316/fiddler.logs.zip)

**Comment by NaluTripician** [comment]
In the issue, for multimaster accounts where the `LimitToEndpoint` flag is set to true and the endpoint is specified to the non-hub region, all metadata write operations will fail because we are trying to preform a write on a non-bub region that does not have access to the master partition.  The failure will be a 403.3 error and the current way the `ClientRetryPolicy` is set up, these metadata write operations will not retry as the `enableEndpointDiscovery` flag is set to false when `LimitToEndpoint` is true. In the `LocationCache`. If we were able to detect that the operation was a metadata write operation on a multimaster account and have the request retry when `enableEndpointDiscovery` is set to true, we would be able to find the hub region and the operation should succeed.
