### ISSUE TITLE
Upgrade resiliency

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#3409]
https://github.com/Azure/azure-sdk-for-java/issues/28266

**Comment by kundadebdatta** [comment]
**Background of the Problem Statement:** 

- Today, in the cosmos db .net sdk, we use fake/ dummy requests to check if the connection was made successfully to determine if a node is healthy vs unhealthy. Therefore, we only have two statuses of the nodes. When the service upgrade happens, the nodes forcefully closes all the open connections, and forces the SDK to re-establish the network connectivity. Re-establishing the connection takes additional time, thus increasing the overall latency. 

- Additionally, when a replica node goes through the upgrade, the Gateway Service should not send that node address as a response. However that's not the case and the so called "under the upgrade" node gets returned by the Gateway Service and our Address cache gets the un-healthy node in it. There are no validation currently present from the SDK side to validate if a node is currently undergoing through the upgrade.

**Solution Approaches:**

- Usage of RNTBD layer to establish connection: Today the .NET SDK uses fake connection to connect to the replica nodes. Instead of using the fake connections, we could use RNTBD layer in the direct connection (TCP based) to quickly open the connection stream.

- Replica Validation: Currently there are 2 states to validate the replicas. Introduce total 4 states (Unhealthy, Unhealthy-Pending, Unknown and Healthy) to clearly identify which replica node could the connection be made.

Tasks (To Do Items):

- [ ] Create the RN TBD Validation Model. 

- [ ] Replica Validation PR. (Unhealthy and UnHealthy Pending)

- [ ] Cold Start (Include Unknown Replicas for one specific Region).

- [ ] Connection State Listner.

**Comment by kirankumarkolli** [comment]
No dummy requests are sent. Part of connection creation context negotiation is different.
