### ISSUE TITLE
Use struct for data-contracts 

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/azure-cosmos-dotnet-v3#344]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ealsur** [comment]
For this, I want to first point to: https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct

> ✓ CONSIDER defining a struct instead of a class if instances of the type are small and commonly short-lived or are commonly embedded in other objects.

>X AVOID defining a struct unless the type has all of the following characteristics:
    It logically represents a single value, similar to primitive types (int, double, etc.).
    It has an instance size under 16 bytes.
    It is immutable.
    It will not have to be boxed frequently.

Since our "Settings" are also used for Update operations after a read and can potentially be larger than 16 bytes, what is the benefit or the goal of changing to struct?

**Comment by j82w** [comment]
Structs can't be mocked. Users will still be able to mock the method call and create an instance to return to the caller. The downside is users won't be able to verify what properties are being accessed or set.

**Comment by ealsur** [comment]
I kind of understand it if the goal is to avoid an instance being changed after first usage, but I think it doesn't pass the size test.
