### ISSUE TITLE
RU count differences (data explorer vs c# code)

### ISSUE THREAD

**Issue by drma-dev** [Azure/azure-cosmos-dotnet-v3#3464]
this my query executed in data explorer shows a RU of 2.95.
```
SELECT * FROM c where c.id="Profile:12345" and c.key="12345"
```
The same query executed in my C# code, returns a different value: 1.05
```
public async Task<T> Get<T>(string id, string partitionKeyValue, CancellationToken cancellationToken) where T : CosmosBase
{
    try
    {
        var response = await Container.ReadItemAsync<T>(id, new PartitionKey(partitionKeyValue), null, cancellationToken);

        if (response.RequestCharge > ru_limit_get) throw new NotificationException($"RU limit exceeded get ({response.RequestCharge})");

        return response.Resource;
    }
    catch (CosmosException ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
    {
        return null;
    }
}
```

is there a reason for this? am i doing something wrong?

**Comment by ealsur** [comment]
These are different operations.

The first one is a Query (Data Explorer). A Query can return any number of records.

The second one is a Point Read (C# SDK). A Point Read will always return 1 item or nothing (NotFound).

This is by design, they are simply different operations with different RU charges. 

More information: https://devblogs.microsoft.com/cosmosdb/point-reads-versus-queries/

**Comment by drma-dev** [comment]
@ealsur

thanks. now I get it. is there any way to do this point reads within the data explorer?

**Comment by ealsur** [comment]
I don't know, that would be a question to the team that creates that UI. My hunch is that a Point Read happens when you click on a document on the list after opening a container, but I don't know, this repository is just for the C# SDK, not Data Explorer.
