### ISSUE TITLE
PartitionKey constructor for types

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#354]
Ref: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/348

Instead of using a constructor for PartitionKey as object, add one for each supported type.

**Comment by j82w** [comment]
I think this is necessary for usability. Partition key only support some primitive types and can't handle complex objects. The only way to figure this out currently is run time exceptions. I think this also causes confusion for new users because they don't know what a partition key is and what they should be passing in.

**Comment by thomaslevesque** [comment]
I've been using Cosmos DB for a while, and it's the first time I learn that there are only a few valid types for partition keys. Is this documented anywhere?

**Comment by ealsur** [comment]
Not sure if it counts as covering all valid values, but the REST API documentation for "x-ms-documentdb-partitionkey" https://docs.microsoft.com/en-us/rest/api/cosmos-db/common-cosmosdb-rest-request-headers says it's an Array if valid values, and that same page seems to imply Number, Bool, and String are those.
