### ISSUE TITLE
PartitionKey implicit or explicit conversion

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#355]
Ref: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/348

Add an implicit conversion from object to a PartitionKey.

**Comment by j82w** [comment]
I wouldn't do implicit for object. It's going to lead to much confusion and errors. This could cause any property set to be used as a partition key like request options which just leads to run time exceptions.

Can we support only doing explicit or implicit for the specific types that are supported? That way we it causes compile time errors instead of run time exceptions. 

Should we provide an item identifier object? 
public class ItemIdentifier{
 string id;
 PartitionKey partitionKey;
}

**Comment by kirankumarkolli** [comment]
It leads to type ambiguity with neighbour parameters.
