### ISSUE TITLE
GetAccountPropertiesHelper.GetAccountPropertiesAsync should check empty

### ISSUE THREAD

**Issue by xieofxie** [Azure/azure-cosmos-dotnet-v3#3557]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**

It only checks `null` here https://github.com/Azure/azure-cosmos-dotnet-v3/blob/acd899e5c0be882c5e962103cc626ee8495a07a8/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L158

But the default `preferredLocations` is `new ObservableCollection<string>();` which is not null https://github.com/Azure/azure-cosmos-dotnet-v3/blob/acd899e5c0be882c5e962103cc626ee8495a07a8/Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs#L44

So when called in `GlobalEndpointManager`, we will always get all locations https://github.com/Azure/azure-cosmos-dotnet-v3/blob/acd899e5c0be882c5e962103cc626ee8495a07a8/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L560

We could check if it is empty to avoid this.

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment]
Could you please describe a bit more what is the problem being reported or what is the behavior that is affecting you?

`GetDatabaseAccountFromAnyLocationsAsync` receives the list of `PreferredLocations` and uses it as an enumerator:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/acd899e5c0be882c5e962103cc626ee8495a07a8/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L115-L128

Which is then used by `GetAccountPropertiesHelper`.

Yes, the `null` check is a no-op because it will never be null, but the enumerator is empty, so the final behavior is the same.

We still go to the Global endpoint first:

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/acd899e5c0be882c5e962103cc626ee8495a07a8/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L165-L176

If it suceeded, all done.

If this fails, and then because the enumerator is empty, the next code will do nothing and throw the error from the Global Endpoint attempt.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/acd899e5c0be882c5e962103cc626ee8495a07a8/Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs#L178-L185

**Comment by ealsur** [comment]
Please reopen clarifying the ask
