### ISSUE TITLE
ChangeFeedStartFrom.Time() seems to return malformed continuation tokens

### ISSUE THREAD

**Issue by MondQ** [Azure/azure-cosmos-dotnet-v3#3595]
**Describe the bug**
We have got a Cosmos database with four partitions and are reading the change feed with a `ChangeFeedIterator` using the `ChangeFeedStartFrom.Time` option, which returns a valid response (OK status code) but the resource collection is empty. The continuation token has four objects in the `continuation` array on the token. The `state` of one of them is of type `continuation` but the others are of type `time`.
Is that a bug?
This is the potentially malformed token: `{"V":2,"Rid":"*redacted*","Continuation":[{ "FeedRange":{"type":"Effective Partition Key Range","value":{"min":"05C1CFFFFFFFF8","max":"05C1DFFFFFFFF8"}},"State":{"type":"time","value":"2022-11-29T14:00:00.0000000Z"}},{ "FeedRange":{"type":"Effective Partition Key Range","value":{"min":"05C1DFFFFFFFF8","max":"05C1E7FFFFFFFA"}},"State":{"type":"time","value":"2022-11-29T14:00:00.0000000Z"}},{ "FeedRange":{"type":"Effective Partition Key Range","value":{"min":"05C1E7FFFFFFFA","max":"FF"}},"State":{"type":"time","value":"2022-11-29T14:00:00.0000000Z"}},{ "FeedRange":{"type":"Effective Partition Key Range","value":{"min":"","max":"05C1CFFFFFFFF8"}},"State":{"type":"continuation","value":"\"11622070\""}}]}`

When we use `ChangeFeedStartFrom.Beginning()` or `ChangeFeedStartFrom.Now()` all four states are of type `continuation` and everything works as expected.

IMPORTANT NOTE: `ChangeFeedStartFrom.Time` works when running it against a database with only one partition key.

**Expected behavior**
To get results from the change feed when using `ChangeFeedStartFrom.Time`.

**Environment summary**
SDK Version: 3.30.0 and 3.31.2 (tested both)
OS Version: Windows

**Comment by ealsur** [comment]
@MondQ Continuation is an opaque string and not meant to be parsed or interpreted.

Could you describe what is the wrong behavior of the library? Can you not continue reading the change feed with the continuation obtained from a call to `ReadNextAsync` after `StartFrom.Time`?

Or is your question, what does the information in the token mean?

**Comment by MondQ** [comment]
@ealsur Apologies if I wasn't clear enough.

When using StartFrom.Time we do not get any resources returned on the ReadNext response, and when using the continuation token obtained, we still do not get resources returned.
As mentioned we get an OK response but the resources collection is empty.

When using StartFrom.Now or StartFrom.Beginning, the behaviour is as expected and we get an OK response with resources populated, and the continuation token has all the feed ranges with the same type.

We had assumed that maybe the token was malformed for us when using StartFrom.Time due to the mixture of feed range types being "contuation" and "time"

But ultimately the problem is that the Resource Collection is empty for us when using StartFrom.Time.

**Comment by ealsur** [comment]
@MondQ This is part of the service behavior. Change Feed can return empty pages but if the response is an HTTP 200, it means further drains are required.

There are a couple of known cases for empty responses:

1. Using StartTime -> When the client sends the first request to a partition with the Start Time, the service returns an HTTP 200 response with no results as the first interaction. The reason is that the Change Feed continuation is an incremental transaction identifier, so the first request returns the incremental identifier that corresponds with the StartTime. Whether the results should be empty or not depends on service behavior and there is no setting on the client that can change that. 
2. Filtering by Partition Key -> See https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3017#issuecomment-1033082319. Also tied to service behavior.

I understand that an empty HTTP 200 goes against the expectations, and we can share this feedback with the team. Empty pages is also something that can happen for queries (reference https://learn.microsoft.com/azure/cosmos-db/nosql/query/pagination).

From the client perspective, the semantics for Change Feed remain the same though. If the response is an HTTP 200, it means there are more changes to be drained, if it's an HTTP 304, it means there is nothing new since the last time it was checked. This means that if you keep cycling until you get the HTTP 304, you should see your expected documents.

The token is not malformed and I would advice against attempting to parse or interpret it as the format is not a hard contract.

**Comment by MondQ** [comment]
Thank you. Knowing that we must expect empty responses and that the first call will yield no results is useful. It actually works, we just need to wait a few calls until we see results.

Thanks for your help.
