### ISSUE TITLE
Add a Stream overload for CosmosItems.CreateItemQueryAsStream

### ISSUE THREAD

**Issue by AndriySvyryd** [Azure/azure-cosmos-dotnet-v3#36]
Currently there are only overloads that accept a `string` or a `CosmosSqlQueryDefinition`.

**Comment by AndriySvyryd** [comment]
@j82w 

1. Consistency with other API like `CreateItemStreamAsync`
2. Control over how the parameters are serialized without having to replace `CosmosJsonSerializer`

**Comment by j82w** [comment]
The other APIs were done for performance reasons. With query the SDK does a lot of logic to figure out what partition to go to, and how to combine/sort the results for queries when the results are from multiple partitions. Since this logic is done in the SDK it would end up deserializing the stream that was just created, and would actually hurt the performance.

**Comment by vladrai** [comment]
We did some testing on a fairly large data (ended up with 100+ physical partitions). Cross partition query parts de-serialized on a client for ORDER-BY merge purposes required a lot of CPU + garbage, causing as a result GC to not be able to clean all used JSON serialization primitives leading to filling all the memory in addition to high CPU. This feature supposed to allow ORDER-BY query parts to be processed on client without complete de-serialization of query parts from partitions. Is my understanding correct here?

**Comment by j82w** [comment]
@vladrai the original post was about taking a stream as a input. The issue you are reporting is around how the SDK handles responses which has recently been completely overhauled to improve this scenario.  The SDK now only lazily deserializes the fields that are need instead of the entire object. Please take a look at the following PRs for more information.

1. https://github.com/Azure/azure-cosmos-dotnet-v3/pull/62
2. https://github.com/Azure/azure-cosmos-dotnet-v3/pull/66
3. https://github.com/Azure/azure-cosmos-dotnet-v3/pull/78

Please tryout the latest [3.0.0.9-Preview](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.0.0.9-preview) which should have all the changes.
