### ISSUE TITLE
Microsoft.Azure.Documents.ServiceUnavailableException is internal to Microsoft.Azure.Cosmos.Direct

### ISSUE THREAD

**Issue by avarnon** [Azure/azure-cosmos-dotnet-v3#3684]
**Is your feature request related to a problem? Please describe.**
We have the need to track when Microsoft.Azure.Documents.ServiceUnavailableException exceptions are thrown by the Cosmos DB SDK. Unfortunately it and its parent class, Microsoft.Azure.Documents.DocumentClientException, are internal to the Microsoft.Azure.Cosmos.Direct assembly. Furthermore, we really want to track the sub status code on the ServiceUnavailableException but the sub status code is a field on DocumentClientException and the Microsoft.Azure.Documents.SubStatusCodes enumeration is also internal to the Microsoft.Azure.Cosmos.Direct assembly.

**Describe the solution you'd like**
Is it possible to make ServiceUnavailableException, DocumentClientException, and SubStatusCodes public types while also making the sub status code on DocumentClientException a public property?

**Describe alternatives you've considered**
To get around this, we have to catch a plain Exception then use reflection to identify the exception as a ServiceUnavailableException then get its sub status code.

``` c#
try
{
    // ...
}
catch (Exception ex)
{
    var cosmosDirectAssembly = Assembly.Load("Microsoft.Azure.Cosmos.Direct");
    var typeOfServiceUnavailableException = cosmosDirectAssembly.GetType("Microsoft.Azure.Documents.ServiceUnavailableException", false);
    var typeOfCosmosSubStatusCodes = cosmosDirectAssembly.GetType("Microsoft.Azure.Documents.SubStatusCodes", false);
    var typeOfNullableCosmosSubStatusCodes = typeof(Nullable<>).MakeGenericType(typeOfCosmosSubStatusCodes);
    var typeOfDocumentClientException = cosmosDirectAssembly.GetType("Microsoft.Azure.Documents.DocumentClientException", false);
    var serviceUnavailableExceptionSubStatusCode = typeOfDocumentClientException
                    .GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                    .FirstOrDefault(p => p.FieldType == typeOfNullableCosmosSubStatusCodes);

    if (ex.GetType() == typeOfServiceUnavailableException)
    {
        var subStatusCode = serviceUnavailableExceptionSubStatusCode.GetValue(ex);
        // Log the substatus code
    }
}
```

**Comment by ealsur** [comment]
`Microsoft.Azure.Documents.ServiceUnavailableException` is not thrown by the SDK.

They are all `CosmosException`.

Please see: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Exceptions.md#typed-apis

If you have evidence of a `Microsoft.Azure.Documents.ServiceUnavailableException` being thrown to the application, please reopen this Issue with the full stack trace and exception's `ToString()`

**Comment by ohads-MSFT** [comment]
@ealsur 

1. `ServiceUnavailableException` and other `DocumentClientException` derived exceptions might not be thrown directly by the SDK, but they are included as inner exceptions of `CosmosException` - for example `GoneException`. IMHO it's inconsistent to have an internal-typed inner exception of a publicly-typed thrown one.
2. `CosmosException` contains a public `SubStatusCode` property, whose value would be some `Microsoft.Azure.Documents.SubStatusCodes` which is internal. So again, the same inconsistency where you expose internal-typed information in a publicly-typed exception.

The stack trace below demonstrates both points above:

> **Microsoft.Azure.Cosmos.CosmosException** : Response status code does not indicate success: ServiceUnavailable (503); **Substatus: 0**; ActivityId: xxxxx-xxxx-xxxx-xxxx-xxxxxxx; Reason: (Service is currently unavailable. More info: https://aka.ms/cosmosdb-tsg-service-unavailable
ActivityId: xxxxx-xxxx-xxxx-xxxx-xxxxxxx, Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, Linux/2.0 cosmos-netstandard-sdk/3.22.2);
 **---> Microsoft.Azure.Documents.GoneException**: The requested resource is no longer available at the server.
ActivityId: xxxxx-xxxx-xxxx-xxxx-xxxxxxx, Linux/2.0 cosmos-netstandard-sdk/3.22.2
   at Microsoft.Azure.Documents.TimeoutHelper.ThrowGoneIfElapsed()
   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicasInternalAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)
   at Microsoft.Azure.Documents.StoreReader.ReadMultipleReplicaAsync(DocumentServiceRequest entity, Boolean includePrimary, Int32 replicaCountToRead, Boolean requiresValidLsn, Boolean useSessionToken, ReadMode readMode, Boolean checkMinLSN, Boolean forceReadAll)
   at Microsoft.Azure.Documents.QuorumReader.ReadQuorumAsync(DocumentServiceRequest entity, Int32 readQuorum, Boolean includePrimary, ReadMode readMode)
   at Microsoft.Azure.Documents.QuorumReader.ReadStrongAsync(DocumentServiceRequest entity, Int32 readQuorumValue, ReadMode readMode)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass31_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy, Func`2 prepareRequestAsyncDelegate)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)

**Comment by ealsur** [comment]
@ohads-MSFT  I don't understand the intent of your comment.

The OP asked how to detect the ServiceUnavailable error, to which the answer is, in V3 SDK, there is no specific exception, just catch the `CosmosException` and match the StatusCode. That completes the requirement. There is no need to dig into the InnerExceptions to achieve this.

1. Sure, there might be other internal exceptions but what is the problem with that? If your intent is to detect a Service Unavailable exception, you simply use the CosmosException and get the Status 503. Which exactly is your use case that you require identifying the Inner Exceptions?
2. The `CosmosException` exposes the headers returned in the service response through the `Headers` property. If you want to read the substatus, you can use `Headers["x-ms-substatus"]`. Which is the use case where you need the substatus to programmatically action on the error?

**Comment by ohads-MSFT** [comment]
@ealsur 

1. I don't have a specific use case in mind, but for example it might be interesting to check `GoneException::LocalIp` or one of the `DocumentClientException` properties that aren't exposed on the `CosmosException` (e.g. `StatusDescription`).
2. Getting the substatus is not the issue, indeed I have it under the public `CosmosException::SubStatusCode`. As you mentioned, the issue is acting upon it programmatically, namely comparing the substatus to some known values in the currently `internal` enum `SubStatusCodes`. I imagine there might be various use cases, but if I were to speak to ours, it's for detecting client-side issues specifically (e.g. `TimeoutGenerated410`). For example, we might to translate these into other HTTP responses back to the original caller (e.g. 429).

**Comment by ealsur** [comment]
1. If there are any properties that you require access, please let us know and we'll help understand how you can access them. Why do you need to check for GoneExceptions? It is an internal type and was not even public on V2 SDK (so it is not a migration gap), giving access just for the sake of access?
2. If the intent is to propagate to the original caller, then you can simply propagate all Headers, that should be the correct thing, because you don't know which header the caller is interested on. Maybe the caller wants to know the Session Token. So in that scenario, just iterate over the Headers and add them to the response, for example: https://github.com/ealsur/ondotnet-cosmosdb/blob/master/src/episode1/streams/Controllers/ItemsController.cs#L40-L57. For 503 troubleshooting, there is nothing you can programmatically do based on the substatus. If its 20001 or 20002, there is no code you can change to act on it, in both cases, you are experiencing connectivity issues, the recommendation for both is the same for your application: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/conceptual-resilient-sdk-applications#timeouts-and-connectivity-related-failures-http-408503. Now, if the volume of these 503s [exceeds the expectations](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/conceptual-resilient-sdk-applications#when-to-contact-customer-support) yes, the Substatus and **the entire Diagnostics** help root causing, but fixing the issue is not something the application, from code, can do, it's someone who is diagnosing the details that needs to act on it.

I want to reiterate, if the use case is there, we will help either making the information accessible through public methods or properties if it's not or helping with how you can obtain it from the current public methods. But there should be a use case for it, there should be value in exposing that.

Everything described in this thread so far is achievable through the current public surface API.
