### ISSUE TITLE
SDK Does Not Respect Configured Timeout

### ISSUE THREAD

**Issue by Jasen-Quadras** [Azure/azure-cosmos-dotnet-v3#3701]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
In the case of ServiceUnavailable (503) error when querying database, the SDK doesn't respect the configured timeout. Timeout is configured during client initialization using CosmosClientOptions.RequestTimeout property.

`CosmosClientOptions cosmosClientOptions = new CosmosClientOptions()
            {
                RequestTimeout = 500
            };`

**To Reproduce**

**Expected behavior**
SDK should terminate the call and return control to the caller once request time exceeds the configured timeout.

**Actual behavior**
SDK doesn't terminate the call and blocks the caller for much more time than what it is configured during client initialization.

**Environment summary**
SDK Version: cosmos-netstandard-sdk/3.23.1
OS Version Windows/10.0.17763 

**Additional context**
[cosmosDbClientLogs.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/10696011/cosmosDbClientLogs.txt)

**Comment by ealsur** [comment]
@aavasthy Can you take a look at the attached diagnostics and reply to this question?

**Comment by aavasthy** [comment]
@Jasen-Quadras 
"RequestTimeout" determines the maximum response time from the server for a single request. It is specified as 500ms in clientOptions. ClientOptions also has "OpenTCPConnectionTimeout" that determines the maximum amount of time a client will wait to establish a new TCP connection to the server. This is 5 seconds by default if not specified otherwise. From the diagnostic log that is shared above, "ChannelAcquisitionStarted" event failed that means the TCP connection was not even established. So it was the 5 seconds "OpenTCPConnectionTimeout" that threw the timeout error and not "RequestTimeout".

**Comment by Jasen-Quadras** [comment]
@aavasthy, that means in 5 seconds the caller should have received an exception. But that did not happen. As you can see in the log, the request was blocked for at least 35 seconds (It may have been more than this).

**Comment by aavasthy** [comment]
> @aavasthy, that means in 5 seconds the caller should have received an exception. But that did not happen. As you can see in the log, the request was blocked for at least 35 seconds (It may have been more than this).

@Jasen-Quadras when you say at least 35s(2100 ms) are you mentioning the total "duration in milliseconds":34491.8583 that we see in the summary diagnostics?

**Comment by Jasen-Quadras** [comment]
@aavasthy, yes.

**Comment by aavasthy** [comment]
The total "duration in milliseconds":34491.8583 that we see in the summary diagnostics includes the processing time of other requests that didn't encounter the timeout error.

**Comment by ealsur** [comment]
Closing as the questions have been answered, thanks @aavasthy.
