### ISSUE TITLE
GROUP BY query with OFFSET AND LIMIT only returning 1000 results, cant paginate for more

### ISSUE THREAD

**Issue by keerthiadu** [Azure/azure-cosmos-dotnet-v3#3849]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I'm using a simple group by statement that is something like

"SELECT root.name , MAX(root.version) AS version FROM root WHERE root.partitionKey = "some-guid" GROUP BY root.name  OFFSET 0 LIMIT 255"

I paginate for more results using offset and limit parameters

I know that there are more than **1200** documents that have unique root.name.

for fetching page 1 , I issued this query

"SELECT root.name , MAX(root.version) AS version FROM root WHERE root.partitionKey = "some-guid" GROUP BY root.name  OFFSET **0** LIMIT **255**"

I got **255** results, and for fetching the second page, I issued this query

"SELECT root.name , MAX(root.version) AS version FROM root WHERE root.partitionKey = "some-guid" GROUP BY root.name  OFFSET **255** LIMIT **255**"

I got **255** results, and for fetching the third page, I issued this query

"SELECT root.name , MAX(root.version) AS version FROM root WHERE root.partitionKey = "some-guid" GROUP BY root.name  OFFSET **510** LIMIT **255**"

I got **255** results, and for fetching the next page, I issued this query

"SELECT root.name , MAX(root.version) AS version FROM root WHERE root.partitionKey = "some-guid" GROUP BY root.name  OFFSET **765** LIMIT **255**"

this time I got **235** results but not **255** as expected. 

and If I fetch for next page
"SELECT root.name , MAX(root.version) AS version FROM root WHERE root.partitionKey = "some-guid" GROUP BY root.name  OFFSET **1000** LIMIT **255**"
it returns empty results.

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

**Expected behavior**
All matching results must be retrievable using OFFSET and LIMIT params.

**Actual behavior**
Only 1000 results can be fetched.
**Environment summary**
SDK Version:v3.26.2.0  Microsoft.Azure.Cosmos.Client
OS Version (e.g. Windows, Linux, MacOSX) Windows

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).
QueryRequestOptions.MaxItemCount  is not set when making the requests.

Setting the QueryRequestOptions.MaxItemCount to **-1** works as expected.

Setting the QueryRequestOptions.MaxItemCount to **255** doesn't work. I only returns first 255 results, and paging for more returns empty.

**Comment by adityasa** [comment]
@keerthiadu
Given the by design behavior explained in #3626 above, here are a few things to check:
1. whether collection actually has the correct number of documents. This can be done by running a COUNT(1) query with same filter without specifying offset limit.
2. whether pagination is being handled correctly and continuation token is drained properly (especially since the last response may be return a continuation). If you can share the application code we can help verify.

If you can repro the issue in a unit test using a sample data, that would be best.
If the issue reproduces only on your dataset, consider opening a support ticket with relevant information (account name, query activity ids etc).
