### ISSUE TITLE
Allow Client Encryption Keys to be deleted from a database, or remove the limit of Client Encryption Keys that can be stored in a database

### ISSUE THREAD

**Issue by aperiooculus** [Azure/azure-cosmos-dotnet-v3#3894]
**Is your feature request related to a problem? Please describe.**
I've recently encountered an issue around Cosmos Client Encryption Keys where I have reached the limit on a single database.

Background:
I'm implementing an encryption service that rotates the client data encryption keys (DEK). The method of rotating the keys involves creating a new container along with a new DEK, then copying the records to the new container.
In my testing I encountered a 403 response when calling Database.CreateClientEncryptionKeyAsync to create a new DEK, indicating - I believe - that the database is at max capacity for DEKs. I haven't yet found a means to remove the keys, and therein lies my challenge.

**Describe the solution you'd like**
A method to delete a client encryption key that is no longer in use, OR remove the limit of client encryption keys that can be stored in a database

**Describe alternatives you've considered**
Instead of migrating the data to a new container in the same database, I can create a new database and migrate the data into a container within the new database.

**Additional context**
Here is a small portion of the Response Body from Cosmos when the limit is reached:

`Message: {\"Errors\":[\"Storage quota for 'ClientEncryptionKey' exceeded.\"]}`

**Comment by ealsur** [comment]
@kr-santosh Could you take a look at this request?

**Comment by kr-santosh** [comment]
@aperiooculus Thank you for writing to us.

- We don't intend to provide a support to delete the keys. This could result in irreversible data loss. If a customer mistakenly deletes an encryption key, the associated encrypted data becomes inaccessible and unreadable. Restricting key deletion helps prevent unintentional data loss due to human error or malicious actions.  Users can delete the database and recreate it with same name if the data it contains is either completely deleted or is not required anymore.
- We currently have a limit on the number of keys that can be created per database, which is 20 keys. Is this need for more keys arising because of a need to rotate the Data Encryption Key? 

Could you please provide the reason to rotate the DEK. We support rotating the customer key. We would like to know more about the use case for rotating the data encryption key.

**Comment by aperiooculus** [comment]
@kr-santosh Thank you for the quick response. 

I am working on getting some clarification from our Security Team on the need for this requirement. As soon as I have the clarification, I will provide it.
