### ISSUE TITLE
Transaction Batch not returning expected results when using Hierarchical Partition Keys

### ISSUE THREAD

**Issue by developerxnz** [Azure/azure-cosmos-dotnet-v3#3919]
**Describe the bug**
I have tested a scenario using Hierarchical Partition Keys configuring a container using all 3 levels.
I set up a transaction batch providing a Partition Key with only the first Partition Key level. 

Added two documents using "CreateItem", with the same Partition Key values.

After calling "ExecuteAsync", the batch response returns with a StatusCode of Ok and no ErrorMessage. 
The returned two operations have a StatusCode of -1 and a SubStatusCode of Uknown. 

**To Reproduce**
https://gist.github.com/developerxnz/5580f809c4f26ab8568f264d735771f5

**Expected behavior**
Transactional Batch Response status code to not be "Ok".

**Actual behavior**
Transactional Batch Response StatusCode returns "Ok".

**Environment summary**
SDK Version: 3.34.0
OS Version: MacOSX

**Additional context**
This was just for testing some weird scenarios with the new "Hierarchical Partition Keys" feature.

**Comment by ealsur** [comment]
@developerxnz Was this against the Emulator or a real account?

**Comment by developerxnz** [comment]
I tried both.

**Comment by ealsur** [comment]
@developerxnz I'm routing/reaching out to the service team to report this, the fact that the service response is an Ok with -1 status on the items sounds wrong

**Comment by developerxnz** [comment]
Any updates?

**Comment by ealsur** [comment]
See https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3930

**Comment by EstherSY** [comment]
Hello, 

It appears that the batch transaction does not work with the container with the hierarchical partition keys.   Any updates?

**Comment by NaluTripician** [comment]
Hello, the problem here is the use of prefix partition keys. In the example you provided, you are creating items and specifying the prefix as the partition key for the `TransctionalBatch` for creating the items. However, prefix partition keys can only be used in queries, not point operations. For further information please see [this document](https://learn.microsoft.com/en-us/azure/cosmos-db/hierarchical-partition-keys?tabs=net-v3%2Cbicep#choose-your-hierarchical-partition-keys) about hierarchical partition keys. Closing this issue for now but if you have any other questions please feel free to reopen it, hope this helps.

**Comment by jdaaboul** [comment]
Not sure why this is closed, the issue remains with a status code of OK when the batch did not go through
