### ISSUE TITLE
Detecting Physical Partition split in cosmos DB V3

### ISSUE THREAD

**Issue by albertofori** [Azure/azure-cosmos-dotnet-v3#4014]
## Background
I have some questions concerning using change feed queries in cosmos DB v3 SDK. 

We currently plan to use persisted feed range/continuation token in our leases and want to know how best to deal with feed range splits. From my understanding, an existing continuation token should still be valid for the specified feed range in the token even if the Feed range has split since this is an arbitrary range that could either span a physical partition or a logical partition. (Correct me if I'm wrong).  

## My ask
I would want to know the best way to re-map feed ranges and replace the continuation token when a split occurs since there might be no way to detect that the Feed range for the rented leases has now been split. 

Any help that I could get on this could be highly appreciated.

**Comment by bartelink** [comment]
What's wrong with using the existing impl in the box - what unique value are you intending to offer to offset the work involved in writing, debugging and maintaining what you are doing?

**Comment by albertofori** [comment]
> What's wrong with using the existing impl in the box - what unique value are you intending to offer to offset the work involved in writing, debugging and maintaining what you are doing?
@bartelink We currently use a custom solution with composite leases tracking different collections whose change feeds need to be processed in a coordinated manner. This solution already exists and is being used in V2 so the work has already been done. We just need to move  from using V2 continuation tokens and partition key ranges to feed range and V3 continuation tokens.

**Comment by albertofori** [comment]
> Please see: #2759
> 
> Currently there is no way to detect a split with a running iterator because the iterator itself is split-proof.
> 
> Could you explain what is the need for this "re-map"? You could certainly call GetFeedRanges again and restart the feed using a timestamp if you really wanted to re-distribute the entire FeedRange list again, but I am not clear on exactly why you'd do that.

@ealsur Since our degree of parallelism depends on the number of partitions (in V2), writing to a partition that no more exists would fail and we handle this failure to enable us stop using non-existent partitions and then check for new partitions to process. This would not happen in V3 since the feedrange will still be valid. assuming FeedRange "a" splits into "b" and "c". New lease processors will pick up and create leases for feed ranges "b" and "c" but "a" will also still be running as expected. That means we will be processing the same slices of a container more than once without any way to detect that feedrange "a" has been split. I agree periodically querying the feed ranges to redistribute the load might be one way of doing this, albeit not ideal. I wanted to just confirm if there is no other way of doing this natively in the V3 library.

Thanks!

**Comment by ealsur** [comment]
@albertofori Thanks for the clarification. As you correctly said, V3 won't throw an exception, because the FeedRange is still valid, so the machine using that FeedRange through the Continuation will continue to succeed, this time, reading "b" and "c" transparently.
What is the need to detect the split? Do you run into resource contention on the machine at some point because it is processing potentially more items (assuming events are evenly distributed across physical partitions)?

I am just trying to understand if the ask is just because this is how it was done in V2 and you'd like a full apples-to-apples or there is a reason for the scale-out support. In V2 you had no choice, because simply the API forced you to provide a valid PartitionKeyRangeId, so you had to build something that handled splits, but now you don't need that.

**Comment by albertofori** [comment]
> @albertofori Thanks for the clarification. As you correctly said, V3 won't throw an exception, because the FeedRange is still valid, so the machine using that FeedRange through the Continuation will continue to succeed, this time, reading "b" and "c" transparently. What is the need to detect the split? Do you run into resource contention on the machine at some point because it is processing potentially more items (assuming events are evenly distributed across physical partitions)?
> 
> I am just trying to understand if the ask is just because this is how it was done in V2 and you'd like a full apples-to-apples or there is a reason for the scale-out support. In V2 you had no choice, because simply the API forced you to provide a valid PartitionKeyRangeId, so you had to build something that handled splits, but now you don't need that.

@ealsur So in V2, we could say we were handling the split error and taking advantage of that to detect a split and stop using a lease that corresponds to a now non-existent partition. Our lease processing actions are idempotent, so we don't worry about duplicates, but we are assured that no two workers are processing the same set of changes. 
The main ask was whether there was any in-built functionality/behavior in V3 that we could use in place of this before going ahead to implement our own checks and lease re-assignment logic. I understand that the split errors had its drawbacks, and an arbitrary range makes changefeed queries more convenient. It just so happens that we found a way to sort of make this useful to us 😂

**Comment by ealsur** [comment]
I'm sorry but I still don't understand why you need the split mechanics or why you need to re-assign the lease.
There is no way for 2 workers to be handling the same set of changes and no possibility of duplicity.

Let's say you have 2 Workers (A and B), and A is processing FeedRange 0 and B is processing FeedRange 1. There is no duplicity, because each FeedRange is a different part of the Container.

FeedRange 0 represents Partition 0 that at some point splits into 2 and 3. But FeedRange 0, which is represented in the Continuation, is still valid.
So my 2 workers A and B, will continue to process their respective leases/Continuations, each one representing a part of the Container that does not overlap with the other.

The different between V2 and V3 is that in V2, you **had** to create new leases for Partitions 2 and 3 and each one have a different Continuation, so you had to re-assign and see which worker now will grab the child partitions to process.
With V3, you don't have to, the existing workers, with the existing Continuations, will continue to process, and you are still assured no two workers are processing the same set of changes because each FeedRange/Continuation does not overlap.

Simply stated, with V3, you do not need any re-assignment logic or anything to detect splits, your logic is now simpler, you just GetFeedRanges, distribute/create leases, and they will forever continue working.

**Comment by albertofori** [comment]
@ealsur Got it! Thank you very much! 👍

**Comment by ealsur** [comment]
Closing as answered
