### ISSUE TITLE
Question about change feed pull api continuation tokens

### ISSUE THREAD

**Issue by v4karuna** [Azure/azure-cosmos-dotnet-v3#4060]
I would like to use the change feed pull model with a custom orchestrator and process the data in parallel per feed range.

Lets say `worker A` accepted a feed range parameter `feedRangeId: 1` and calls the change feed iterator to get the first page of 100 results:
```
var feedIterator = cosmosClient.GetContainer(databaseId, collectionName).GetChangeFeedIterator<Document>(
    ChangeFeedStartFrom.Beginning(FeedRange.FromJsonString(feedRangeId)),
    ChangeFeedMode.LatestVersion,
    changeFeedRequestOptions: new ChangeFeedRequestOptions
    {
        PageSizeHint = 100,
    });

// return continuationToken after processing results from above
```

After processing the 100 documents, `worker A` returns the continuation token back to the orchestrator. The orchestrator then calls `worker B` with the continuation token returned from above.

```
// uses continuation token instead of starting from the beginning

var feedIterator = cosmosClient.GetContainer(databaseId, collectionName).GetChangeFeedIterator<Document>(
    ChangeFeedStartFrom.ContinuationToken(continuationToken),
    ChangeFeedMode.LatestVersion,
    changeFeedRequestOptions: new ChangeFeedRequestOptions
    {
        PageSizeHint = 100,
    });
```

**The question**

Would the change feed iterator in `worker B` know only to get changes from `feedRangeId: 1`? Is this information persisted in the continuation token returned from `worker A`?

Or would this result in getting changes from cross-partitions?

Is there another way to process changes for a given feed range with support for continuation?

Thanks :)

**Comment by ealsur** [comment]
@philipthomas-MSFT Could you take a look at this question?

**Comment by philipthomas-MSFT** [comment]
Hello @v4karuna 

Thanks for reaching out to us and thanks for using the Cosmos DB SDK .NET.
Let me repeat your question, and I will follow up with an answer.

"Would the change feed iterator in `worker B` know only to get changes from `feedRangeId: 1`?* Correct. using the continuation token of 'worker A' will only yield feed items for 'feedRangeId 1' for `worker B`.

"Is this information persisted in the continuation token returned from `worker A`? Absolutely. The continuation token contains the feed range's type and value as well as the state in order to yield the desired feed items.

"Or would this result in getting changes from cross-partitions?" No, this is not a possibility.

"Is there another way to process changes for a given feed range with support for continuation?" Your scenario and solution to said scenario is sufficient to accomplish your needs. I do not believe there is an exhaustive list of solutions to this scenario. Every customer is different and is free to try different solutions to cater to their needs. We encourage creativity but we will always make efforts to guide the customer to the most optimal solutions.

Thanks again for your time.

**Comment by v4karuna** [comment]
Thank You :)
