### ISSUE TITLE
V3 SDK with bulk execution performs worse than V2 SDK using BulkExecutor

### ISSUE THREAD

**Issue by gonzaleznicolas** [Azure/azure-cosmos-dotnet-v3#4083]
**Describe the bug**
When upserting documents to a manual throughput container, the V3 .NET SDK performs consistently worse than the V2 SDK using the bulk executor.

Not only is it slower, but it also frequently throws a CosmosException with the status code TooManyRequests.

**To Reproduce**
See this minimalistic [sample project](https://github.com/gonzaleznicolas/Cosmos_v2_vs_v3_SDK).

Run it while running the cosmos DB emulator with rate limiting enabled. The sample project will create a test database and container.

Alternatively, change the accountEndpoint and accountKey to point at a live cosmos account, and observe the same behavior.

**Expected behavior**
I would expect the V3 SDK to perform at least as well as the V2 SDK.

**Actual behavior**
The V3 SDK is slower, and often throws a CosmosException with the status code TooManyRequests.

**Environment summary**
SDK Version: 3.35.3
OS Version: Windows 11

**Comment by FabianMeiswinkel** [comment]
Hi @gonzaleznicolas,
 I have two questions glancing at your sample code.
1) What is the intent of using Parallel.ForEach when "enqueueing" the async tasks? This kind of creates an artificial lock contention - the call to UpsertItemAsync because not awaited is synchronous without any I/O operations and will be very quick. Usually I would expect the "enqueueing" of the async tasks to haven sequentially on a single thread into a List that doesn't need to be any of the Concurrent lists - will avoid the lock contention and the Parallel.ForEach won't help you much anyway.

2) Usually when doing bulk processing the 429-retry policy gets configured to retry forever - the main goal of bulk is to saturate the throughput - so, throttling from the backend is kind of wanted - and so, allowing retries longer than the default policy of at most 9 retires in at most 30 seconds is often preferred. You can change the max. retry attempts to a higher number here - https://github.com/Azure/azure-cosmos-dotnet-v3/blob/391c3d9872aff6615c00dffaa313aaa7013b69a0/Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs#L282-L332

**Comment by FabianMeiswinkel** [comment]
Last comment - usage of bulk really is an improvement to keep saturating the provisioned throughput (RU/s) - when just updating very small number of documents, bulk can result in higher latency. The background is that in bulk mode the client will enqueue updates per physical partition and only send them to the backend in a bulk request after 100ms - or when the number of documents reaches a certain size. So, when you update very small number of documents in Bulk mode, the latency might actually be a bit higher. Bulk Mode is meant to optimize for throughput - not best latency when doing point operations or update very small number of documents.

**Comment by FabianMeiswinkel** [comment]
This is also summarized here: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-migrate-from-bulk-executor-library

**Comment by gonzaleznicolas** [comment]
Hi @FabianMeiswinkel. Thank you for your prompt reply.

I have addressed your recommendations on the updated [repository](https://github.com/gonzaleznicolas/Cosmos_v2_vs_v3_SDK).

Regarding the Parallel.ForEach, I removed it.

Regarding the retry policy, I did what you suggested and increased the MaxRetryAttemptsOnRateLimitedRequests, and MaxRetryWaitTimeOnRateLimitedRequests. That solved the "TooManyRequests" cosmos exception. It is no longer thrown.

However, the V3 SDK still takes consistently longer than the S2 SDK to perform the exact same upsert operation.

To address your last point, I increased the number of documents significantly (and also the provisioned throughput of the container). I did this so that we are no longer talking about a "very small number of documents". And still, I see the V3 SDK taking about twice as long as the V2 SDK to perform the bulk upsert.

I also tried setting the V3 SDK to "AllowBulkExecution = false" (with the smaller amount of documents), but that made it even slower.

As an experiment, I set the container's throughput to autoscale. In this scenario, the V3 SDK does perform very well. Which is in line with your statement that "usage of bulk really is an improvement to keep saturating the provisioned throughput (RU/s)".

However, what I need is to upsert the documents that I need to upsert _as quickly as possible with the manually provisioned throughput of my container_. And it seems that the V2 BulkExecutor does a much better job of throttling itself than the V3 SDK. So is that something that the V3 SDK is just not capable of? Or do you have any further suggestions?
