### ISSUE TITLE
Reduce PartitionKey allocations

### ISSUE THREAD

**Issue by AndriySvyryd** [Azure/azure-cosmos-dotnet-v3#409]
The current design of the API leads to 2 extra objects being allocated for every call that takes a partition key when using a non-string value:

1. A new instance of `PartitionKey`.
2. Boxing of the value.

One way of avoiding these would be by making `PartitionKey` a generic struct.
Alternatively the overloads that take a `string` instead of `PartitionKey` could be added back.

**Comment by j82w** [comment]
The PartitionKey is about getting the correct public contract. We will optimize the operations once we are sure it won't change. 

How do you feel about implicit conversions?
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/355

**Comment by AndriySvyryd** [comment]
This problem is in the contract itself, so fixing it would require changing the contract.

Implicit conversions don't help.

Constructor overloads would mitigate the second point if you converted the value to a string before storing it.

**Comment by j82w** [comment]
Partition Key currently only supports string, double, bool, null, and undefined. 

We got a lot of feedback from users that object caused them a lot of issues. 
- Confusion on what types were actually supported
- Lots of run time exceptions (invalid types, accidentally having request options passed into PK)

Having a generic struct will just cause the same confusion as object did.

We decided to go with a Partition Key class. This allowed strict type checking to avoid all the run time exceptions. It is one additional object, but it's necessary to support the 5 different types. Otherwise we would have to have 5 overloads for every item method, and this would just cause the API surface area to explode.

**Comment by AndriySvyryd** [comment]
It can be a non-generic struct. Eventually the key value will need to be converted to a string. So as long as it's stored as a string there would be no boxing.

The latter is implementation detail so it can be fixed post RTM. But making `PartitionKey` a struct would be a breaking change, so it's best to do ASAP.

**Comment by j82w** [comment]
Is your only issue that it is a class instead of a struct? Can you possibly provide an example just to make sure there is no misunderstanding?

PartitionKey get's converted to different values depending on the connection. For Direct Mode it actually get's converted into a hash, and for Gateway Mode it is a JSON string.

**Comment by AndriySvyryd** [comment]
As I said there are two issues. One of them is that `PartitionKey` parameter in the public API is not a struct. I don't know what example would you like to see. The usage wouldn't change if it's made into a struct.

The other issue is that the value passed to the `PartitionKey` constructor is boxed when it's stored. This is a smaller issue as it only affects the value type overloads. Also this and other allocations can be fixed later, whenever you do a perf pass.

**Comment by j82w** [comment]
The only problem I see with using a struct is Partition key has a limit of [2048 bytes](https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-item-limits), and it's not recommended to use a struct if the size is over [16 bytes](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct)

**Comment by AndriySvyryd** [comment]
Oh you can just declare it as `readonly` and use an [`in` modifier](https://docs.microsoft.com/en-us/dotnet/csharp/write-safe-efficient-code) on the parameter to avoid defensive copying.

**Comment by kirankumarkolli** [comment]
@AndriySvyryd thanks for the feedback.

PartitionKey as struct makes sense, it enables non--breaking optimization later. 
Current cosmos wire contract is we could only avoid one object heap allocation. 

Generic struct vs overloaded CTOR: Usability is one concern that needs attention for generic structs. We could explore using generic's as optimization underneath with overloaded CTOR as contract.

**Comment by AndriySvyryd** [comment]
Should I open an issue to track further optimizations or you are tracking them elsewhere?
