### ISSUE TITLE
Migrating from Azure Cosmos SDK v2 (DocumentClient) to Azure Cosmos SDK v3 (CosmosClient) results in a significant increase in throttling (429s) and normalized RU consumption for a highly partitioned container

### ISSUE THREAD

**Issue by elimetzlerprieb** [Azure/azure-cosmos-dotnet-v3#4101]
**Describe the bug**
Migrating from v2 to v3 causes a significant increase in throttling and normalized RU consumption for a highly partitioned container. Based on RU consumption we expect to see 2x costs if we continue to use v3 vs v2. Increased throttling appears correlated to the increase in RU consumption but is not affecting our application (429s can be seen in Cosmos insights, sometimes as many as 6 per request, but they do not bubble up to our application. SDK appears to be executing retry correctly).

**Expected behavior**
We expect similar cost and similar (or better) performance using the v3 SDK versus the v2 SDK

**Actual behavior**
Cosmos Insights shows a distinct change in behavior after we released a build using the v3 SDK relative to v2 (red line indicates time of release)

Similar spikes in requests cause a much larger increase in Normalized RU consumption in v3 vs v2. On v3 we are consistently maxing out throughput where previously we would hang out mostly between 40-80%
![screenshot 1](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/18538017/fa88c7f5-a24c-46b6-9283-b443975c1453)

Similar spikes in requests also show larger increases in 429s in v3 vs v2. Previously we saw almost no throttling.
![screenshot 2](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/18538017/cf3ec3d8-aa6e-4836-b547-bd40a0a3ab2b)

Scaling up to 75,000 max RU/s had minimal affect. At best we saw a slight reduction in the rate of 429s and a few short periods of less than 100% RU utilization.  

**Context**
- Container is used to store 1 type of document 
- Container is set to autoscale 
- Indexes are defined for 5 properties 
- Partitioned on property "/partitionKey"
- partitionKey value is always a guid 
- Each partition contains anywhere from 5-500 documents around 10kb each 
- Write workflow involves creating a write task for each item in a set of documents (5-500, all headed for the same partition) then using _await Task.WhenAll(...)_ to wait for completion (_AllowBulkExecution_ = false)
- Our Application does minimal reads from this container. The vast majority (95%+) of transactions are writes
- Reproduces with Microsoft.Azure.Cosmos 3.35.4 and 3.35.3
- EnableContentResponseOnWrite = false was tested and had no discernable effect

**Comment by ealsur** [comment]
@elimetzlerprieb The SDK does not by itself, increase RU consumption in an account. There is no significant difference in the content of the request between V3 and V2 and the RU cost of an operation depends on the size of the payload (10Kb in your case) and other configurations, such as your Indexing Policy, none of these are related to the SDK.

V3 SDK is more performant and can deliver greater throughput than V2 SDK, what you are probably seeing is this. The volume of operations/sec is higher on V3, thus, leading to more "per second" RU consumption.

You can adjust the volume of data / operations accordingly.

Were you also using `Task.WhenAll` in V2 SDK?

**Comment by elimetzlerprieb** [comment]
Hi @ealsur, thank you. Yes, we used the same `Task.WhenAll` approach when using v2 and v3. The only significant difference between our builds was using `cosmosClient.CreateItemAsync(...)` instead of `documentClient.CreateDocumentAsync(...)`

The relationship between performance, RU consumption, and cost is hard to reconcile.

Even if our total RU consumption for any particular process does not increase with the v3 SDK, increased throughput means our maximum RU/s is going to be much higher. Since autoscale containers bill on the 'highest RU/s used each hour' this actively disincentivizes us from moving to the more performant package for cost reasons.

It also _feels_ like the increase in normalized RU consumption is higher than expected just based on better throughput. It seems like we should see briefer, taller spikes in RU consumption, instead of being consistently maxed out. 

Do you have a rough estimate for the expected improvement in throughput using the v3 SDK vs v2? It seems to me like if we scale our container up a similar amount we should see better normalized RU consumption behavior, i.e. brief, tall spikes. If we don't see that behavior (completely maxed out RUs) then it would indicate there is perhaps another issue at hand. 

`You can adjust the volume of data / operations accordingly` 
Just to clarify are you recommending we rate limit on the application side to avoid large spikes in RU/s?

FYI, we rolled back to v2 and immediately saw a reduction in normalized RU consumption and throttling 
![screenshot 3](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/18538017/f0c44c28-308a-46d8-82ab-74eeb629c9aa)
![screenshot 4](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/18538017/81a5a1c1-d27b-4aaf-b86c-2eed1252cc3e)

**Comment by ealsur** [comment]
> Do you have a rough estimate for the expected improvement in throughput using the v3 SDK vs v2? It seems to me like if we scale our container up a similar amount we should see better normalized RU consumption behavior, i.e. brief, tall spikes. If we don't see that behavior (completely maxed out RUs) then it would indicate there is perhaps another issue at hand.

I don't have any numbers handy, maybe @jcocchi can chip in here.

> Just to clarify are you recommending we rate limit on the application side to avoid large spikes in RU/s?
The logic is pretty straight forward. Your container can process up to X RU/s before throttling. If within 1 second, you send 100 operations or 1000, that will affect the total RU/sec you consume. It will obviously process data faster though (which is a metric that is missing on this picture). What dictates the operations/sec is your application, the size of the Task.WhenAll and/or the concurrency within the application. The SDK is not the one deciding to send operations, it is in the application's control. At some point when designing the app you might have decided that for V2 SDK, the ideal batch size was X to consume Y RU/s. Given that V3 has higher throughput, then your app can now push more operations within the same second.

Reverting to a slower client (V2) will certainly reduce the RU/s consumption assuming the same data load, because it will send data slower, consuming less RU within the same second BUT taking longer to process the data.

**Comment by bartelink** [comment]
All the a aboe is good advice, but would still recommend to eliminate porting errors from your inquiries though - it's definitely possible to e.g. end up not passing a partition key in some cases and hence end up targeting a fundamentally different service API with a diff charge structure.

**Comment by jcocchi** [comment]
@elimetzlerprieb - the degree of perf improvements between V2 and V3 depends on the type of workload you're running as well as some environment factors (.NET version etc.). We have seen about 20-30% improvements in our test benchmarks when moving to V3. I echo what @ealsur mentioned, it would be better to determine the desired throughput with V3 than relying on V2 to lower the throughput for you because it's less performant. The V2 SDK is on a deprecation path and won't receive any new features, after deprecation in August 2024 it also won't receive maintenance. If the primary issue with V3 is that it's creating too many 429s, I recommend you work through some of the prior suggestions to mitigate that rather than downgrading the SDK.

Another suggestion is to test out burst capacity. It's a free feature that just reached GA and may help you smooth out spikes in RU consumption. One note- the max any given physical partition can burst to is 3K RUs, so if you already have over 3K RUs provisioned per physical partition this won't help you. https://learn.microsoft.com/en-us/azure/cosmos-db/burst-capacity
