### ISSUE TITLE
Memory leak within Microsoft.Azure.Cosmos.Direct library

### ISSUE THREAD

**Issue by hari-hlubovac-carvana** [Azure/azure-cosmos-dotnet-v3#4124]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Every service we use Microsoft.Azure.Cosmos package in Direct connection-mode experiences increasing memory consumption, until it eventually reaches limits and crashes. We captured and compared memory dumps, where Microsoft.Azure.Documents.BufferProvider is being mentioned as possible culprit. We briefly examined the source code of the Direct library (via the "msdata/direct" branch of the parent Cosmos library here), and we spotted how an instance of that class isn't being disposed of in at least one scenario. We stopped looking after we found that one scenario, which is: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e727fd57ad82cc8af4f60362fe02d2febe3a662f/Microsoft.Azure.Cosmos/src/direct/Dispatcher.cs#L753C39-L753C39 (line 753, class "Microsoft.Azure.Documents.Rntbd.Dispatcher", method "Task ReceiveLoopAsync()"). In other words, it appears to be that "responseMd.Dispose()" call is due right before that object was set to null.

**To Reproduce**
Use your library over a longer period of time, in a highly utilized service, via an instance of CosmosClient configured with ConnectionMode=Direct.

**Expected behavior**
To have memory usage maintain a stable range, as opposed to being continuously increased until the maximum is reached. 

**Actual behavior**
See description above.

**Environment summary**
SDK Version: multiple versions, including the latest
OS Version: Ubuntu; asp.net core; multiple versions; seems irrelevant

**Additional context**

**Comment by hari-hlubovac-carvana** [comment]
@kundadebdatta

**Comment by ealsur** [comment]
@hari-hlubovac-carvana are there any dumps or evidence that shows this being the problem? Do you have some [Diagnostics](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-dotnet-sdk#capture-diagnostics) to see the client configuration?

**Comment by kundadebdatta** [comment]
@hari-hlubovac-carvana : I would also suggest that you take the memory dumps from the [latest version of the v3 release](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.35.4) to get a better understanding. The `msdata/direct` branch is primarily for testing purposes and it's sometimes not up to date with the latest code. Therefore, as @ealsur has suggested, any evidences, such as diagnostics, dump snapshot, will greatly help us to get to the bottom of the root cause.

Also, when you mentioned the term "compare", which dump you compared with ? Is that another version of memory dump taken from an older version of the SDK ?

**Comment by hari-hlubovac-carvana** [comment]
We did take memory dumps from the actual released version of CosmosClient library. I mentioned researching and locating the source code of the Direct library as a favor to you, to perhaps investigate and relay to the group that owns it - as I see that isn't your group and that source code hasn't been published (since your copied it over for reference). It might be that I'm right about the missing `Dispose` call where I pointed it's missing.

As far as which version of the CosmosClient library we're using: we've been dealing with this for months, and it's been evident with literally every version of that library. We watch your releases, and we update promptly, with hopes it's been fixed. The mentioned memory-dumps were taken against 3.35.4. We do this by generating two dumps across a period of time, then by diff-ing them using the PerfView.exe. I'm an amateur reading PerfView reports, but this is how we concluded where the problem was (which is how I then stumbled upon the suspect-problem within the Direct lib):
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/61329215/1d52a08d-dcee-4e17-9531-df62def7170b)
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/61329215/b893e5d3-63e7-4861-9309-878b26700b03)


This is an example of what, to us, indicates the memory growth over time:
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/61329215/8d80e98c-23d9-4c02-9fac-8dc571c1d84c)

**Comment by hari-hlubovac-carvana** [comment]
By the way, it appears that the nuget dependency for the Direct library isn't configured properly.
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/61329215/6984be5d-a893-444b-80f0-168fba836e41)

**Comment by hari-hlubovac-carvana** [comment]
@ealsur instead of asking me to go out of my way to further profile our services (yes, there are multiple), to capture more diagnostics, could you please examine the code location within the Direct-library that I pointed at - it's really trivial to understand that the `Dispose` call is missing there, which may be the culprit.

**Comment by ealsur** [comment]
@hari-hlubovac-carvana The Direct package inclusion is by design, it is not a nuget dependency but the DLL is packed inside.

The reason I am asking about Diagnostics is because the code you are pointing out, deals with TCP connections. TCP connections are expected to be long-lived by design. The volume of TCP connections depends on the size of the container and the physical partitions -> https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/sdk-connection-modes#direct-mode

You mention that the culprit is Microsoft.Azure.Documents.BufferProvider, the BufferProvider is per connection (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/e727fd57ad82cc8af4f60362fe02d2febe3a662f/Microsoft.Azure.Cosmos/src/direct/Connection.cs#L127), the volume will depend on the number of connections. If connections are closed, then they will lower, if connections increase, they increase. The number of connections depends on the physical partitions and volume of requests (previous paragraph link). I am not sure how the Dispatcher code you linked is related to the BufferProvider though as the Receive Loop and the lifetime of the Connection (which holds the BufferProvider) are not tied. The BufferProvider is not disposed if you call `responseMd.Dispose()`.

If this is a problem with a recent SDK release, then the problem might be related to number of connections being created, not about any memory leaks. Rather, the SDK might be opening more connections. This is something @kundadebdatta was investigating.

With a Diagnostics we can analyze how the client is configured and how many client instances you are using. I am referring to the SDK Diagnostics coming out of the operations. If the CosmosClient is not being used as a Singleton (you have more than 1 instance) then the volume of connections (and BufferProvider) increases because these are not shared across CosmosClient instances.

Regarding this comment:

> Use your library over a longer period of time, in a highly utilized service, via an instance of CosmosClient configured with ConnectionMode=Direct.

Just to share some insight, this code is (SDK + Direct package) is internally used by the Azure Cosmos DB service itself. The same code your application uses is being run on the service itself. This counts as a highly utilized service for a long period of time :)

**Comment by hari-hlubovac-carvana** [comment]
One. We're constructing one instance of CosmosClient, with the ConnectionMode=Direct (default behavior), and we're using it as a singleton, never to be reconstructed again. The service continuously gets requests that depend on cosmosdb interaction (INSERT or SELECT) and while there may be a lot of them simultaneously and over a long period of time, we'd expect the memory usage graph line to be flat, as opposed to continuously increasing until it reaches preset limits.

But, I'll work on collecting that diag, the way that you suggested. Maybe it'll help. Thank you.

**Comment by hari-hlubovac-carvana** [comment]
The diag-capturing sample that you pointed to appears to be related to troubleshooting slow transfer for individual occurrences/interactions - which doesn't seem to be the problem in our case. Our problem relates to some data lingering in service's memory space without being released. If I was to log this diag-metadata for each request, we'd have thousands to look at. I'm not sure if that's the correct way to go. But, if you'd still like a random one (or few), I could to it?

**Comment by hari-hlubovac-carvana** [comment]
I hope this helps understand what I meant here:
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/61329215/f90ea0b8-9137-4d5c-bdc4-197c6e72f725)

**Comment by hari-hlubovac-carvana** [comment]
Pardon me; the execution branch that I think isn't disposing this object is the 2nd one listed (so, not the one that my previous screenshot points at); correction here:
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/61329215/65c97a36-8c68-407a-bd4a-25beb99d41f4)

**Comment by hari-hlubovac-carvana** [comment]
This is probably a little bit better indicator on the quantity of memory an example service deals with, as I inadvertently omitted that earlier:
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/61329215/35a9b093-7746-4bb1-aaa4-c2b342b52498)

**Comment by ealsur** [comment]
> The diag-capturing sample that you pointed to appears to be related to troubleshooting slow transfer for individual occurrences/interactions - which doesn't seem to be the problem in our case

This is a generic document, we have the same documentation across everywhere: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/troubleshoot-dotnet-sdk#capture-diagnostics

I was just pointing to one of them. The Diagnostics is important because it shows volume of established connections, connectivity settings, and tracks client instances.

**Comment by hari-hlubovac-carvana** [comment]
OK, Thank you. I'll work on that also. We decided to use the dotMemory profiler over one of these services, so perhaps that reveals additional data. Please keep this open, if you can.

**Comment by DLackmeyer** [comment]
I also encountered this. After some digging around through the link provided by ealsur, I determined that the issue is that we have a very large number of partitions (we access thousands of them per day), which causes the SDK to create a massive number of connections.

This usage pattern can be addressed via this setting:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.idletcpconnectiontimeout?view=azure-dotnet

Hopefully this helps anyone else that stumbles on this thread.
