### ISSUE TITLE
Question regarding the ClientRetryPolicy for 408 and 503 status code

### ISSUE THREAD

**Issue by blankor1** [Azure/azure-cosmos-dotnet-v3#4139]
**Describe the bug**
From the doc it says that ["clients redirect reads to other regions when a write region outage happens."](https://learn.microsoft.com/en-us/azure/cosmos-db/high-availability#:~:text=Clients%20redirect%20reads%20to%20other%20regions.) 

But seeing from the code of ClientRetryPolicy.cs, I found that for 408 status code, it will not retry for both read and write (since this line is a no-op and just return false).: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/08981bf2fd87f110ca4a1e2af5f82974857c1aaf/Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs#L176C1-L177C51

And for 503 it will only retry 1 time: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/08981bf2fd87f110ca4a1e2af5f82974857c1aaf/Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs#L397

I do see that for **HttpRequestException** it will retry multiple time from multiple regions. But in our previous experience during the Cosmos DB outage, we will first receive lot of 408 and 503 status code with **CosmosException**. And if they are not retried(please correct me if I'm wrong), it seems conflict with the doc description. So I would like to understand the behavior of the retry better.

Also, is there a way that we can simulate the server return 408 or 503 to test our service resilience and verify the client behavior?

Looking forward to hearing from you. Thanks a lot!

**To Reproduce**
Hard to reproduce since 408 and 503 happened during the outage.

**Expected behavior**
With the CosmosClientOption.ApplicationRegion configured, all read requests will automatically redirect to the read region and won't be affected.

**Actual behavior**
Not have a change to test since in last outage we haven't set ApplicationRegion or ApplicationPerferredRegion.

**Environment summary**
SDK Version: 3.31.0
OS Version: Windows

**Comment by blankor1** [comment]
Also, when I'm simulating the outage behavior using the Clumsy I hit a strange case.

First, I set the CosmosClientOptions.RequestTimeout to 1 second, and run 100 task to get a same items in the db. They all succeed. So through my understanding the TCP connection to this part should already established(Please correct me if I'm wrong).

Then I start the Clumsy to have the inbound and outbound lag to be 2 seconds, and start a new task to get the same item again. But instead of 408, I got 503 status code which says ""The request failed because the client was unable to establish connections to 4 endpoints across 1 regions. Please check for client resource starvation issues and verify connectivity between client and server." which confused me. Why there is still connection that need to be established?

**Comment by ealsur** [comment]
> clients redirect reads to other regions when a write region outage happens

408s and 503s are not outages. 

The cases where SDK reaches out to other regions are documented here: https://learn.microsoft.com/azure/cosmos-db/nosql/troubleshoot-sdk-availability

408s and 503s are considered transient failures that can either be coming from the service as responses or generated within the client due to networking issues.

The 408/503 section in the above link covers what does the SDK do in these cases.

SDK contains retries for certain error conditions, including 408/503, as described in https://learn.microsoft.com/azure/cosmos-db/nosql/conceptual-resilient-sdk-applications

And for .NET implementation details we have : https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/SdkDesign.md

In your case what you are doing with Clumsy is generate TCP timeouts, that are retried in the Direct layer (see last link) until retries are exhausted. You are correct that the SDK reuses existing connections but when retries happen the SDK might reach out to other replicas (hence the 4 endpoints in the message). Upon failures all across, a 503 is generated and the ClientRetryPolicy will take over to retry one time (as per the first link in my answer and also covered in the last link) for read operations (receive timeouts cannot be retried within the SDK as per the second link).

**Comment by blankor1** [comment]
Thank you @ealsur for your very informative answer!

And for the direct mode SKD retry for 408s, could you help point me to the place where the 408s(read operation) will be retried(I didn't find it in the [GoneAndRetryWIthRequestRetryPolicy.cs](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/msdata/direct/Microsoft.Azure.Cosmos/src/direct/GoneAndRetryWithRequestRetryPolicy.cs))? Is it also in the Direct package? I see HTTP retry layer for the timeout from the SdkDesing.md. But that is seems only apply for the gateway mode not direct mode.

**Comment by NaluTripician** [comment]
I believe what he meant by "receive timeouts cannot be retried within the SDK" is that there is no logic within the SDKs to retry 408 status code responses.  Depending on the request type, 408 responses can be wrapped into a 503 error in [CosmosHttpClientCore ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6de10ddc98d45440d7fd334a55b2f1d171785f28/Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs#L391C37-L402C38) and then retried as a 503 in the [ClientRetryPolicy](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/6de10ddc98d45440d7fd334a55b2f1d171785f28/Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs#L250). I believe this also answers your second question. Direct Mode will also handle received timeouts, in the [SDK Design for Direct Mode Retries](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/SdkDesign.md#direct-mode-retry-layer), the SDK will generate a 410 Substatus Code 0 and will retry in GoneAndRetyWithRyquestRetryPolicy.

**Comment by ealsur** [comment]
Typo: "receive timeouts cannot be retried within the SDK as per the second link" should be "**write** receive timeouts cannot be retried within the SDK as per the second link"

**Comment by blankor1** [comment]
Got it. Thanks a lot!
