### ISSUE TITLE
Question: Can we use Guid (random string) as instance name (Change Feed) 

### ISSUE THREAD

**Issue by oshvartz** [Azure/azure-cosmos-dotnet-v3#4184]
related to #3067
I saw that the instance name should be unique per compute and should be the VM\pod name
my question is can I use just guid or any random string - will it work and will it have any effect on behavior or RU utilization ?

**Comment by bartelink** [comment]
It's just a tracking id that flows into the lease document in oredr to aid troubleshooting, without any major restrictions.
Unless the size pushes the lease document size over a 1K boundary etc, it should not affect RU consumption etc.

**Comment by oshvartz** [comment]
@bartelink thanks for you answer 
just to verify and make my question clearer: Using guid is fine and only may affect troubleshooting
I intent to generate new guid\random string each time the process starts so for the same node I will have a lot of instance names
over time
do the lease collection has internal cleanup of process crash ?

**Comment by bartelink** [comment]
Yes, people put process ids and machine names in and all sorts e.g. https://github.com/jet/propulsion/blob/master/src/Propulsion.CosmosStore/CosmosStoreSource.fs#L43
the true persistent identifier is the processorName - that's the thing that's shared across competing consumers and/or replacement processors if you kill one

>do the lease collection has internal cleanup of process crash ?

there is a document per physcial range
it records who has it leased and for how long
when that time has elapsed, it's open to be taken over by another consumer
Normally the configured renew interval means it does not expire
When you shut down, you dispose/close the CFP and that releases the lease (stops renewing, and hands back the reserved time)

If you crash, your instance name will remain stamped in the lease document

There is no magic process anywhere that will remove anything (but there also does not need to be)

Remember with the CFP, it's 
- N physical ranges worth of server clusters that host your data
- your process negotiating with other competitors with the same processor name via documents in the -aux container you nominate
- the winning processes querying a range of the moniitored container once it has won a lease per the co-operative process

**Comment by oshvartz** [comment]
Hi
@bartelink 
Thanks for the detailed response. I am not sure I understand all that you mention above. So I will try to summarize
for instance-name I could do whatever I want as long as it's unique - for example use process id that will change after restart.
What is important is processorName that should be constant.
Can you say what will happen if process will set new processorName each time after it restarts and when we don't dispose and the process crash ?

**Comment by bartelink** [comment]
if you do a new processorname each time then
- each processorname has a separate set of lease documents
- each set starts afresh if it is a new name
- 2 instances of code can process same data at same time

the "don't dispose and crash" just means nobody will ever touch those documents in the aux container again. Do that 1000 times and you have 1000 docs. Also if you dont use the same processor name and e.g. your host runs 2 copies of your processor, they will work completely independently

**Comment by bartelink** [comment]
In general the latency and RU costs should remain stable - the impl just does point reads and updates of the documents
You'll just pay a tiny bit more for document storage
(If it got to 20/50GB and split due to a truly insane amount, then your RU capacity would become diluted, but that's very theoretical based on your scenario as I understand it)
Though in your case, if there was a delete api as described in https://github.com/Azure/azure-cosmos-dotnet-v3/issues/510 you'd probably use that with a stable name as you're not deriving any value from the document after processing is finished (i.e. nothing is ever continuing based on where the checkpointed posiition got to)

**Comment by oshvartz** [comment]
@ealsur  @bartelink 
Sorry for not mentioning it earlier - the instance name can be just guid this is clear. Now I'm focusing on processor name and our use case for change feed is a bit different we have multiple nodes, and we want all of them to get updates (like pub/sub) we just gave each one different processor name so they all will get the same updates. now we are considering just creating random string for processor name each time the service starts - different one.
We could use pull for each node but then we needed to manage the current last update time and though that CF will give us this out of the box.
So having a lot of processor names but they do not run in the same time - it is still causing high RU consumption  ?

**Comment by ealsur** [comment]
>  want all of them to get updates

The problem with this approach is the pressure you put on the Lease Container. It will consume RUs and the higher the number of instances, the higher the RU pressure.

CFP is designed to do 2 things mainly:

* Automatic distribution of leases across machines, with dynamic adjustment when the number of machines changes (this is achieved by the common Processor Name + monitored container + lease container across machines).
* Store state and recover/resume

Can you expand on exactly what having many machines, tracking progress independently, is trying to achieve? Is each machine doing something different? Is this for cache synchronization?

**Comment by oshvartz** [comment]
@ealsur as you mentioned 
This is done for cache synchronization 
We are keeping container documents in memory with some enrichment on the data in  container and we want to be sync if documents are added or deleted
The amount of insanced are small < 30
So we didn't though it will have pressure on the collection. Our question is on setting the processor name as guid and changing its value on service restart
Could you advise what is the risk taking this approach and alternative to achieve the same functionality

**Comment by ealsur** [comment]
> This is done for cache synchronization

Then why using Change Feed Pull model storing the continuation inmemory, is not a valid option?

If the machine crashes, you can start a new Pull model, it is just for cache synchronization, and cache is an optimization. You can even start the pull model from the Beginning if you want to pre-hydrate the cache.

**Comment by ealsur** [comment]
CFP for cache synchronization across a farm of machines does not make much sense. It is costly on the lease container, you are not benefiting from automatic load distribution, and neither from the lease store, because when a machine crashes, because you are using a different processor name, the previous state won't be resumed. Even if you used a fixed processor name per machine, resuming the state does not help with cache synchronization.

**Comment by oshvartz** [comment]
@ealsur  
These are great insights for sure change Feed Pull model this is what we need - we'll work on it.
Just to verify for the short term - using the same processor name or guid that is changing every restart is equally bad - there is no reason to have is consistent ?

**Comment by ealsur** [comment]
Not sure I fully understand your question. If you change the **Processor name** on every restart, using a Guid, then every restart creates a new unique set of leases in the lease container, and it will start processing as if it had never done any processing (similar to starting a Pull Model iterator from scratch). 

If you **keep the Processor name** inbetween restarts, then the processor will resume to read the Change Feed from the last time it saved progress (before it restarted), but in your case, because you are using it for cache synchronization, that really makes no benefit.

**Comment by oshvartz** [comment]
@ealsur after understanding this is not the correct approach to use CFP my question is if there is different between setting processor name "node_5" vs using guid that will change every restart of the service

**Comment by ealsur** [comment]
My apologies if my response was not clear, I tried to address that scenario with this part of my reply:

> If you keep the Processor name inbetween restarts, then the processor will resume to read the Change Feed from the last time it saved progress (before it restarted), but in your case, because you are using it for cache synchronization, that really makes no benefit.

If you always use "node_5" then the processor will pickup the previous saved state and will start to deliver any changes that happened between when it shutdown and when it is coming back up. For cache synchronization, I am not sure what is the value this brings because it will just hydrate whatever changed in between those times, it won't hydrate the state of the entire container. Is this small delta of changes worth the cost (RU) of maintaining the lease container? If the answer is yes, then you can do it, if the answer is no, then probably Pull Model is still the solution.

**Comment by oshvartz** [comment]
@ealsur and @bartelink  thanks for making it clear 
appreciate your answers
