### ISSUE TITLE
ToQueryDefinition() returns null

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-cosmos-dotnet-v3#4196]
**Describe the bug**
The `ToQueryDefinition()` returns `null` if using the conditional `Where`. Why doesn't it work with `WhereIf`? It's a simple extension

**To Reproduce**

```cs
IQueryable<Device> queryable = _container
    .GetItemLinqQueryable<Device>(requestOptions: new QueryRequestOptions{  MaxItemCount = 100 })
    .WhereIf(Connected.HasValue, d => d.Connected == Connected);

var queryDefinition = queryable.ToQueryDefinition();
var queryText = queryDefinition.QueryText;  <---------------- System.NullReferenceException
```
My extension method

```
public static IQueryable<TSource> WhereIf<TSource>(this IQueryable<TSource> source, bool condition, Expression<Func<TSource, bool>> predicate)
    => condition ? source.Where(predicate) : source;
```

**Expected behavior**
A query definition is generated from LINQ.
`queryDefinition ` is not null and `queryText` is something like

- `select * from root where root.Connected = true` if my variable `Connected` is `true`
- `select * from root where root.Connected = false` if my variable `Connected` is `false`
- `select * from root` if my variable `Connected` is `null`

**Actual behavior**
`queryDefinition ` is null

**Environment summary**
SDK Version: 3.37.0
OS Version: Windows 11

**Additional context**
It works for this code

```cs
IQueryable<Device> queryable = _container
    .GetItemLinqQueryable<Device>(requestOptions: new QueryRequestOptions{  MaxItemCount = 100 });

if (Connected.HasValue)
{
    queryable  = queryable.Where(d => d.Connected == Connected);
}
var queryDefinition = queryable.ToQueryDefinition();
var queryText = queryDefinition.QueryText;
```
but what is wrong with the extension?

**Comment by Marusyk** [comment]
👀

**Comment by adityasa** [comment]
@Marusyk thank you for reporting this issue. I am able to reproduce the issue using a simple test as shown below.

Per existing behavior, ToQueryDefinition does return null in certain cases. The repro does not require any extension method to be involved.
The most common case of this is when there is no LINQ operator involved, as shown by the third variation below (which hits the NullReferenceException) in addition to your case.
In fact, in the WhereIf example you noted, this is the "else" case (since Connected.HasValue is false) which simply returns the original IQueryable expression without any LINQ operation.

Internally when no query definition is generated, the sdk stack implicitly converts it to "SELECT * FROM c", however that query definition is not exposed on the ToQueryDefinition interface.

A workaround (as you may have figured out and the test below shows) is to perform a null check on the client side on queryDefinition before accessing the QueryText.

Test output:
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/12704155/14db0459-c20b-432d-b5b5-f56d8999a200)

Test:

        [TestMethod]
        public void WhereIf()
        {
            {
                bool? Connected = true;
                IQueryable<Device> queryable = this.Container
                    .GetItemLinqQueryable<Device>(requestOptions: new QueryRequestOptions { MaxItemCount = 100 })
                    .WhereIf(Connected.HasValue, d => d.Connected == Connected);
                var queryDefinition = queryable.ToQueryDefinition();
                var queryText = queryDefinition?.QueryText ?? "<<NULL>>";

                Debug.WriteLine($"Connected.HasValue : {Connected.HasValue}; queryText: {queryText}");
            }

            {
                bool? Connected = false;
                IQueryable<Device> queryable = this.Container
                    .GetItemLinqQueryable<Device>(requestOptions: new QueryRequestOptions { MaxItemCount = 100 })
                    .WhereIf(Connected.HasValue, d => d.Connected == Connected);
                var queryDefinition = queryable.ToQueryDefinition();
                var queryText = queryDefinition?.QueryText ?? "<<NULL>>";

                Debug.WriteLine($"Connected.HasValue : {Connected.HasValue}; queryText: {queryText}");
            }

            {
                // Without any WhereIf
                IQueryable<Device> queryable = this.Container
                    .GetItemLinqQueryable<Device>(requestOptions: new QueryRequestOptions { MaxItemCount = 100 });
                var queryDefinition = queryable.ToQueryDefinition();
                var queryText = queryDefinition?.QueryText ?? "<<NULL>>";

                Debug.WriteLine($"Without any WhereIf, queryText: {queryText}");
            }

            {
                // Origina repro
                bool? Connected = null;
                IQueryable<Device> queryable = this.Container
                    .GetItemLinqQueryable<Device>(requestOptions: new QueryRequestOptions { MaxItemCount = 100 })
                    .WhereIf(Connected.HasValue, d => d.Connected == Connected);
                var queryDefinition = queryable.ToQueryDefinition();
                var queryText = queryDefinition?.QueryText ?? "<<NULL>>";

                Debug.WriteLine($"Connected.HasValue : {Connected.HasValue}; queryText: {queryText}");
            }
        }

        internal class Device
        {
            public bool Connected { get; set; }
        }

internal static class LinqExtensiosn
{
    public static IQueryable<TSource> WhereIf<TSource>(this IQueryable<TSource> source, bool condition, Expression<Func<TSource, bool>> predicate)
        => condition ? source.Where(predicate) : source;
}
