### ISSUE TITLE
Invalid Region Targetted

### ISSUE THREAD

**Issue by chidi-git** [Azure/azure-cosmos-dotnet-v3#4206]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persists in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
We have a read-replica in East US 2, not East US. We see that although the preferred region is East US 2, ~.03% of the time, the SDK attempts to request from East US, although no read replica exists there. 

**To Reproduce**
I'm an internal employee, what is the best way to link an ADO repo?

**Expected behavior**
SDK only targets regions that have read replicas, so East US would never be targeted.

**Actual behavior**
~0.03% of the time, the SDK makes a request to East US, although there is no read replica there.

**Environment summary**
SDK Version: 3.31.2

**Comment by ealsur** [comment]
@chidi-git Can you please share code examples and evidence that shows that the SDK is going to East US?

* How are you creating the client and configuring it? Which APIs are you using for regional preference configuration?
* What sources of information are you using to verify the traffic goes to East US?

**Comment by ealsur** [comment]
SDKs will not route requests to regions not present in the Account information they obtain from the service except on the scenarios described in [ApplicationRegion](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.applicationregion?view=azure-dotnet#remarks) and [ApplicationPreferredRegions](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.applicationpreferredregions?view=azure-dotnet#remarks) which are both during initialization (should happen once) and mean there are connectivity issues affecting connection towards the Global DNS. On top of that, if this behavior is seen frequently, it would also mean, the application is not following the Singleton pattern (because this happens only on initialization).
