### ISSUE TITLE
update Newtonsoft.Json package to 13.0.3

### ISSUE THREAD

**Issue by drma-dev** [Azure/azure-cosmos-dotnet-v3#4209]
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/12803050/a78fd4cd-aee8-4d74-a95e-e376ffca1659)

I already know that it is planned to remove this in the next major update. but until that happens, you could at least use the newest and safest version.

**Comment by ealsur** [comment]
Duplicate of https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3924

This was already discussed last year. Newtonsoft.Json 13 brings **breaking changes**. We cannot update the dependency on the SDK or otherwise we would potentially break existing customers.

See https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3313
