### ISSUE TITLE
Feature request to make Cosmos.Headers.SubStatusCodes to be a public property

### ISSUE THREAD

**Issue by blankor1** [Azure/azure-cosmos-dotnet-v3#4228]
**Is your feature request related to a problem? Please describe.**
We are trying to add some application-side retry through CustomizedHandler. But we found it hard to retry on some cases with SubStatusCode since we can't access the SubStatusCode in the Customized Handler. (For example: 404.1013)

I do see that CosmosException contains public SubStatusCode. But this exception is fomated after all the pipeline returns, so we can't access it in the Customized Handler.

**Describe the solution you'd like**
Make Cosmos.Headers.SubStatusCodes to be a public property, or provide a way to get the SubStatusCode in the Customized Handler.

**Comment by ealsur** [comment]
@blankor1 The substatuscode is a header (`x-ms-substatus`), like any other response header, it can be read from the `ResponseMessage.Headers` property bag.

The rest of the response headers are also present there.

Out of curiosity, what scenario for a retry case do you need the substatus for?

**Comment by blankor1** [comment]
@ealsur Thank you for your response! But the Headers.SubStatusCode seems to be an internal property which we can't access: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/02e4f3475e4842c5dbe551dc706464a52b4172d4/Microsoft.Azure.Cosmos/src/Headers/Headers.cs#L24

For the SubStatusCode use case, we have retry for SubStatusCode like: "404.1013" which indicate the collection creating operation is in process, "404.1002" for session not available. And some logging based on some SubStatusCode.

**Comment by ealsur** [comment]
@blankor1 `Headers.SubStatusCode` is just a string, you can use a string in your code, you don't need the internal property. `Response.Headers` is a dictionary of `string`.

`var substatus = responseMessage.Headers["x-ms-substatus"];`

The properties you are linking are just shortcuts so within the SDK we don't have to keep referencing the same constant and we already have it parsed as an enum for internal processing.

https://github.com/Azure/azure-cosmos-dotnet-v3/blob/02e4f3475e4842c5dbe551dc706464a52b4172d4/Microsoft.Azure.Cosmos/src/Headers/CosmosMessageHeadersInternal.cs#L62

For `404.1002` you should be needing to add a retry policy in general, the SDK already retries: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/SdkDesign.md#cross-region-retries

If a 404/1002 is surfacing to the calling application then there is something not entirely right. It can appear in the Handler Pipeline because it will surface to the ClientRetryPolicy, but should not go up to the calling application.

**Comment by blankor1** [comment]
Verified and it works. Thank you of your very detailed explanation! @ealsur 

Bwt, since this WFConstants class is internal that we can't access through reference, can we treat the string "**x-ms-substatus**" as a public contract and will have release note point out as breaking change if potential change happens on it in the future?

**Comment by ealsur** [comment]
@blankor1 The header names are not defined by the client SDKs, these are headers defined by the service. Thus, the client SDKs even if they wanted, could not change these names in any version.

SDKs just treat the headers in a service response as pass-through. The same headers are returned if you do a call from a REST API client. 

If the header names would change, it would be a service change and it would break all client SDKs.

**Comment by blankor1** [comment]
I see. Thank you so much!
