### ISSUE TITLE
Distributed Tracing: Network level attributes OTel Semantics

### ISSUE THREAD

**Issue by sourabh1007** [Azure/azure-cosmos-dotnet-v3#4232]
Right now, in **.NET SDK**, below attributes are getting recorded

| Key | Value| Comment|
|--|--|--|
| tcp.uri | TNTBD replica url ||
| tcp.sub_status_code| Substatuscode returns||
| tcp.status_code| Status Code||

In **Java SDK**, below attributes are getting captured

| Key | Value| Comment|
|--|--|--|
| rntbd.operation_type | e.g. Create ||
| rntbd.activity_id | GUID ||
| rntbd.request_charge| ||
| rntbd.latency_created|||
| rntbd.latency_channelacquisitionstarted|||
| rntbd.latency_pipelined|||
| rntbd.resource_type|||
| rntbd.latency_decodetime|||
| rntbd.latency_transitiontime|||
| rntbd.lsn|||
| rntbd.gclsn|||
| rntbd.backend_latency|||
| rntbd.is_new_channel|||
| rntbd.request_size_bytes|||
| rntbd.url|||
| rntbd.latency|||
| rntbd.region|||
| rntbd.response_size_bytes|||
| rntbd.status_code|||
| rntbd.request_session_token|||
| rntbd.session_token|||
| rntbd.partition_key_range_id|||

Here intention is to make it consistent across SDKs.

### Proposal

Here we are capturing Network calls which are similar to HTTP calls (just different protocol) . ref. Open Telemetry HTTP call semantics https://opentelemetry.io/docs/specs/semconv/http/http-spans/#http-client

**PREFIX = cosmosdb.tcp** (other suggestions are direct, rntbd, cdbdct)

| Key | Value| Comment|
|--|--|--|
| url.full| replica address||
| url.scheme | rntbd |
| ~~useragent.original~~| ||
| ~~cosmosdb.tcp.request.operation_type~~  PREFIX.operation_type |||
| ~~cosmosdb.tcp.request.activity_id~~ PREFIX.activity_id | GUID ||
| ~~cosmosdb.tcp.request.resource_type~~ PREFIX.resource_type|||
| ~~cosmosdb.tcp.request.is_new_channel~~ PREFIX.is_new_channel |||
| PREFIX.request.size_in_bytes|||
| ~~cosmosdb.tcp.request.region~~ PREFIX.region |||
| PREFIX.request.session_token|||
| PREFIX.response.session_token|| Session token returned from service|
| PREFIX.response.status_code | ref a link to the list of status code, customer can expect ||
| PREFIX.response.sub_status_code | ref. a list of substatus expected here ||
| ~~PREFIX.response.request_charge~~ PREFIX.request_charge| ||
| PREFIX.response.latency||**Do we need it?**|
| ~~cosmosdb.tcp.response.latency.created~~  PREFIX.pipeline.latency_created || We need a better name for this, Latency Created doesn't make sense |
| ~~cosmosdb.tcp.response.latency.channel_acquisition_started~~ PREFIX.pipeline.latency_channelAcquisitionStarted |||
| ~~cosmosdb.tcp.response.latency.pipelined~~ PREFIX.pipeline.latency_pipelined ||We need a better name for this|
| ~~cosmosdb.tcp.response.latency.decodetime~~ PREFIX.pipeline.latency_decodetime ||We need a better name for this|
| ~~cosmosdb.tcp.response.latency.transitiontime~~  PREFIX.pipeline.latency_transitiontime ||We need a better name for this|
| ~~cosmosdb.tcp.response.lsn~~  PREFIX.lsn |||
| ~~cosmosdb.tcp.response.gclsn~~  PREFIX.gclsn |||
| ~~cosmosdb.tcp.response.backend_latency~~ PREFIX.backend_latency |||
| PREFIX.response.size_in_bytes|||
| ~~cosmosdb.tcp.response.partition_key_range_id~~ PREFIX.partition_key_range_id |||

### Final List

**PREFIX = rntbd** (other suggestions are direct, rntbd, cdbdct)

| Key | Value| Comment|
|--|--|--|
| PREFIX.url| replica address||
| PREFIX.request.size_in_bytes|||
| PREFIX.request.session_token|||
| PREFIX.response.session_token|| Session token returned from service|
| PREFIX.response.size_in_bytes|||
| PREFIX.status_code | ref a link to the list of status code, customer can expect ||
| PREFIX.sub_status_code | ref. a list of substatus expected here ||
| PREFIX.operation_type |||
| PREFIX.activity_id | GUID ||
| PREFIX.resource_type|||
| PREFIX.is_new_channel |||
| PREFIX.region |||
| PREFIX.request_charge| ||
| PREFIX.latency|||
| PREFIX.lsn |||
| PREFIX.gclsn |||
| PREFIX.backend_latency |||
| PREFIX.partition_key_range_id |||
| PREFIX.timeline.created || |
| PREFIX.timeline.channelAcquisitionStarted |||
| PREFIX.timeline.pipelined |||
| PREFIX.timeline.decodetime |||
| PREFIX.timeline.transitiontime |||
| exception.type|||
| exception.timestamp |||
| exception.message |||
| exception.stacktrace|||

Operation level attributes which is part of Otel convention : https://opentelemetry.io/docs/specs/semconv/database/cosmosdb/

**Comment by sourabh1007** [comment]
@jcocchi @kirankumarkolli @FabianMeiswinkel

**Comment by FabianMeiswinkel** [comment]
The identifiers above in the proposal IMO are too long. request and response namespace isn't needed (IMO). Normalization on pipeline latency attributes can be misleading - the transport pipelines are different in .Net and Java - so, I think in the documentation we would always need to call out that latency_* just shows in which stages of the pipeline time was spent - without going into any details of individual pipeline steps. Prefix - no surprise, I think rntbd as a prefix is simply more transparent - rntbd is the protocol we use in direct SDKs - Java doesn't even allow direct http, .Net has severe limitations there as well - no need for tcp (that is a no-brainer, who would use UDP or another transport protocol for a database?). To me the alternatives for prefix are "rntbd", "direct" or "cdbdct" or similar. My preference is "rntbd" - we use it in diagnostics when adding transport Uris for the endpoint anyway. In Java we combine status code and substatus code into one attribute - I think this is useful (no need for two separate attributes) and I would do the same in .Net. "session_token" vs. "request_session_token" the latter is the session token provided in the request by the client, the former is the session token returned from the service

**Comment by sourabh1007** [comment]
_The identifiers above in the proposal IMO are too long. request and response namespace isn't needed_ : Here trying to follow HTTP OTel Conventions
![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/6362382/7a3f45b2-ce0e-493a-90a6-e85fbfe93f86)
And I don't think long attribute names has any drawback if they are giving value to us by making information more understanble by customer.
_call out that latency* just shows in which stages of the pipeline time was spent_ : According to Otel Convention, .(dot) is used to seggregate the sections/stages when we identify a value. Actually we don't need to capture latency separately in attributes, because latency is already get captured in an Activity/Span based on time between its creation and dispose. Any discrepancy between these values might trigger unnecessary discussions.
If its representing latency of any stage, then we can rename it to `cosmosdb.tcp.stage.channel.created.latency`. (something like this)
 _I think rntbd as a prefix is simply more transparent - rntbd is the protocol we use in direct SDKs_ : I agree with any prefix which is easily understandable by customer and avoid them going to documentation to understand it. Instead of going with "direct" or "cdbdct", I would have "rntbd". Anyway in _"url.scheme"_, we are mentioning that it is rntbd protocol, So customer would know, what is `rntbd` actually.
_In Java we combine status code and substatus code into one attribute_ : According to me, these are 2 different information and should be separated from each other, thats what we decided at operation level activity also. it should be same everywhere.
 _latter is the session token provided in the request by the client, the former is the session token returned from the service_ : in that case other one would be `cosmosdb.tcp.response.session_token`

**Comment by kirankumarkolli** [comment]
There are some common headers (ex: Size, session-token, etc...) needs some dis-ambiguation. 
If we take Http as reference and their instrumentation is using request and response as means to dis-ambiguation then it only comes down to the long names part (me too felt the same).

Onto the protocol naming part: Even in .NET our ConnectionMode naming is `Direct`. Aligning these with pubic contracts makes sense to me.

**Comment by FabianMeiswinkel** [comment]
Currently in Java transport level traces are disabled by default - why? Because they are rather noisy and consume quite a bit of storage. Try running any reasonable workload against ApplicationInsights with tracing enabled and you will see quickly warnings of throttling etc. unless you change the log analytics workspace to store more data (which becomes expensive quickly). So, yes - attribute names should be informative - but definitely with the smallest footprint possible. 

- UserAgent (does not make sense at a transport (or operation) level - this should be a client wide attribute - we had the same discussion with Liudmila
- Request/Response - this is only necessary for size and session-token. For none of the other attributes it is necessary
- Pipeline - as mentioned before - pipeline is different in Java and .Net anyway - so, I am ok with .Net doing whatever you guys prefer. But on the Java side I am not planning to change anything, introduce a new namespace etc. Documentation will simply say that latency_* attributes can help to determine in which stage of the pipeline the latency was spent - everything else needs our insights anyway because it is deep implementation detail.

**Bottom-line:** 
- If absolutely necessary I think changing the prefix from rntbd to whatever is decided is something I could live with. It is rather expensive (needs to be versioned, will need to keep both names for few months before we can get rid of the old one etc.) but for consistency sake I think that is reasonable. If absolutely necessary in your minds we can also make the change in the three attributes to use "request." or "response." instead of "_" and create separate namespaces for request and response (I did not because both namespaces would have less than 3 attributes - but if http is doing the same this is acceptable.
- Everything else - my proposal would be too keep what we have in Java. We have actual customers using it, there has been no negative feedback from any customer about the names  and let's be honest - transport level traces are implementation detail - none of the attributes will ever be easy to understand for most customers.
- Pipeline - different in .Net and Java anyway - these attributes can very well have different names/structure
- My recommendation would be to have transport-level traces in .Net disabled by default as well. Definitely something I am not willing to change in Java for the reasons above.

**Comment by sourabh1007** [comment]
Here focus is to decide the semantic convention aligned with Open Telemetry. 

We are already aware that there will be cost implication if customer decides to enable everything and start collecting it in Appinsight. Thats where Sampling comes into picture where customer can define the sample size in the Otel exporter, so they can control the cost with everything enabled.

I have updated the list based on above comments:
1. Following HTTP convention for basic information like `url.full`, `url.scheme`, `PREFIX.request.size_in_bytes`, `PREFIX.response.size_in_bytes`, `PREFIX.response.status_code`, `PREFIX.response.sub_status_code`, `PREFIX.request.session_token`, `PREFIX.response.session_token`
2. Considering all other information cosmos DB specific, those will be just `PREFIX.attributename`.
3. Removed Useragent, we don't need it
4. for pipeline related attributes, added pipeline keyword, so that we can follow the same convention in .NET SDK also where all pipeline related information will go in the attributes prefix "pipeline"

**Comment by sourabh1007** [comment]
@lmolkova please let us know if you any suggestion or comment.

**Comment by FabianMeiswinkel** [comment]
> Here focus is to decide the semantic convention aligned with Open Telemetry.
> 
> We are already aware that there will be cost implication if customer decides to enable everything and start collecting it in Appinsight. Thats where Sampling comes into picture where customer can define the sample size in the Otel exporter, so they can control the cost with everything enabled.
> 
> I have updated the list based on above comments:
> 
> 1. Following HTTP convention for basic information like `url.full`, `url.scheme`, `PREFIX.request.size_in_bytes`, `PREFIX.response.size_in_bytes`, `PREFIX.response.status_code`, `PREFIX.response.sub_status_code`, `PREFIX.request.session_token`, `PREFIX.response.session_token`
> 2. Considering all other information cosmos DB specific, those will be just `PREFIX.attributename`.
> 3. Removed Useragent, we don't need it
> 4. for pipeline related attributes, added pipeline keyword, so that we can follow the same convention in .NET SDK also where all pipeline related information will go in the attributes prefix "pipeline"
> 5. I am not using `header` prefix anywhere, even if it is part of request/response header, to address the attribute name size concern raised and I believe that it is not necessary to mention where that information really exists.
> 6. `PREFIX.response.latency`, I don't think we need it.

I am using heavy sampling in our benchmarks already (APPLICATIONINSIGHTS_SAMPLING_REQUESTS_PER_SECOND=2 or 10) still throttling applies regularly. Anyway, above sounds better. BY the way - sub_status_code is its own (optional) attribute in Java as well. It will only be emitted if the sub status code is != 0. All other custom attributes are optional as well. Only emitted if not default/empty. There is one missing above - "rntbd.fault_injection_rule_id" - will become useful in .Net as well when FaultInjection gets merged

**Comment by sourabh1007** [comment]
**Request Timeline in .NET SDK**

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/6362382/e4017ac4-3524-4f2f-a86f-b3d859ce7a1d)

**Request Timeline in Java SDK**

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/6362382/03df58be-537b-42de-aba1-32c6b2d715c7)

It is almost similar. Regardless of this, having `pipeline` prefix is relevant.

**Comment by sourabh1007** [comment]
> > Here focus is to decide the semantic convention aligned with Open Telemetry.
> > We are already aware that there will be cost implication if customer decides to enable everything and start collecting it in Appinsight. Thats where Sampling comes into picture where customer can define the sample size in the Otel exporter, so they can control the cost with everything enabled.
> > I have updated the list based on above comments:
> > 
> > 1. Following HTTP convention for basic information like `url.full`, `url.scheme`, `PREFIX.request.size_in_bytes`, `PREFIX.response.size_in_bytes`, `PREFIX.response.status_code`, `PREFIX.response.sub_status_code`, `PREFIX.request.session_token`, `PREFIX.response.session_token`
> > 2. Considering all other information cosmos DB specific, those will be just `PREFIX.attributename`.
> > 3. Removed Useragent, we don't need it
> > 4. for pipeline related attributes, added pipeline keyword, so that we can follow the same convention in .NET SDK also where all pipeline related information will go in the attributes prefix "pipeline"
> > 5. I am not using `header` prefix anywhere, even if it is part of request/response header, to address the attribute name size concern raised and I believe that it is not necessary to mention where that information really exists.
> > 6. `PREFIX.response.latency`, I don't think we need it.
> 
> I am using heavy sampling in our benchmarks already (APPLICATIONINSIGHTS_SAMPLING_REQUESTS_PER_SECOND=2 or 10) still throttling applies regularly. Anyway, above sounds better (and ok to change if and only if PREFIX != rntbd). If we stick with rntbd above changes are not worth breaking anybody. BY the way - sub_status_code is its own (optional) attribute in Java as well. It will only be emitted if the sub status code is != 0. All other custom attributes are optional as well. Only emitted if not default/empty. There is one missing above - "rntbd.fault_injection_rule_id" - will become useful in .Net as well when FaultInjection gets merged

I am not planning to add all this information immediately in .Net SDK but I want to finalize it is to put it in Otel Semantic conventions. There will be 2 kind of attributes
1. Which follows HTTP convention (mentioned above)
2. `PREFIX.*` : where * can by any cosmos db specific attribute name
3. `PREFIX.pipeline.*` : * can be any request pipeline specific information

**Comment by jcocchi** [comment]
My preference for the prefix is `cosmosdb` or `tcp.cosmosdb`. We can expose rntbd in `url.scheme` like Sourabh has above but putting it in each property name over-emphasizes what is an internal protocol that customers shouldn't have to care about. What we publish is that direct mode uses tcp, and all of these calls are already in the context of direct mode.

If we aren't planning to explain what each of the pipeline steps are, is it still useful to expose? The specific values would be in the diagnostics anyway which is already optionally being captured separately.

**Comment by FabianMeiswinkel** [comment]
> but putting it in each property name over-emphasizes what is an internal protocol that customers shouldn't have to care about. 

I disagree - the whole purpose of transport level traces is to provide information for the internal protocol. lsn, gclsn, any of the pipeline steps, most importantly the fully qualified rnbtd-uri containing partitionId and replicaId and service endpoint are all direct/rntbd protocol details. Yes, most customers won't ever understand or need them (that is why transport level traces should be disabled by default)

> If we aren't planning to explain what each of the pipeline steps are, is it still useful to expose?
For power users (and us) - yes, I believe so. At least for metrics this has proven to be super useful when analyzing why latency is suddenly high with Walmart. Again, mostly based on metrics - but to me the main use case for transport level traces is when customers don't have a way to deal with metrics (for example because they use AppInsights - which falls short for custom metrics compared to Prometheus + Grafana etc.). And in that case when using transport level traces lookin g at latencies for different pipeline stages can be useful. Not necessarily for the customer to self0diagnose what the problem is. But when they can tell us easily for high latency requests in 90 percent the channel acquisition, transit time or whatever other pipeline name is high we can use it to debug what is happening. My only point was IMO it does not make sense to document what happens in each pipeline step - because we need to be able to change what happens where, add new pipeline steps, remove some etc. That is internal implementation detail - but exposing how much time was spent in each of the pipeline stages can be helpful

**Comment by kirankumarkolli** [comment]
It's better to close over a call. @sourabh1007 Monday sync-up plan to go-over this?

**Comment by sourabh1007** [comment]
Yes..on Monday we are going to discuss this only.

**Comment by sourabh1007** [comment]
We synced up online @FabianMeiswinkel @kirankumarkolli @jcocchi Annie
1. `PREFIX.*` : where * can by any cosmos db specific attribute name
2.`PREFIX.timeline.*` : * can be any request pipeline specific information

Updated list on issue description.

**Comment by sourabh1007** [comment]
adding `exception.type`, `exception.timestamp`, `exception.message` in the documentation, in .NET SDK we are already capturing these as part of Network Level attributes. in case of any exception. cc @FabianMeiswinkel

**Comment by sourabh1007** [comment]
Closing this.
