### ISSUE TITLE
Partition key with dot notation 

### ISSUE THREAD

**Issue by aparna198809** [Azure/azure-cosmos-dotnet-v3#4272]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persists in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
There is an old collection with a partition key that has a dot notation (partitionkey.column1).Now when trying to do Readitemasync or Deleteitemasync using .net SDK Resource not found error is thrown in the console.

**To Reproduce**
Now the users cannot create a partition key with dot notation as it is not allowed, but earlier it allowed.Hence the issue is not reproducible  
**Expected behavior**

Since it allowed the dot notation earlier ,there should be some mechanism to read /delete the documents using .Net SDK

In portal the below query works 

select * from c where c.['partitionkey.col1'] ="123"

**Actual behavior**

It gives a 404 resource not found error 
**Environment summary**
SDK Version:
OS Version (e.g. Windows, Linux, MacOSX)

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by ealsur** [comment]
@aparna198809 I'm sorry this is affecting you, this is not something related to the Cosmos DB SDK, although is the SDK returning this failure, the 404 response is coming from the service.

There is nothing that has changed in the SDK nor any possible change that it could be done on the SDK, the values are sent to the service and the service is the one that is returning the 404.

If this has started recently without any SDK changes, that would also highlight this being unrelated to the SDK.

Please follow up with a [Support Request](https://aka.ms/azure-support) if you have not yet done so already.

**Comment by ealsur** [comment]
Just to clarify: The client SDKs just send the values as is (your id and PartitionKey), the service decides the response, whether it's 400, 404, or 200. There is nothing being done on the client side.

If you are getting a 404 response is because the service is returning this error that seems to indicate the document does not exist.

If the document does indeed exist, consider checking the Consistency Level to know if, for example, it was a recent item creation, other clients might not yet see it due to replication.
