### ISSUE TITLE
Reason of Timeouts (408)

### ISSUE THREAD

**Issue by anandnamdev** [Azure/azure-cosmos-dotnet-v3#4295]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
I have following questions
1. I case of request timeouts (408), how can I check from diagnostics logs whether it was due to Request Timeout or due to OpenTcpConnectionTimeout (timeout while making connection)?
2. Default value of Request Timeout and OpenTcpConnectionTimeout. 
3. Should we use CancellationToken for 408s in case of DB writes? If yes, is it possible that we can get operation canceled operation in the middle of write operation which might cause Conflicts (409) when we retry the write request?
4. How can we come up with an optimum value of Cancellation token since request timeouts are defined only for single n/w request whereas Cancellation token is defined for entire operation spanning multiple n/w requests. (See - https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1679). 

**To Reproduce**
Steps to reproduce the behavior. If you can include code snippets or links to repositories containing a repro of the issue that can helps us in detecting the scenario it would speed up the resolution.

**Expected behavior**

**Actual behavior**
Provide a description of the actual behavior observed. 

**Environment summary**
SDK Version: cosmos-netstandard-sdk/3.23.1
OS Version (e.g. Windows, Linux, MacOSX) - Windows/10.0.20348

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).
See attached file - 
[408s.txt](https://github.com/Azure/azure-cosmos-dotnet-v3/files/14122979/408s.txt)

**Comment by ealsur** [comment]
Can you share which is the Cancellation Token you are passing to operations? The exception contains a related link: https://aka.ms/cosmosdb-tsg-request-timeout, that one has the difference of both settings.

A 408 means the issue was receiving the response (RequestTimeout), it was on the network. Because the request was sent, it the SDK cannot retry: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/conceptual-resilient-sdk-applications#timeouts-and-connectivity-related-failures-http-408503

OpenTcpConnectionTimeout means the connection could not be established, it is retryable by the SDK and it will do so until either retries are exceeded or your Cancellation is signaled. In this case, you'd get an HTTP 503 if the connect attempts keep failing or an OperationCanceledException if the CT is signaled.

Current defaults are 5 seconds for OpenTcpConnectionTimeout and 6 seconds for RequestTimeout (your version might have different values)

The logs attached show 408s due to Receive Timeouts - SDK will not retry. If you retry, you can get a HTTP 409 or a success, it depends on whether or not the original request after leaving the client reached or not the service (impossible for the SDK to know).

As a side note, you seem to be using SDK 3.23 (2+ years old), might want to consider updating to a more recent version.
