### ISSUE TITLE
Change Feed Processor public API name changes

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-cosmos-dotnet-v3#432]
Based on feedback, we'll rename the public APIs for the Change Feed Processor and Estimator to:

    public delegate Task ChangesHandler<T>(
        IReadOnlyCollection<T> changes, 
        CancellationToken cancellationToken);

    public delegate Task ChangesEstimationHandler(
        long estimatedPendingChanges, 
        CancellationToken cancellationToken);

    public abstract ChangeFeedProcessorBuilder DefineChangeFeedProcessor<T>(
        string processorName,
        ChangesHandler<T> onChangesHandler);

    public abstract ChangeFeedProcessorBuilder DefineChangeFeedEstimator(
        string processorName,
        ChangesEstimationHandler estimationHandler,
        TimeSpan? estimationPeriod = null);

**Comment by bartelink** [comment]
00. Is there a tracking document or post that details what all this stuff is - is it going to be a v4 release? is there a stabilisation period? are we doing final changes circling the drain for a release?

0. The names are fine, but I don't like the indirection of having delegates - there are not enough parameters in the delegate to warrant this

1. Is this in addition to the existing APIs ? Is having `estimatedPendingChanges` as a single `long` not too distilled? For me, backlogs are nuanced - i.e. one might want to infer the min/max and/or how many ranges are behind?

2. what is the value of the default for `estimationPeriod` (in both senses of the word _value_) ?

Also wondering how checkpointing works with this give there's no longer a context argument ? If the old/deeper API still exists, that's fine I guess, but for me it's critical to have support for being able to, for a given batch, be able to checkpoint up to that point independently of the CFP lib's intrinsic support for doing that.

And an aside - given this API, is there any good way to get a rough size of the response - i.e. how many K it was ? (same question for v2)

**Comment by ealsur** [comment]
0. The delegates were to replace the `Func` we were using. What do you mean with "there are not anough parameters?"
1. Which existing APIs? Do you mean the CFP V2 APIs? V3 APIs are somewhat different, the public surface has changed. In V3, the estimator is a push model, like the processor. In V2, you had the `IRemainingWorkEstimator` which had [a method](https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet/blob/200b8fe194863f8ad01e430ed67c9eaa8a4bd6ac/src/DocumentDB.ChangeFeedProcessor/PartitionManagement/IRemainingWorkEstimator.cs#L19) to obtain this same number. We are now making it easier with a push model.
2. Good point on the undocumented default value, see https://github.com/Azure/azure-cosmos-dotnet-v3/blob/dceeac4e8a1476807ab95ae80331d1efd2efcfd1/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedEstimatorCore.cs#L15, will add it to the signature.

Checkpointing works the same way it works on CFP V2, the delegate is just a representation of ProcessChangesAsync. So automatic checkpointing happens after a successful execution of the delegate. CFP V2 didn't let you do partial checkpoints, even manual checkpointing was for the entire batch, never for X amount of documents. Manual checkpointing in V3 is not supported at this point, we would like to understand what are the motivations for manual checkpointing on a per scenario basis, so if you'd like to share how/if you are currently using manual checkpoint, we can talk about it :)

As for the size of the response, that is basically tied to the SDK diagnostics/monitoring story, not only for the Change Feed Processor, but the entire SDK V3. The idea is that you should be able to obtain these diagnostics for any operation in the SDK.

**Comment by bartelink** [comment]
Thanks for the detailed response. Apologies for the wall of text I'm about to subject you to in response ;)

0. by "not enough parameters", I mean that using a `delegate` to a) name a signature b) name the individual parameters has negligible value when the delegate only has 1-3 args, and they're all of different and/or obvious types
1. re existing APIs, as you inferred, I do mean "v2 style things". ~Not sure I agree I want a push model for the estimator~ Interesting - a push model does seem to make sense on the surface. However, I'd like to understand better how I go from that API and 5 ranges that split to 6 and one that is not responding due to rate limited to presenting "6 ranges, 3 in sync, one behind by x, the other by y, and one not responding". In other words, for me, the only API that makes sense is `GetEstimatedRemainingWorkPerPartitionAsync` - the other is worse than useless (how will you represent 2 uncontactable ranges in the response if you're pushing anyway?)
2. I'd suggest not having a default and making people supply a `TimeSpan` so there is one less thing to read or document (is 5s useful when I have 100 ranges? (all depends on the answer to Q1 I guess))

Checkpointing: This really doesnt work for my use cases and doesnt align with how similar tech works; are you saying this is the default, or the only way ?

I'm not talking about partial checkpoints - I'm saying let me:
- control the ingestion rate by responding or not to the API (delaying if I have enough data) - then I can asynchronously update the progress as I achieve it. In other words, I might want to let 5 batches be read ahead and I'll delay my response when I get to 5.
- perform the checkpointing inside my processing as and when I note I've completed a batch (all the time bearing in mind that checkpointing batch 5 implies also having completed 0-4)

The reading N batches ahead and asychronously checkpointing is implemented in https://github.com/jet/propulsion. Consumer code [looks like this](https://github.com/jet/dotnet-templates/blob/d25b806612725a9b0b2cfd9bf0d5a5925223f33f/equinox-projector/Projector/Program.fs#L182) - in this case I'm reading say up to 5 batches ahead on the changefeed, grouping them by stream, feeding them to Kafka and then drive the calls to per-ChangeFeedProcessor batch `CheckpointAsync()` calls as all the Kafka `ProduceAsync` calls required to fulfill the projection complete. If you're telling me there will be no `CheckpointAsync`, I can't do any of this (I was asking this in the other open issue BTW). If there is something of this nature, I'll spike rebasing the impl on V3 (its definitely on the list as there's a big feature roadmap tied to this)

Regarding response size - I appreciate that there is a need and effort re improvments around this. However this doesnt answer the question - given that function signature (which does not have a `context` parameter), how can I do this in context - I'd like to immediately emit a log line saying "I got a 2MB batch from the changefeed at this point in time" (I assume it ultimately arrives in the response header, but really I'd prefer not to have to do keyhole surgery to correlate a diagnostics stream with the actual response if it can be avoided)
