### ISSUE TITLE
Track all CosmosDB requests as dependencies with AppInsights SDK

### ISSUE THREAD

**Issue by Benjiiim** [Azure/azure-cosmos-dotnet-v3#4329]
In a .NET Framework 4.8 WebForm project.
Hosted in a Windows Azure App Service app.
Microsoft.ApplicationInsights and Microsoft.ApplicationInsights.DependencyCollector 2.22.0
Microsoft.Azure.Cosmos 3.38.1
I'm using Cosmos DB SDK with the default Direct mode.

I'm trying to track as dependencies all calls made to Cosmos DB (read, write, replace, ...).
It seems that only some calls are tracked such as "GET /dbs/*/colls/*/pkranges" or "Get collection" (the ones using HTTP(s) even when using Direct mode?)

According to https://github.com/microsoft/ApplicationInsights-dotnet/pull/2635, AppInsights SDK v2.22 should be used and according to https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies CosmosDB SDK v3.33.0-preview minimum should be used to automatically track TCP calls as well.

Is there something else to do to make it work?

Should I do something in the ApplicationInsights.config file to add CosmosDB the same way Microsoft.Azure.EventHubs or Azure.Messaging.ServiceBus are listed (documented at https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net)?

cc @sourabh1007 as this seems to be one of his area of expertise.

Thanks a lot

**Comment by Benjiiim** [comment]
Found that CosmosClientTelemetryOptions.DisableDistributedTracing was set to true by default.
Setting the property to false did the trick.

According to https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclienttelemetryoptions.disabledistributedtracing, the default value should be false.
On https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/sdk-observability, we can read that "This feature is on by default if you're using a supported preview SDK version."
Lastly, we can read on https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies that "TCP will also be captured automatically using preview package >= 3.33.0-preview".

Are these documentation issues?

**Comment by sourabh1007** [comment]
For preview package, it should be `false` but for the stable package, you need to enable it by setting this flag as `false` because this feature is in public preview right now. ref. https://github.com/Azure/azure-cosmos-dotnet-v3/blob/bf0f6291f214836200e8495190b6485b4ec4e10e/Microsoft.Azure.Cosmos/src/CosmosClientTelemetryOptions.cs#L24

Here there are 2 documentation issue I can see:
1. https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclienttelemetryoptions.disabledistributedtracing, => this documentation needs to be fixed.
2. https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies, => using appInsights package you can capture only Operation Level Activities and corresponding HTTP calls. This documentation also needs to be fixed. @jcocchi 

If you want to capture TCP calls made during DIRECT mode, you can follow [this](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry) example with Azure Monitor Exporter.

**Comment by sourabh1007** [comment]
@Benjiiim For your information, we don't recommend you, to enable telemetry for TCP calls and in future version of SDK, we will stop emitting it.
