### ISSUE TITLE
Should we add additional application layer retry on the top on client SDK retry policy?

### ISSUE THREAD

**Issue by blankor1** [Azure/azure-cosmos-dotnet-v3#4344]
We are designing our application and in this doc we found this guidance: https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/conceptual-resilient-sdk-applications#should-my-application-retry-on-errors. 

But my question is: 
**if we should add another layer of retry policy in our application in the top of client SDK retry? If another layer of application level retry is suggested, why those retrys are not covered in the client sdk (since this could be seen as a retry amplifier)?** Or do you have any other concerns to not including all retries in the client sdk?

For example, if we retry on 449 or 503 for 3 times in our application side, we can't guaranty that how many times this request is retried since it will contain both application layer retry and client sdk layer retry.

Looking forward to hearing from you. Any insights would be appreciated!

(Not sure if this the right place to ask but considering it's SDK behavior related question I post it here.)

**Comment by ealsur** [comment]
Whether or not you want to retry some of these cases on your application is really up to you.

The documentation gives you the information on how the SDK retries and if they retry, on top of that, if your business model requires more retries, you can certainly add them, but any guidelines would be kind of hard because we cannot predict all business cases.

Going to your example, the SDK retries on 503s under certain conditions (you could also opt to disable these retries too), if that strategy suffices for your case, then great. If, for example, you have an account in 10 regions, you route requests to a client local to your user, maybe that client got a 503, and you want to add a retry at the Load Balancer level to route the user to another region (different client instance), you could choose to do so. Or maybe you want to retry on timeouts on writes and are fine discarding any HTTP 409 conflicts because your scenario allows for this, we cannot recommend that for everyone, not everyone can support discarding 409s (or they could be doing Upsert).

The chart on that article suggests which ones you could retry, but whether or not you want to do it, depends on each individual case. Maybe whatever the SDK does is enough for you. 

All SDKs tend to align in terms of the retry strategy (either retry for X time or Y iterations depending on the case), the .NET implementation is described in https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/SdkDesign.md which covers the cases described in the above document.

**Comment by kirankumarkolli** [comment]
Please re-open with more context as needed
