### ISSUE TITLE
[QUERY] DISTINCT query using MaxItemCount gives me fewer results than it should

### ISSUE THREAD

**Issue by andreeatatar23** [Azure/azure-cosmos-dotnet-v3#4348]
I've been using .NET SDK to query Azure Cosmos Db I'm having some issues with a query that should retrieve an exact number of distinct items, using MaxItemCount. Here's what the query looks like:

SELECT DISTINCT VALUE c.variant_code
FROM c
WHERE c.last_update >= '2024-03-13T16:48:55.5335094Z'
ORDER BY c.variant_code

I used QueryRequestOptions, so I set **MaxItemCount** to 500, but after this query is executed, the actual umber of items retrieved is less than 500 (around 100). I triedcomposing this query using both LINQ and SQL through the C# SDK but the result is the same.
I can't use GROUP BY beacuse it looks like is not supported in LINQ query and for SQL query it trows an error on the continuation token (https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/pagination).
Even if I set a value to the patition key on QueryRequestOptions, I still se less than 500 items retrieved, so is there a way to get an exact number of distinct items from a container? Any help/pointers would be very helpful.

SDK Version:  3.25.0
OS Version : Windows

**Comment by Maya-Painter** [comment]
Setting **MaxItemCount** does not guarantee a certain number of results, it only guarantees [less than or equal to that amount per round trip](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/pagination#:~:text=The%20MaxItemCount%20is%20specified%20per%20request%20and%20tells%20the%20query%20engine%20to%20return%20that%20number%20of%20items%20or%20fewer). 

If you want to up to a certain number of items you can use [OFFSET LIMIT](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/offset-limit), with the LIMIT value being 500 in your case. 

SELECT DISTINCT VALUE c.variant_code
FROM c
WHERE c.last_update >= '2024-03-13T16:48:55.5335094Z'
ORDER BY c.variant_code
OFFSET 0 LIMIT 500

You will need to continue executing the query until no more continuation tokens are returned, since the number of documents returned per round trip will not be guaranteed.

**Comment by andreeatatar23** [comment]
> Setting **MaxItemCount** does not guarantee a certain number of results, it only guarantees [less than or equal to that amount per round trip](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/pagination#:~:text=The%20MaxItemCount%20is%20specified%20per%20request%20and%20tells%20the%20query%20engine%20to%20return%20that%20number%20of%20items%20or%20fewer).
> 
> If you want to up to a certain number of items you can use [OFFSET LIMIT](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/offset-limit), with the LIMIT value being 500 in your case.
> 
> SELECT DISTINCT VALUE c.variant_code FROM c WHERE c.last_update >= '2024-03-13T16:48:55.5335094Z' ORDER BY c.variant_code OFFSET 0 LIMIT 500
> 
> You will need to continue executing the query until no more continuation tokens are returned, since the number of documents returned per round trip will not be guaranteed.

Thank you for your response! I also tried this approach, but there are hundreds of thousands of documents in my container, and my goal is to extract them in batches of fixed size (500). Using offset and limit, I should compose a while in which to adjust the limit, so that I can finally reach exactly 500 items, and unfortunately this is not at all optimal, the code in the while being executed many times.

That's why I was thinking if there is a method that will bring me directly, exactly 500 distinct items, without executing the query several times within a batch

**Comment by Maya-Painter** [comment]
Unfortunately we cannot guarantee an exact number of items per round trip.  No matter the query, the continuation token will need to be drained fully for accurate results.

**Comment by Maya-Painter** [comment]
@andreeatatar23 Thanks for your question.  I'm closing this issue but if you have any more questions feel free to follow up in this thread and tag me.
