### ISSUE TITLE
ToString(signed-integer) is broken (32-64 bit conversion)

### ISSUE THREAD

**Issue by 92dev** [Azure/azure-cosmos-dotnet-v3#4428]
<img width="495" alt="image" src="https://github.com/Azure/azure-cosmos-dotnet-v3/assets/38649465/92f4f2e1-cfa9-4d80-b3fa-ca28d5232dbc">

DB-Value = `-2069524964357598500`
QUERY-Value = `-2069524964357598447`

As you might notice, it's basically due to the CosmosDB converting it to 32bit and back,
so yeah, hope you can fix this

Probably has nothing to do with the SDK, since I did it from the website directly, but will love to find out that it works well if used from an SDK directly

**Comment by ealsur** [comment]
@92dev thanks for the report.

> will love to find out that it works well if used from an SDK directly

Have you tried executing the query on the .NET SDK? Is it working and if not, what is the exception? Can you share a repro in that case?

This repository is not to track issues with the Azure Portal or the service in general.

**Comment by jackbond** [comment]
I can say with 100% certainty this is NOT an issue with the SDK or the database engine, but some Javascript (the worst language in the history of the universe) code in the portal. Your code would work fine with 32 bit integers, but Javascript (the worst language in the history of the universe) can only natively handle 53 bit integers. Where this will burn you in terms of the database engine is if you ever combine an entity with a long property AND a trigger. Since triggers are written in Javascript (the worst language in the history of the universe), your long properties in some cases, depending on the value, will get rounded.

The Cosmos team should allow developers to implement triggers and stored procedures in a language other than Javascript (the worst language in the history of the universe), but given that they don't support spatial and have never heard of DateTimeOffset, I'm not holding my breath.

**Comment by 92dev** [comment]
Yeah, just did a deep dive into this shit, it's 100% like @jackbond mentioned,
it's an issue with the Azure portal converting values in javascript and managing it in a weird way
the thing is I used the portal as a source-of-truth (which made sense at the time lol)

after inspecting with the SDK itself - since the value in the DB differs from the one I saw - it works just fine 🙂 

all in all, I guess there will be 0 chance of Azure web team ever fixing it (the UI is already all over the place with different icons themes and people maintenance teams)

**Comment by jackbond** [comment]
@92dev Converting to string works great, until you need to order signed integers. If you want ordering, your converter will need to convert the long to ulong, and then convert to string (and don't forget you'll need to pad left with zeros.) It goes without saying this is a truly ugly solution.

Funny how they fail to mention all of this in their marketing. An enterprise database which can't handle 64 bit integers. Oh, and they've only known about this FOR SEVEN YEARS. But gee, thanks for all the new AI fluff.

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/2799232/241717a2-a338-46f8-bd3c-79379c1c2b26)

**Comment by Pilchie** [comment]
@jackbond - for queries where you need the numeric value where you store something as a string, consider using the [`STRINGTONUMBER`](https://learn.microsoft.com/en-us/cosmos-db/nosql/query/stringtonumber) to convert it to a number inside the query engine.  Also tagging @sboshra.
