### ISSUE TITLE
UpsertItemAsync with ItemOptions.IfMatchEtag not work sometimes

### ISSUE THREAD

**Issue by htzhang2** [Azure/azure-cosmos-dotnet-v3#4449]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
UpsertItemAsync with same IfMatchEtag value both return success

**To Reproduce**
1. Retrieve etag value from existing item with ReadItemAsync
2. Call to UpsertItemAsync with  IfMatchEtag value from step 1.
3. Another call to UpsertItemAsync with  IfMatchEtag value.

**Expected behavior**
1. One call succeed
2. Another call fail with CosmosException.PreConditionFailed

**Actual behavior**
Both calls succeed sometimes

**Environment summary**
SDK Version: 3.38.1
OS Version (e.g. Windows, Linux, MacOSX): Windows

**Additional context**
CosmosDb is strong consistency

**Comment by bartelink** [comment]
>Both calls succeed sometimes

So you're saying you have a repro where two different writes succeed based off the same etag, i.e. the written data from one of the cases is lost?
That's declaring SELECT broken, and is highly unlikely to be the case - you'll need to rig a real test case harness for this rather than just loosely alleging 'sometimes'. 
If this is not what you mean, I'd suggest modify the expecation
