### ISSUE TITLE
Clarification on versioning practices of preview packages

### ISSUE THREAD

**Issue by walliski** [Azure/azure-cosmos-dotnet-v3#4517]
As the discussions do not seem to get a lot of attention overall, moving this here, as it would be quite important to know what's happening with the versions.

### Discussed in https://github.com/Azure/azure-cosmos-dotnet-v3/discussions/4444

<div type='discussions-op-text'>

<sup>Originally posted by **walliski** April 22, 2024</sup>
I tried looking for release notes etc, but could not really find anything on this.

In versions before 3.38 we got a `-preview` package together with the normal release. As I have understood it that preview package used to be the same as the normal one, but also contain the Preview features. Not sure if I have understood this part wrong?

After 3.38, it seems like the preview packages are now released at random times, before the real version. Does this also mean that the preview packages are now treated as "beta" packages, where also other functionality than the preview features should be considered unstable, or is the release cadence of the old "-preview" packages just detached from the GA ones now?

![image](https://github.com/Azure/azure-cosmos-dotnet-v3/assets/5192434/346f78f3-ca4f-4e83-8e28-6481498d87ed)
</div>

**Comment by FabianMeiswinkel** [comment]
Starting with 3.38.0 and 3.39.0-preview we release the preview package with a +1 minor version. Why? It makes it easier to move from normal to preview version - because now the preview version looks like an "upgrade". Also exposes better that when you move "back" from preview to normal version a few public APIs might be missing.

So 3.38.0 and 3.39.0-preview align as well as 3.39.0 and 3.40.0-preview etc.
