### ISSUE TITLE
Operation 'POST' on resource 'dbs' is not allowed through Azure Cosmos DB endpoint. Please switch on such operations for your account, or perform this operation through Azure Resource Manager, Azure Portal, Azure CLI or Azure Powershell

### ISSUE THREAD

**Issue by pjohnst5** [Azure/azure-cosmos-dotnet-v3#4552]
>We are continuously addressing and improving the SDK, if possible, make sure the problem persist in the [latest SDK version](https://www.nuget.org/packages/Microsoft.Azure.Cosmos).

**Describe the bug**
Hello, I am using managed identity to connect to a cosmos db from a .net application (I also work for Microsoft, Azure)
I see on the following error when trying to `CreateDatabaseIfNotExistsAsync()`:
```
Response status code does not indicate success: Forbidden (403); Substatus: 0; ActivityId: ff8c1b3c-0bd5-47da-9113-066f3bd0c3e9; Reason: ({"code":"Forbidden","message":"\"Operation 'POST' on resource 'dbs' is not allowed through Azure Cosmos DB endpoint. Please switch on such operations for your account, or perform this operation through Azure Resource Manager, Azure Portal, Azure CLI or Azure Powershell
```

My expectation here is to be able to create DBs and Containers if they do not exist, using Managed Identity

I have already made a `az cosmosdb sql role` with sufficient permissions, and assigned it to the MI as well as me (for testing):
```
az cosmosdb sql role definition show --account-name subnetdelegator-westus-yinuh -g cosmostest4 -i 5d4d8955-51ad-5f1a-a377-894715803041
{
  "assignableScopes": [
    "/subscriptions/9b8218f9-902a-4d20-a65c-e98acec5362f/resourceGroups/cosmostest4/providers/Microsoft.DocumentDB/databaseAccounts/subnetdelegator-westus-yinuh"
  ],
  "id": "/subscriptions/9b8218f9-902a-4d20-a65c-e98acec5362f/resourceGroups/cosmostest4/providers/Microsoft.DocumentDB/databaseAccounts/subnetdelegator-westus-yinuh/sqlRoleDefinitions/5d4d8955-51ad-5f1a-a377-894715803041",
  "name": "5d4d8955-51ad-5f1a-a377-894715803041",
  "permissions": [
    {
      "dataActions": [
        "Microsoft.DocumentDB/databaseAccounts/readMetadata",
        "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/write",
        "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/*",
        "Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/items/*"
      ],
      "notDataActions": []
    }
  ],
  "resourceGroup": "cosmostest4",
  "roleName": "DB Writer Role",
  "type": "Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions",
  "typePropertiesType": "CustomRole"
}
```
The goal here is to be able to create a cosmos db, which gives the managed identity sufficient privileges to create dbs and containers

**To Reproduce**
```
var credential = new ManagedIdentityCredential('clientid');
_cosmosClient = new CosmosClient(endpointUri, credential);
_cosmosClient.CreateDatabaseIfNotExistsAsync("New DB"); // Fails
```

**Expected behavior**
I would like the .Net app to be able to create dbs and containers, since the .net app has sufficient privileges per the `az cosmosdb sql role definition`

**Actual behavior**
Failure seen in description

**Environment summary**
SDK Version: `3.41.0`
OS Version (e.g. Windows, Linux, MacOSX): `Windows`

**Additional context**
Add any other context about the problem here (for example, complete stack traces or logs).

**Comment by pjohnst5** [comment]
Ah, this may be why:
in the db that fails for me, I have this set:
`"disableKeyBasedMetadataWriteAccess": true,`

And I believe that the db creation needs keys?

However, with a different db with `"disableKeyBasedMetadataWriteAccess"` set to `false`, db creation also fails there (but container creation succeds)

So still would be nice to be able to create dbs when`"disableKeyBasedMetadataWriteAccess"` is `false`

**Comment by ealsur** [comment]
This is not a client SDK issue. Client SDKs do not perform any of these validations. According to public documentation, data plane SDKs cannot perform management plane operations with MSI: https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#permission-model

That is what the error you are getting says.

`disableKeyBasedMetadataWriteAccess` seems to be a configuration on the resource, again, this is unrelated to the client SDK, it is not a configuration that the client sees or understands and the client is not validating, the HTTP 403 response comes from the service. Please reach out to the service or support team for clarification.

**Comment by pjohnst5** [comment]
Okay, @ealsur, in that case, will these methods be removed in the future, to avoid this sort of confusion
`CreateDatabaseIfNotExistsAsync`
`CreateContainerIfNotExistsAsync`
?

**Comment by pjohnst5** [comment]
Otherwise, why do they exist?

**Comment by ealsur** [comment]
You can perform Create Database or Create Container when authenticating with Keys, so no, they will not be removed.

> Otherwise, why do they exist?

This SDK was created 4+ years ago, back then, the only auth possible was keys. MSI was introduced later on. You cannot remove APIs from a library, it's a breaking change. And in any case, for customers that want to keep using keys, they work perfectly fine.

**Comment by pjohnst5** [comment]
Gotcha thanks

**Comment by FrancescoSaverioZuppichini** [comment]
anyone has a fix?

**Comment by weikanglim** [comment]
I ran into this myself. I believe that what is needed is to create an RBAC (not SQL role) permissions to enable the control-plane access.

Minimally, you'll need to assign RBAC for `Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/*`, you can see what this grants in the security [guide](https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/databases?context=%2Fazure%2Fcosmos-db%2Fnosql%2Fsecurity%2Fcontext%2Fcontext#microsoftdocumentdb). Unfortunately, no built-in role exists so a new custom role definition is required.

If this is just for dev/test, you can assign the built-in role '[DocumentDB Account Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/databases#documentdb-account-contributor)' to see if it works.

**Comment by ProbablePrime** [comment]
Came across this when "upgrading" an APP from keys to Managed Identities. App manages some of its own CosmosDB containers using app code to enforce things like partitioning etc. 

The solution i decided to operate with here is to:
1. Ensure the managed identity has: "Cosmos DB Operator" as a role or something similar if you wish to further restrict permissions
2. Create a `CosmosClient` in your app for Data queries
3. Create a Management SDK `ArmClient`
4. Both using the same identity, your managed one.
5. Wrap `Create<X>IfNotExistsAsync`, in your own interface like `ICosmosManagement`
6. Implement the interface twice:
    * a key based approach that goes through `ComosClient` -> easy quick Adapter pattern class
    * an identity based approach that goes through `ArmClient` -> slightly harder as has to manage resource groups etc.
8. Using DI, provide only ICosmosManagment to your app code.

End result is something like:
```
ICosmosManagement manager = .... //Get from DI
Database products = manager.GetOrCreate("products");
```

With many caveats that are from my actual app, this effectively meant we could run in a Key and Identity configuration with minimal changes to the areas that relied on the raw create if not exist functions. Other team members can just use the wrapper and now not care about what API its going through. That's a configuration/operational thing.

As a further disclaimer, ideally your IaC should create the containers, as that can lead to things like policy management around billing in regards to throughput. I intend to do that eventually but needed this wrapper for the switchover.

---

One important item, the error message here is usually something like "cannot be authorized by AAD token in data plane. Learn more: https://aka.ms/cosmos-native-rbac."

Due to the period on the end of that link, my terminal and other places such as Azure Dev Ops lead us to literally "https://aka.ms/cosmos-native-rbac." which doesn't work.

The error message should probably separate the url from the period somehow. I'm not sure where to direct that inquiry though.
