### ISSUE TITLE
How does one delete a sproc?

### ISSUE THREAD

**Issue by kentcb** [Azure/azure-cosmos-dotnet-v3#46]
**Is your feature request related to a problem? Please describe.**
I am creating a sproc programmatically. The first time it's created, the creation invocation works (`CreateStoredProceducreAsync`). The second time, I get a `409` with no explanation. I figured out that it's complaining because that sproc has been created already. By appending a random string on the name, it then worked.

I'd obviously rather delete the sproc and create a replacement, but I can't see any API allowing this in the `Microsoft.Azure.Cosmos` client.

**Describe the solution you'd like**
A simple way to delete a sproc programmatically.

**Describe alternatives you've considered**
Recreating the entire container (nope, especially impossible when production data is in the container).

**Comment by j82w** [comment]
Hi @kentcb,

In the v3 SDK everything is reference via objects instead of ids and URLs. When you create a stored procedure you get that [reference object](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/StoredProcedure/CosmosStoredProcedure.cs). From that object you can delete the stored procedure. You can also read and replace the stored procedure with the reference CosmosStoredProcedure object. 

```
// If you don't have a reference to the existing stored procedure.
await container.StoredProcedures[sprocId].DeleteAsync();

// To get a reference from the created stored procedure
CosmosStoredProcedure sproc = await container.StoredProcedures.CreateStoredProceducreAsync(scriptId, File.ReadAllText(scriptFileName));
await sproc.DeleteAsync();
```
