### ISSUE TITLE
Allow GetChangeFeedProcessorBuilder to return a list of strings

### ISSUE THREAD

**Issue by MrAntix** [Azure/azure-cosmos-dotnet-v3#4789]
**Is your feature request related to a problem? Please describe.**
Not a problem really, it can be done using the stream, but it would be nice

**Describe the solution you'd like**
I would like GetChangeFeedProcessorBuilder[string], This will allow me to selectively deserialize my change data

**Describe alternatives you've considered**
The stream delegate can be used, but al list of strings would be a convenient API

**Additional context**
Many thanks

**Comment by philipthomas-MSFT** [comment]
Hello @MrAntix,

Thank you for reaching out to us and for utilizing our product!

To ensure I fully comprehend your request—I want to avoid any misinterpretation—are you suggesting that, instead of `GetChangeFeedProcessorBuilder<T>` returning an `IReadOnlyCollection<T>` as originally intended, it would be more advantageous for it to return an `IReadOnlyCollection<string>`?

Wouldn't it be more efficient to serialize the collection of objects into a collection of strings on your end? Serialization, especially for large or complex objects, can be resource-intensive. Performing this for every request across all customers could introduce unnecessary overhead and negatively impact performance.

For example:

```csharp
IEnumerable<string> serializedStrings = docs.Select(doc => (string)JsonConvert.SerializeObject(doc));

**Comment by philipthomas-MSFT** [comment]
Thank you again for the clarification, @MrAntix.

I completely understand your request and the reasoning behind it. However, at this time, given the potential for large datasets, increased memory consumption, and the overhead associated with serialization—particularly in the context of a change feed request—it would be more prudent to support `Stream`. This allows each individual customer the flexibility to decide how and when the `Stream` should be read, optimizing for their specific use case.

Your current workaround is sufficient and supports your use case under the current circumstances. That said, we genuinely appreciate your suggestion. We encourage you to continue providing feedback and suggestions on how we can make the product even better. We are here to listen and act accordingly, ensuring that our customers have the best possible experience.

Thank you for your continued input and support, and please don't hesitate to reach out with any further feedback or questions.

**Comment by MrAntix** [comment]
Thats fine, all the best now
