### ISSUE TITLE
Unable to create CosmosClient without Newtonsoft.Json

### ISSUE THREAD

**Issue by lindsve** [Azure/azure-cosmos-dotnet-v3#4900]
**Describe the bug**
I'm currently trying the new version of the SDK (3.46.0) and I'm unable to create a CosmosClient without referencing Newtonsoft.Json explicitly.

**To Reproduce**
I've disabled the check for Newtonsoft in the project file:
```
<PropertyGroup>
    <AzureCosmosDisableNewtonsoftJsonCheck>true</AzureCosmosDisableNewtonsoftJsonCheck>
</PropertyGroup>
```

I've configured the CosmosClient to use System.Text.Json:
```
var cosmosClientOptions = new()
{
    ConnectionMode = ConnectionMode.Gateway,
    UseSystemTextJsonSerializerWithOptions = new JsonSerializerOptions
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        IgnoreReadOnlyProperties = true
    }
};

var client = new CosmosClient(uri, servicePrincipal, _cosmosClientOptions);
```

**Expected behavior**
I'd expect this to run fine without adding an explicit dependency on Newtonsoft.Json.

**Actual behavior**
When I run this I get the following exception:
```
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.

File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Microsoft.Azure.Cosmos.DocumentClient..ctor
   at Microsoft.Azure.Cosmos.ClientContextCore.Create(CosmosClient cosmosClient, CosmosClientOptions clientOptions)
   at Microsoft.Azure.Cosmos.CosmosClient..ctor(String accountEndpoint, AuthorizationTokenProvider authorizationTokenProvider, CosmosClientOptions clientOptions)
   at Microsoft.Azure.Cosmos.CosmosClient..ctor(String accountEndpoint, TokenCredential tokenCredential, CosmosClientOptions clientOptions)
```

**Environment summary**
SDK Version: 3.46.0
OS Version macOS 15.1.1

**Comment by Pilchie** [comment]
This is expected - the reason we have the check in the first place is to ensure that you do have a reference to Newtonsoft.Json.  It *is* required.

Even if you configure the client to use S.T.J to serialize your own types, there are various places internally where the SDK still uses Newtonsoft.Json.

We do hope to eliminate that dependency fully eventually and give you the ability to fully use either STJ or Newtonsoft, but that work isn't complete yet.

**Comment by lindsve** [comment]
Ah, I misunderstood the change then, I thought it was no longer needed after changing to use S.T.J

**Comment by Hargravejason** [comment]
If Newtonsoft.Json is required to use this library, it should be listed as a Dependency.  I also was under the impression that we no longer needed as it is no longer listed on NuGet as a Dependency. 

See https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.46.0 

Dependencies:  
>.NETStandard 2.0
>   [Azure.Core](https://www.nuget.org/packages/Azure.Core/) (>= 1.44.1)
>   [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/) (>= 6.0.0)
>   [Microsoft.Bcl.HashCode](https://www.nuget.org/packages/Microsoft.Bcl.HashCode/) (>= 1.1.0)
>   [System.Buffers](https://www.nuget.org/packages/System.Buffers/) (>= 4.5.1)
>   [System.Collections.Immutable](https://www.nuget.org/packages/System.Collections.Immutable/) (>= 1.7.0)
>   [System.Configuration.ConfigurationManager](https://www.nuget.org/packages/System.Configuration.ConfigurationManager/) (>= 6.0.0)
>   [System.Diagnostics.DiagnosticSource](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/) (>= 8.0.1)
>   [System.Memory](https://www.nuget.org/packages/System.Memory/) (>= 4.5.5)
>   [System.Net.Http](https://www.nuget.org/packages/System.Net.Http/) (>= 4.3.4)
>   [System.Numerics.Vectors](https://www.nuget.org/packages/System.Numerics.Vectors/) (>= 4.5.0)
>   [System.Runtime.CompilerServices.Unsafe](https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/) (>= 6.0.0)
>   [System.Text.RegularExpressions](https://www.nuget.org/packages/System.Text.RegularExpressions/) (>= 4.3.1)
>   [System.Threading.Tasks.Extensions](https://www.nuget.org/packages/System.Threading.Tasks.Extensions/) (>= 4.5.4)
>   [System.ValueTuple](https://www.nuget.org/packages/System.ValueTuple/) (>= 4.5.0)

**Comment by jasonshave** [comment]
Could you please update the documentation then to include this as a dependency?

**Comment by gottagetgit** [comment]
I just spent so much time trying to debug why using the CosmosDB package wasn't compiling.  Just had to install Newtonsoft.Json and it fixed it. PLEASE add it as a dependency.

**Comment by kipusoep** [comment]
I have been confused as well since we now updated to v3.46.0 and thought we can skip JSON.NET completely.
Because why did you guys introduce `AzureCosmosDisableNewtonsoftJsonCheck` then?

**Comment by Pilchie** [comment]
You can serialize your own types without JSON.NET, but internally the SDK does still require a version of it to be loaded.  We removed the direct dependency due to a tricky issue - we referenced a version with a security vulnerability, but the fix was only in a version that had breaking changes.  We verified that *our* use wasn't affected by either the security vulnerability or the breaking change, but we can't make that choice for customers.

Eventually we do plan to remove our internal use of Newtonsoft.Json, but that work isn't completed yet.

**Comment by kipusoep** [comment]
I understand the reasoning et al, it was just a really confusing situation and proper documentation about these changes would've been helpful.

**Comment by ChefBDawg** [comment]
This is a joke. Trying to upgrade to System.Text and remove Newtonsoft ends with constant conflicts between the two serializers due to dependencies like this. Upgrading to System.Text is literally not possible in a large scale system that is forced to reference both. STILL having internal dependencies to Newtonsoft is a farce.

**Comment by Matthewsre** [comment]
@Pilchie , for upgrading from 3.45.2 to 3.46.1 (only isolated change in the project), I also added the latest Newtonsoft.Json package (13.0.3) and started getting the following error on build:

> "Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'"

The error was not very clear of what the actual problem was, but fortunately I came across [this post]( https://mikaelkoskinen.net/post/net-core-standard-missing-compiler-required-member) that help me identify that in addition to adding the Newtonsoft.Json reference, I also had to add a reference to Microsoft.CSharp because I am using dynamic.

Additional context:

- My project targets "netstandard2.0".
- The dependencies in Newtonsoft.Json for 13.0.3 (https://www.nuget.org/packages/Newtonsoft.Json/13.0.3#dependencies-body-tab) and 10.0.2 (https://www.nuget.org/packages/Newtonsoft.Json/10.0.2#dependencies-body-tab) are both the same.
- I also see the in the dependencies between 3.45.2 (https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.45.2#dependencies-body-tab) and 3.46.1 (https://www.nuget.org/packages/Microsoft.Azure.Cosmos/3.46.1#dependencies-body-tab) that they only have the Newtonsoft.Json dependency as a difference.

Not sure exactly what is going on here, but this isolated package update was more of a headache from the breaking change than I was anticipating. It looks like there may be other bugs at play here as well.

I feel like this breaking change moves away from the reliability of dependency mapping that I have come to trust and rely on, and was introduced more as a workaround to address a flag/flaw in the vulnerability detection (which is also very appreciated and important!).

**Comment by Pilchie** [comment]
It's likely to happen as part of the next major version of the .NET Cosmos SDK. We haven't started work on that in earnest yet, but we expect we will start working on it in the second half of the year.
