### ISSUE TITLE
ReplaceThroughputAsync throws an exception when scaling back throughput

### ISSUE THREAD

**Issue by adrianknight89** [Azure/azure-cosmos-dotnet-v3#538]
I created a database with 400 shared throughput and then added 20 containers. The throughput was increased to 2000 (which I expected). When I deleted every container, the throughput stayed 2000. Now, when I invoked `ReplaceThroughputAsync` with 400 throughput, I got an exception saying that the minimum throughput must be 2000. The Azure portal has the same issue and I'm not allowed to scale it back to 400. Is this by design or a bug? It seems like `ReplaceThroughputAsync` is only meant to be used when increasing the throughput - not decreasing it.

**Comment by j82w** [comment]
@adrianknight89 since this is not an SDK specific issue can you send an email to "askcosmosdb@microsoft.com" with your question.

**Comment by adrianknight89** [comment]
Why do you think this is not an SDK specific issue? Do you mean this is by design and not a bug?

**Comment by j82w** [comment]
You said Azure Portal is hitting the issue too. The portal does not use the .NET SDK. If they are both hitting the error then it's most likely coming from the Cosmos DB service. Since the exception is coming from the service the best way to get your question answered is via "askcosmosdb@microsoft.com".
