### ISSUE TITLE
BatchOperationResult should use Stream

### ISSUE THREAD

**Issue by j82w** [Azure/azure-cosmos-dotnet-v3#670]
BatchOperationResult uses MemoryStream. All other types in Cosmos use Stream.

**Comment by j82w** [comment]
Should Batch be split like all the other types where Stream and Typed responses are 2 different objects?

**Comment by kirankumarkolli** [comment]
A Batch composition is independent of stream or typed. For operations inside a way customer can get response as either stream or typed. 

One way to look at it Batch composition allows for IN in both stream or typed ways. 
BatchResponse enables reading responses (i.e. OUT) as either stream or typed.

With this model its expected developer will make the choice on the response. 

```c#
    public abstract class Batch
    {
        ...
        public abstract Batch CreateItemStream(Stream streamPayload, BatchItemRequestOptions requestOptions=null);
        public abstract Batch CreateItem<T>(T item, BatchItemRequestOptions requestOptions=null);
        ...
    }

    public class BatchResponse : IReadOnlyCollection<BatchOperationResult>
    {
        ...
        public virtual BatchOperationResult this[int index] { get; }
        public virtual BatchOperationResult<T> GetOperationResultAtIndex<T>(int index);
        ...
    }
```

**Comment by kirankumarkolli** [comment]
If the question was why not have responses like below
```C#
    public class BatchResponse<T> : IReadOnlyCollection<BatchOperationResult>
    {
        ...
       public virtual BatchOperationResult<T> this[int index] { get; }
        ...
    }

    public class BatchResponseStream : IReadOnlyCollection<BatchOperationResult>
    {
        ...
       public virtual BatchOperationResult this[int index] { get; }
        ...
    }
```

Batch envelope contract is currently internal and binary format. When this contract goes public in an application consumable form then we can explore that path.

**Comment by kirankumarkolli** [comment]
> BatchOperationResult uses MemoryStream. All other types in Cosmos use Stream.

It needs attention for consistency. 
Personally I would prefer to align with Stream for consistency for now and later move to Span<T> part of contracts. Hybrid contract might be mis-leading.

**Comment by j82w** [comment]
1. Do we have any scenarios where customers will be using both typed and stream APIs?
2. Every other typed API disposes of everything for the user. If the user does all typed APIs this is the only response in the SDK that requires the user to dispose of it. I don't think users will realize that only this one response type needs to be diposed of.

**Comment by abhijitpai** [comment]
@j82w - In regard to Dispose, MemoryStream need not be disposed per .net documentation, and we create MemoryStreams when we serialize typed objects, so users do not necessarily need to call Dispose unless they use the stream APIs and pass other kinds of Streams. 

@kirankumarkolli - The reason we don't have BatchResponse<T> is because the entities in the response may not all conform to the same T.

Using MemoryStream in BatchOperationResult is based on feedback that returning as Stream when we know that the data is completely available in memory leads to sub-optimal caller code and lower E2E perf; also MemoryStream is a derived class of Stream. But if there is still confusion, can change this.
