### ISSUE TITLE
How could we handle ReadItemAsync if item not existed in collection

### ISSUE THREAD

**Issue by kevinding0218** [Azure/azure-cosmos-dotnet-v3#692]
For the `ReadItemAsync()` method, if an item does not exist in the collection, will throw a CosmosException of status code "NotFound" (e.g, `catch(CosmosException ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)`), so instead of implementing the business logic in the `catch(...)` statement, could we just handle the _item not existed_ case outside the catch statement but in the try statment? For example, if the `ItemResponse<T>` could contain some flag to identity if the item existed or not? or is there a way just by check ` if (itemResponse<T>.Resource == null)` ?

Thank you very much for your help!

**Comment by j82w** [comment]
Hi @kevinding0218 , 

Do you just need to verify the object exists or do you need the object for the business logic after the read?

**Comment by j82w** [comment]
You could do something like this:

```
ItemResponse<ToDoActivity> response = null;
            try
            {
                response = await this.Container.ReadItemAsync<ToDoActivity>();
            }
            catch (CosmosException ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound) { }

            if(response == null)
            {

            }
```

if(

**Comment by kevinding0218** [comment]
@j82w , yes that is exactly what I'm currently doing, by using the status code with exception filter to handle the non-existed case. I am just wondering why would non-existed document consider as an exception rather than just returning a null object? So that we don't need to handle it in the exception filter case.

**Comment by j82w** [comment]
This is a very long running debate. We initially started v3 out with it returning null. We got feedback from central .NET team and central SDK team that it should throw. The reason why is 404 is considered an exception according to the [http standard](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) and most developers expect it throw. We had several users report it thinking it was a bug.

If you want you can use the Stream APIs. They only throw argument exceptions, and return all other exceptions as a status code.

T item = null;
using(ResponseMessage responseMessage = await this.Container.ReadItemStreamAsync()){
if(responseMessage.StatusCode == System.Net.HttpStatusCode.NotFound){
   // Do other logic
}

 item = jsonSerializer.Deserialize<T>(responseMessage.Content);
}

**Comment by bartelink** [comment]
To save me thinking/looking it up a) what does v2 do b) can/does the xmldoc for `ReadItemAsync` mention this as being the advised approach (I agree with the stance)

**Comment by j82w** [comment]
v2 throws on 404 not found. I believe that is where a lot of the confusion came from. If this is something enough users want we could add a client option to now throw on 404. The default it will throw to avoid a breaking change, but would give users the option.

**Comment by bartelink** [comment]
As long as you mean an option on an individual call, i.e. adding a `bool dontThrowOnFailure=false` or adding a `TryReadItemAsync` that can yield a `null`. Most importantly I believe the fact that V3 aligns with how v2 works will save people a lot of hair pulling when inevitably doing porting work without.

**Comment by j82w** [comment]
I was thinking more of a CosmosClientOptions with a bool DoNotThrowOnNotFound . That way the entire client is configured that way to avoid needing to specify on every call. The typed responses only have a status code which should be good enough to see 404. They don't have an error message or other info needed for debugging. If users want a truly exceptionless experience they can use the stream APIs.

**Comment by bartelink** [comment]
I feared you might have meant that - making stuff modal like that is a recipe for 
a) lots of tests your side
b) problems for library code that gets handed a Container to operate against.
At my call site, I'd like to have full control and in-your-face visibility as to what we're dealing with, without out-of-band modalities wreaking havoc.
But, back to my main point - I'm happy if the OOTB default and natural porting target from a V2 call behaves similarly, so I have no actual concerns at this point in time.

**Comment by j82w** [comment]
That's a good point. I agree this shouldn't be added to the SDK. There is enough solutions with the current implementation.

**Comment by bartelink** [comment]
@j82w I have [some code](https://github.com/jet/equinox/blob/329d6843825ddc21bec77dbff39de081e55f20f9/src/Equinox.Cosmos/Cosmos.fs#L325) :-

```
        member container.TryReadItem(partitionKey : PartitionKey, documentId : string, ?options : ItemRequestOptions): Async<float * ReadResult<'T>> = async {
            let options = defaultArg options null
            let! ct = Async.CancellationToken
            try let! item = async { return! container.ReadItemAsync(documentId, partitionKey, requestOptions = options, cancellationToken = ct) |> Async.AwaitTaskCorrect }
                if item.StatusCode = System.Net.HttpStatusCode.NotModified then return item.RequestCharge, NotModified
                // NB `.Document` will NRE if a IfNoneModified precondition triggers a NotModified result
                else return item.RequestCharge, Found item.Resource
            with CosmosException (CosmosStatusCode System.Net.HttpStatusCode.NotFound as e) -> return e.RequestCharge, NotFound
                // NB while the docs suggest you may see a 412, the NotModified in the body of the try/with is actually what happens
                | CosmosException (CosmosStatusCode System.Net.HttpStatusCode.PreconditionFailed as e) -> return e.RequestCharge, NotModified }
```
This has been ported direct from V2; I'm wondering whether `NotModified` continues to not throw as previously (as you can see above I happen to handle it both ways, but in general I'd like to [continue to] avoid the exception in the `412` case). (Yes I could look myself but I'm sure someone will benefit from the discussion at some point)

**Comment by bartelink** [comment]
It seems based on my code in https://github.com/jet/equinox/pull/144 (specifically https://github.com/jet/equinox/blob/400b2ab320c0b9149f4ea6c48a6066d9d4f00559/src/Equinox.Cosmos/Cosmos.fs#L336) that there is a change in behavior wrt the 304 it used to (arguably surprisingly) not throw, but it now throws [the `304`]. Clearly the fix in my case is to drop to the `TryReadItemStreamAsync` and avoid all throws

**Comment by hari4147** [comment]
Is there any implementation to check the data exist in the database without sending the whole data. like simply return a Boolean. This kind of feature really helpful, if there is lots business scenarios only required the existence of the data in the data base, To fulfill the requirements we currently bring the stream of data from the database. This will reduce the application performance.

**Comment by bartelink** [comment]
@hari4147  Doing an `EXISTS` query is not likely to be more efficient RU wise than a point read for small items. Best way to verify that is by trying the query in your favorite query tool.
There is a flag to not return results in the request options (which does reduce network traffic and latency as you suggest), but you'll still pay the RUs to ready the body on a read item call with that flag - its most common use is in the delete request (which would otherwise return the body).
On the client, assuming a point read is the tool for your job, its clear that `ReadItemStreamAsync` (and skipping the body deserialization) is what you'd do if you go down that route.

I'd suggest there's probably a way to address it in your overall process at a higher level though - if you are doing a pre-flight check before doing something, you probably want to grab the etag and then do a conditional update and/or an insert conditional on the item not existing.

**Comment by hari4147** [comment]
Thank you for your response. Is there any way to stop 404 exceptions, when
the ReadItemAsync() is not found the document. This will leads high amount
exception logging in application insights.

**Comment by bartelink** [comment]
Yes; call `ReadItemStreamAsync`, which is a lower level API which does not have the same throwing semantics - there are links and snippets above

**Comment by rf-0** [comment]
@j82w Is there a reason why `ReadItemStreamAsync` `RequestCharge` is always 0?

I'm getting the request charge from `response.RequestMessage.Headers.RequestCharge`

Using `<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.31.2-preview" />`

**Comment by bartelink** [comment]
@rf-0 I've never seen problems with what you've described ([similar code](https://github.com/jet/equinox/blob/b0fb2e7549afbbee847dd629f31a01c2957740fd/src/Equinox.CosmosStore/CosmosStore.fs#L355))

**Comment by rf-0** [comment]
@bartelink I updated my question with some more context but will come back after I run some tests with a different setup (not using the preview package in this case and maybe running the cloud version instead of the emulator).

**Comment by TREVORPINKS** [comment]
I just wanted to chime in and say that exceptions should be reserved for edge cases or scenarios that don't happen often. 

Checking to see if a record exists or not doesn't fit that criteria to me.   Therefore,  ReadItemStreamAsync seems like the better way to go.

**Comment by baptistepa** [comment]
I am surprised to stumble on this thread... While creating some queries for cosmos, I was stunned when I saw that we got a CosmosException because an item was not found... Now we have to catch that exception and check status code to then return null in all of our methods where we do a call to Cosmos... We should just receive null in the first place from the SDK.

**Comment by bartelink** [comment]
@j82w I think you should edit your [second comment](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/692#issuecomment-521368031) to a) fix the mangle b) qualify the bad advice of letting it throw given you don't end up saying that in the end 

I've also updated my snippet which one had way too much just-in-case catches: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/692#issuecomment-521936888

----

cc @ealsur (because j82w does not seem to be active in the repo atm and you're the most consistently responsive (aka an easy victim for atting!)

I think baptistepa raises a good overall point though:
- based on the discussion above, it's for the best that `ReadItemAsync` throws (equivalent to V2 SDK etc)
- but [the xmldoc for `ReadItemStreamAsync` and `ReadItemAsync`](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs#L379-L456) leaves a heck of a lot for the reader to infer and/or search up from the docs etc

I feel it's thus high time that this is addressed; my asks:
- `ReadItemAsync`:
  - `ToDoActivity` in the sample should include an `_etag` to illustrate the `remark`
  - the doc should refer to the throwing on error including expected errors such as 404 and 304
  - the doc should mention ReadItemStreamAsync as the way to explicitly manage such an anticipated conditon
- `ReadItemStreamAsync`
  - can continue to show how to manipulate the low level stream in general. _But this should be as a final example_
  - should present the canonical mechanism for doing what 80% of worldwide usage of the API is trying to accomplish - **avoid an exception in an expected no body scenarios** - deserialize it just like ReadItemStream would
    -  i.e. presenting an alternative to the low level stream manipulation in the example which instead does, i.e.: 
        ```csharp
        var content = rm.EnsureSuccessStatusCode().Content
        return container.Database.Client.ClientOptions.Serializer.FromStream<ToDoActivity>()
        ```
  - grammar: which wraps -> that wraps
- Deserialization helper in the box cc @kundadebdatta @Maya-Painter  (because you guys are in the throes of deserialization polishing atm)
  
  I'm carting around this extension method which works for me, but I had to traverse the source 2-3 years ago to arrive at it:
  
  ```fsharp 
  member private container.DeserializeResponseBody<'T>(rm: ResponseMessage): 'T =
  rm.EnsureSuccessStatusCode().Content
  |> container.Database.Client.ClientOptions.Serializer.FromStream<'T>
  ```
     
  The problem is that hacks like this rot, and it really should not be on the user to figure them out and/or maintain them, as there are doubtless problems with it.

  **Unless there's a better option (I'd love if there was), I think there should be something in the box that does this cleanly**

----

Ideally one of you guys writes up an Issue covering finally putting this to bed; if not I'll paste the above text into an issue in a few days time and we can work from there... NOTE it's definitely a two parter:

1. establish best practice of how to conditionally deserialize an item and/or document it somewhere
2. ensure that `ReadItemAsync` and `ReadItemStreamAsync` cover this mainline scenario including actually mentioning the most common need and how to address it

**Comment by ealsur** [comment]
@bartelink reading this thread I'm still not sure I fully understand.

Point 1 I guess makes sense, in general you'd want to attempt to deserialize only on a successful request. Not sure exactly **where** this would go though. Please create an Issue to track this.

Point 2 though:

The SDK in general throws exceptions for any non-success StatusCodes when using the Typed APIs. It's not just for 404. If, for example, the service returns an HTTP 503 because it's facing some issue, then you'd get that in the StatusCode of the CosmosException. Or if you get an HTTP 400 because of input validation.

The only thing I see possible is adding the most relevant/important list of StatusCodes with their meaning. Would you also expect that on CreateItemAsync we show how to handle a HTTP 409? or DeleteItemAsync? 

There are a lot of questions here that really point at Service behaviors that we cannot magically change in the SDK. The service has a REST API, the contract is that an HTTP GET to fetch a document returns 404 if the document doesn't exist or the full document it does. **That we cannot change on the SDK**. If a user would like a different operation (for example, an API that returns a boolean when a document exists) then that needs to first exist in the Service, for SDKs to implement it. We can gladly add it when that happens. But I would not entertain complains about service behavior, I am all for having a conversation about how to make users' life better with the things we can change though.

SDKs are implemented and depending on the language, they might communicate errors in a certain way. This SDK originally had no exceptions before GA (3.0.0), but the community response was negative, we received pushback and had to introduce exceptions for any non-success response.

This SDK is not outside of the umbrella of the Azure SDKs for .NET and thus, some behaviors cannot diverge. One of them is: https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-errors. Which says that if the StatusCode is not a success, an exception should be thrown.

**Comment by bartelink** [comment]
This is about reading items, only. You know this, but spelling it out:
1. You need a way to deal with the case of there not being a value. It's a very normal thing to not handle in some global handler. It's why dictionary has a TryGetValue and a GetValue.
2. For the ifnonematch case you are saying "the chances are I have this already, but given me the update if not". The last thing I want/need if it's there is an exception saying "yes you were right, here's a smack on the head"

While it's technically true that dropping own a level to custom decoding is a viable workaround, it's only that.

I fully get that the service behavior is the service behavior. This is about the experience of using the SDK as a whole. I also get that you can't and sjouldn't change the semantics.

I was describing it in a neutral way leaving it open for you guys to pick a way to handle the problem cleanly, but the bottom line is that this is simply not good enough.

Absolutely the documentation is part of it.

But spelling it out: Either there should be a dedicated TryGet API, or something that makes the "use the lower level api and skip deserialization" mechanism clean and obvious.

Right now it's all very https://www.reddit.com/r/programmingcirclejerk/comments/4ojswl/classic_ok_its_not_a_database_how_do_i_query_it/

**Comment by bartelink** [comment]
I've also just checked a comparable service offering. Both the xmldoc and the real docs lead with the "what happens if it's not there". It does not throw an exception. (That SDK does not get involved in deserialization and the service does not offer an IfNoneMatch, so it's a bit simpler, but don't let that be an excuse). I use it via a wrapper library that offers a TryGetItem (which returns None) and a GetItem (which throws).

I don't think there's any real need to go comparing things in this way, but I am feeling a touch gaslit by the fact that I'm explaining and therefore losing despite mounds of evidence that things coudl quite easily be improved here.

**Comment by GoTo-Menyus777** [comment]
> This SDK is not outside of the umbrella of the Azure SDKs for .NET and thus, some behaviors cannot diverge. One of them is: https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-errors. Which says that if the StatusCode is not a success, an exception should be thrown.

What a terrible rule that contradicts core principles and best practices.. Also there are numerous articles how to push CosmosDB performance to the limit then we get to handle expected scenarios as exceptions which is notoriously expensive in .NET... Also someone above wrote it already that exceptions are for unexpected scenarios not for commonly expected scenarios like not found or item already exists ones..

I hope that one day at least you give an option to not throw exceptions but you provide us an Exception property that can be optionally consumed if desired and besides that we can just safely implement our own domain logic based on the status code.

Also anyone could link me the discussions where people are surprised that Not found "errors" are not thrown as exceptions?

**Comment by ealsur** [comment]
@GoTo-Menyus777 The option to not throw exceptions already exists and has always existed: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Exceptions.md#responsemessage-from-stream-apis-

Using the Stream APIs is your option if you prefer better performance, as you correctly mention, exceptions have CPU overhead. 

Both paths can be chosen depending on the user preference.

**Comment by GoTo-Menyus777** [comment]
Yeah you are right although it makes implementation a little bit "heavier" on our side just to achieve exceptionless flow (not a big deal really). I was just grumpy cos I wanted to write a oneliner call from your SDK and handle these expected flows very simply especially that the SDK handles transient errors and retrials. Which I was not sure that it does for the StreamAPI. But in your link I already see that it handles it.
Anyway I still think we are teaching anti patterns with this exception flow but since that guideline seems to be for the whole Azure SDK ecosystem this is not something that is easy or worth to change. I just hope that other Azure SDKs also support both flows.

**Comment by bartelink** [comment]
Reiterating [what I said](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/692#issuecomment-2016087743)

This ugliness and confusion could so easily be fixed by adding a TryReadItem and adjusting the docs.

Yes there is a workaround but:

**Saying "but we already have a lower level API so it's solved" is such an easy thing to provide a proper answer for.**

Please stop pretending that this is justifiable, regardless of the set of historical events that led us to this subobptimal state and the fact that Good Enough Software is Good Enough.
