### ISSUE TITLE
Consider supporting ConnectionMode in the connection string

### ISSUE THREAD

**Issue by GrimGadget** [Azure/azure-cosmos-dotnet-v3#759]
**Is your feature request related to a problem? Please describe.**
In some environments, we can use Direct connection mode with no problems, but in other environments, firewall policies force us to use Gateway mode.

It seems reasonable that ConnectionMode (and some of the other properties of CosmosClientOptions) should be configurable in app.config/settings.xml/etc.

**Describe the solution you'd like**
Add support to the CosmosClient(string connectionString) constructor for the ConnectionMode to be defined as part of the connection string, rather than having to be set in "my" code.

**Describe alternatives you've considered**
Obviously we could use a separate setting for this and wrap our constructor call in a chain of if statements, or inherit our own CosmosClient implementation and create our own constructor overload to support ConnectionMode in the connection string.

**Additional context**
ApplicationName, ApplicationRegion, GatewayModeMaxConnectionLimit, RequestTimeout,  ConsistencyLevel, MaxRetryAttemptsOnRateLimitedRequests, MaxRetryWaitTimeOnRateLimitedRequests, IdleTcpConnectionTimeout, OpenTcpConnectionTimeout, MaxRequestsPerTcpConnection, MaxTcpConnectionsPerEndpoint, and ConnectionProtocol should also be considered for inclusion in the connection string.

With Octopus Deploy (or similar deploy tools) and/or Azure App Config being used to manage environmental configuration differences, this will reduce the number of configuration variables that have to be managed.

It also seems like it would be useful on a broad enough scale to justify building it into the Microsoft.Azure.Cosmos framework rather than requiring each consumer to design and build their own solution to handle these settings.

**Comment by j82w** [comment]
I believe that the application should own loading the settings. The application should already have a way of loading settings for it's different properties. The issue with supporting app.config/setting.xml/etc is that there is really no standard. Every framework and operating system uses a different solution. Also having a different app.config/settings.xml/etc for each library doesn't make since.

The issue with connection strings is it's very easy to miss something. Right now if all the properties were put into a connection string it would have like 20 different properties in the string. It's very easy to miss a wrong value in a string like that. Any one of these values being wrong leads to an issue with an application in production. Even if you make the argument I only want ConnectionMode it opens the gates for all the other properties. If 1 additional property it will only be a matter of time before new issues are created asking for the rest of the properties.
