### ISSUE TITLE
Using GetItemLinqQueryable with inherited classes

### ISSUE THREAD

**Issue by NickSevens** [Azure/azure-cosmos-dotnet-v3#778]
When using `GetItemLinqQueryable<BaseClass>` I don't see any way to get the underlying inherited classes of the result set. Is there anyway to achieve this?
E.g.:
```
public class Animal { public string Name { get; set; } }
public class Cat : Animal { public int Lives { get; set; } }
public class Dog : Animal { public int Puppies { get; set; } }
...
container.GetItemLinqQueryable<Animal>()
```

The query above would result in a list of `Animal` objects, without being able to cast them to `Cat` or `Dog`.

Is there anyway to implement the same while not losing inheritance?
I keep thinking I'm just not getting something, and that I probably just can't wrap my head around it :(

Thanks

**Comment by j82w** [comment]
The problem is the JSON that is returned from Cosmos is just a list of properties. The serializer has to be told what object to convert the JSON to. I see these 3 possible solutions to your problem. Each has it own pros and cons. 
Option 1: Create a [custom serializer](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializer.cs) that handles the logic. In the JsonConverter it's possible to check the type and create an instance of Cat or Dog and return it as Animal. 
Option 2: Do a query on a JObject which is like a property bag. Then convert it to a Cat or Dog object, and insert it into a list of animals.
Option 3: Do separate queries then combine the results.

**Comment by NickSevens** [comment]
The first one seems the most elegant solution... I'll see what I can come up with :p
Thanks for the info!
