### ISSUE TITLE
API's throw exceptions instead of setting StatusCode property on ItemResponse

### ISSUE THREAD

**Issue by apulliam** [Azure/azure-cosmos-dotnet-v3#804]
With Cosmos SDK v3, all API's return a response object containing an StatusCode property along with data.  However, the API's (CreateItemAsync and ReadItemAsync) are throwing CosmosDbException's instead of returning errors in the StatusCode of ItemResponse.  CosmosDbException has its own StatusCode property which contains the error code.  What's the point of the StatusCode in the responses if its not used?  If the API's throw exceptions, remove StatusCode.

**To Reproduce**
Call CreateItemAsync with missing id or missing paritition key or call ReadItemAsync on an ID not in the DB.

**Expected behavior**
I would expect CreateItemAsync with errors in the document to return StatusCode= 400 (Bad Request) and ReadItemAsync on an ID not found to return StatusCode = 404 (Not Found)

**Actual behavior**
API's throw a CosmosDbException with error in the exception StatusCode property

**Environment summary**
SDK Version: Microsoft.Azure.Cosmos 3.1.1
OS Version (e.g. Windows, Linux, MacOSX) : Windows 10 1903

**Comment by j82w** [comment]
The reason ItemResponse has a status code is for upsert scenarios. Users gave feedback during the preview that they need to tell if it was a create or not. There is no error message or other exception info on ItemResponse. During the preview there was a lot of debates on if the SDK should throw or not. It came down to that the .NET guidelines say that it should throw, and that it matched the v2 behavior. 

The stream APIs do not throw because of performance reasons.
