### ISSUE TITLE
Throttling Retries

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-cosmos-dotnet-v3#88]
I saw in the examples how to use a custom handler to retry throttled requests. Do we have to manually do this or does the DocumentClient do this by default?

Thanks!

**Comment by ealsur** [comment]
The CosmosClient does this automatically, see https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/CosmosClientBuilder.cs#L208. The sample is in case you want to add more retries on top of the SDK ones or if you want to retry on other StatusCode or custom logic.

Since you can now step in the pipeline, you could implement custom StatusCodes that define some particular scenario and you could add retrying logic for it.

**Comment by mpaul31** [comment]
thank you!
