### ISSUE TITLE
azure v3 Unable to load DLL 'Microsoft.Azure.Cosmos.ServiceInterop.dll': Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

### ISSUE THREAD

**Issue by RaulGonzalezA** [Azure/azure-cosmos-dotnet-v3#881]
I'm trying to do an container.GetItemLinqQueryable<PartnerLog>(true).Where(x => x.Error == errorType).ToList();
where PartnerLog is a class to save log. and I've recieved azure v3 Unable to load DLL 'Microsoft.Azure.Cosmos.ServiceInterop.dll': Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) exception.

Te Error field is an Enum field. to add more info for the Issue.

**Comment by ealsur** [comment]
Can you specify which SDK version and what is the environment you are running on?

**Comment by RaulGonzalezA** [comment]
The SDK is NetCore.App 2.0 and I'm ussing the Azure.Cosmos 3.2.0. The environment is an API using the azure cosmos emulator in local.

**Comment by j82w** [comment]
In the bin folder does the Microsoft.Azure.Cosmos.ServiceInterop.dll exist? Is there any other application that could be taking a lock on it?

**Comment by RaulGonzalezA** [comment]
I don't have this dll in my team. Maybe could be this.

**Comment by ealsur** [comment]
Are you debugging from inside VS? From the command line with `dotnet run`? Is the folder mapped to a an IIS website?

**Comment by RaulGonzalezA** [comment]
Yes, I'm debugging inside VS. And yes is mapped to an IIS website

**Comment by ealsur** [comment]
If it's mapped to an IIS website, IIS might be locking the files. Can you try copying the project files to another folder, open VS there, and starting the debug session?

**Comment by RaulGonzalezA** [comment]
Ok... I'll try with IIS Expres and works. I've got administrator account, how I must procceed to solve this, because I need to have it in IIS.

**Comment by ealsur** [comment]
You can have the web app running in IIS and IIS Express. But when you debug inside VS, if the web app is running in IIS, you need to use Attach To Process to debug it. If you press F5, VS will try and run it in another IIS Express instance and that is when the conflict happens.

**Comment by RaulGonzalezA** [comment]
I've launch the debug in IIS, without attach to process, pressing F5, but doesn't work, and when I try to debug in IIS Expres works properly.

**Comment by ealsur** [comment]
When you work with IIS Express, with the project in another folder, it works because there is no other web server accessing the files.
When you open the project in the folder that is mapped to IIS, and you launch VS with F5, it won't work because VS will launch another webserver that won't be able to access the locked file that IIS is locking.

You need to open a VS instance as Admiinstrator (this needs to be explicit, you need to right-click the VS icon and choose `Run as Administrator`), then go to Debug > Attach to Process, check `Show processes from all users`, find the `w3wp` process that is running your IIS application and attach to it. That is the only way you can debug in VS an application that is running in IIS. Make sure your VS configuration is set to `Debug` too.

**Comment by RaulGonzalezA** [comment]
I always open my VS as Administrator. I don't have w3wp process running in my machine, so can't attach it to my VS. When I launch as usual my VS to debug doesn't appears this process neither.

**Comment by RaulGonzalezA** [comment]
I'll do as here is explained:
[https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-enable-debugging-for-aspnet-applications.md](url) how-to-enable-debugging-for-aspnet-applications

**Comment by RaulGonzalezA** [comment]
Is not a Web application. Is an API.

**Comment by ealsur** [comment]
What is still not working? You don't see any `w3wp` process after you do a request to the API that is hosted by IIS? Does the API respond to that request with a correct response?
 
If API responds, then it must be running in a `w3wp` process and you should see it in the list of processes in Visual Studio if you opened the Debug window after doing the request (otherwise IIS tends to kill the `w3wp` process if there is innactivity). Unless you have changed the default behavior of IIS.

The root cause of this issue is the fact that the Interop DLL is being locked by some external process (ISS) and you cannot simply F5 Debug the application in that folder due to this reason. That was proved when you copied the files outside and F5 Debug'ed there and it worked. Either remove the lock (shutdown IIS) to debug from IIS, or find a way to attach a debugger to the current IIS process (what we have been trying).

**Comment by RaulGonzalezA** [comment]
I've seen w3wp, I've attach the debugger to the process and still having the same error.

**Comment by ealsur** [comment]
Are the breakpoints you set in VS being hit? Is the IIS Application Pool set with the default identity?

Go to the folder in a CMD / command prompt where the `Microsoft.Azure.Cosmos.ServiceInterop.dll` is and run `tasklist /m Microsoft.Azure.Cosmos.ServiceInterop.dll`.

Check the Permissions on the file, do they include the IIS application identity and the user under which VS is running?

Are the files in a shared network folder?

**Comment by ealsur** [comment]
Please reopen if you have any more information for the scenario following the last questions.

**Comment by JosephPinedo** [comment]
@RaulGonzalezA were you able to find a solution for this issue? I too am running a .Net Core 2.x web app locally in IIS with the latest Cosmos SDK version (3.24.0) and am running into the same exception:

"Unable to load DLL 'Microsoft.Azure.Cosmos.ServiceInterop.dll': Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)) exception."

@ealsur, you all didn't find out the cause for this issue by any chance too?

**Comment by ealsur** [comment]
Not really, there was no reply after the last comment 2+ years ago on the permissions check. The identity on which the files are accessed depends on IIS and the permissions on those files would need to match.

**Comment by JosephPinedo** [comment]
Was reading the earlier comments.. and IIS Express did not work. This exception is not being thrown if I use IIS Express.

So to your point seems like an IIS permissions/lock issue. I ensured that the IIS user has full permissions to the dll file but I am still getting the same error...

I was trying to understand the last suggestions posted here and wasn't sure on the next steps forward... is there possibly more information I can furnish that would be helpful?

**Comment by JosephPinedo** [comment]
No need to look into this any further; but thank you for your quick response earlier!

I was able to find out the solution needed. Turns out even though the error message being thrown was "Access is denied"; I uncovered that a "DllNotFoundException" was being silently logged in the Debug console roughly whenever I executed the  function "CreateAndInitializeAsync".

This then turned my attention away from a possible permissions issue and more towards the possibility that the DLL simply could not be found, I found an article (somewhere) where someone was experiencing a "Module not found" error and a workaround was to add the DLL folder location to the PATH environment variable. This fixed my issue!

Although I do not need the fix ASAP anymore since I found a workaround; could you all possibly address this issue?

I do also worry about whether I will be still be able to host our web app in our existing Azure App Service since I don't think I am able to modify environment variables there... and I know of course that Windows Azure App Service's use IIS. Will need to test and find out.

**Comment by ealsur** [comment]
Curious, was the PATH you added the same `bin` folder of the application or a different one? IIS sometimes has this "Shadow Copy" feature that will copy DLLs into temporary folders.

**Comment by JosephPinedo** [comment]
Tested this on a Azure App Service and it worked just fine. Seems to perhaps be an issue that only exhibits itself on Windows 10.
