### ISSUE TITLE
Specifying ApplicationRegion results in significantly longer timeouts

### ISSUE THREAD

**Issue by afscrome** [Azure/azure-cosmos-dotnet-v3#931]
**Describe the bug**

If `ApplicationRegion` is specified on `CosmosClientOptions` and you forget to start the emulator, the SDK takes about 2 minutes before timing out.  If you remove the `ApplicationRegion`, it only takes 10 seconds or so to fail.

**To Reproduce**

Run the following code, making sure the cosmos emulator is **NOT** started, and note the elapsed time.  Remove `ApplicationRegion = "North Europe",` and repeat. 

```cs
static async Task Main()
{
    var options = new CosmosClientOptions
    {
        ApplicationRegion = "North Europe",
        RequestTimeout = TimeSpan.FromMilliseconds(100)
    };

    var client = new CosmosClient(
        "https://localhost:8081",
        "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==",
        options);

    var stopwatch = new Stopwatch();
    stopwatch.Start();
    try
    {
        await client.ReadAccountAsync();
    }
    finally
    {
        Console.WriteLine($"Elapsed: {stopwatch.Elapsed}");
    }
}
```

**Expected behaviour**
I would expect that the timeout if the cosmos emulator is not running should be the same regardless of whether `ApplicationRegion` is specified or not.

**Actual behaviour**
When `ApplicationRegion` is specified, timeout jumps from ~10 secs to ~2 minutes.

**Environment summary**
SDK Version: 3.3.2
OS Version: Windows 3.3.2

**Additional context**

A similar issue can be seen with `SetCurrentLocation` in the v2 sdk - https://gist.github.com/afscrome/0b8073b748a0da8185b9d93770d0e26e

**Comment by ealsur** [comment]
The timeout is due to the fact that the SDK is trying to resolve the DNS for the region and such a DNS is impossible to resolve when you use the Emulator.

There is no way for the SDK to detect that you are using the Emulator, since the URI could be masked, a redirection, or a local DNS record that points to a running emulator, so it cannot add some `if` logic to not try and reach the desired region.

If you are using the Emulator, just not populate the ApplicationRegion, because that in itself is not true (the Emulator is not in Azure North Europe, it's local).
