### ISSUE TITLE
Allow consumption of Change Feed as a in-memory push model

### ISSUE THREAD

**Issue by AndreasHassing** [Azure/azure-cosmos-dotnet-v3#972]
**Is your feature request related to a problem? Please describe.**
We're using ChangeFeedProcessor to update in-memory caches. When an instance of the application dies, a new one takes its place (either via rolling upgrade or failures) and the CFP lease is orphaned (requiring cleanup, sooner or later).

**Describe the solution you'd like**
Allow us to bypass the need for a lease container to read from the change feed. One solution might be to make `ChangeFeedProcessorBuilder.WithInMemoryLeaseContainer()` public with a way of specifying whether to start from the beginning or end of the change feed. We are able to take snapshots and would just read from the end when starting the application.

**Describe alternatives you've considered**
Keep using the existing model and clean up CFP lease containers that haven't moved (cont. token not brought up to level within `n` time) - this is less than ideal when the in-memory lease container seems to do exactly what we need, without requiring any cleanup in Cosmos.

Request sprung from discussions in #831.

**Comment by RomanKreisel** [comment]
Exactly same issue here - we don't need to have our leases, because we use the changefeed only to update an internal in-memory cache.

Right now, we stick with v2 of the SDK for the ChangefeedProcessor just because of this issue.

**Comment by liquidsnk** [comment]
Hello @ealsur, how comes that PR closed this ticket? Isn't that just for the pull model? Or you've decided against working on an in-memory push model? I've got here because I have have a similar scenario as above for using the change-feed. I can work around using the pull model which is nice, but I think push would be cleaner.

**Comment by ealsur** [comment]
@liquidsnk In-memory push scenarios are better served by the Change Feed pull model. Because In-memory has really no benefits (no load balancing nor distribution) over the Pull model. Pull gives more control on the frequency and even lets you store the state if you desire so (also in a controlled fashion, since you can store the continuation token anywhere you want). It is also easier if you are using it in a background process (for example, a Background Host in an ASP.NET app).

**Comment by liquidsnk** [comment]
Thanks for your answer!, my scenario is as above, updating an in-memory cache for a service with changes coming trough the change-feed. My plan is to do that from a hosted service as you mention. I can manage just fine with the pull model and as you say it does give me more control. My thinking was that using the push model would allow me to make the initial implementation/prototype much easier by basically providing just a handler instead of having to worry about the details of polling the feed myself.

**Comment by ealsur** [comment]
The problem is that CFP adds a lot of threads/Tasks in the background for this simple scenario. It would start one parallel set of Tasks for each partition, where each set contains a Task to renew the in-memory leases, a Task to read the changes, and a Task to do cross partition synchronization. It's just a lot of things that won't yield any benefit and will potentially add overhead.

With the pull model you can have your Background host periodically just call ReadNextAsync on the FeedIterator. From the lines of code perspective I believe they are pretty similar, both would need a setup (configuring and starting the CFP vs creating the FeedIterator), and consuming it (create a handler or call ReadNextAsync and handle the changes). So you end up coding more or less the same amount and one does not generate the Task overhead.
